// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001181Component } from './my.001181.component';

@NgModule({
  declarations: [
    My001181Component,
  ],
  imports: [CommonModule],
  exports: [
    My001181Component,
  ]
})
export class Module000981 { }
