// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001181',
  templateUrl: './my.001181.component.html'
})
export class My001181Component {
  @Input() parentName: string;
  myName = 'My001181Component';
}
