// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000702Component } from './my.000702.component';

@NgModule({
  declarations: [
    My000702Component,
  ],
  imports: [CommonModule],
  exports: [
    My000702Component,
  ]
})
export class Module000502 { }
