// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000702',
  templateUrl: './my.000702.component.html'
})
export class My000702Component {
  @Input() parentName: string;
  myName = 'My000702Component';
}
