// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000316Component } from './my.000316.component';

@NgModule({
  declarations: [
    My000316Component,
  ],
  imports: [CommonModule],
  exports: [
    My000316Component,
  ]
})
export class Module000216 { }
