// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000549',
  templateUrl: './my.000549.component.html'
})
export class My000549Component {
  @Input() parentName: string;
  myName = 'My000549Component';
}
