// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000091Component } from './my.000091.component';

@NgModule({
  declarations: [
    My000091Component,
  ],
  imports: [CommonModule],
  exports: [
    My000091Component,
  ]
})
export class Module000071 { }
