// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000142Component } from './my.000142.component';
import { My000143Component } from './my.000143.component';

@NgModule({
  declarations: [
    My000142Component,
    My000143Component,
  ],
  imports: [CommonModule],
  exports: [
    My000142Component,
=======
import { My000091Component } from './my.000091.component';

@NgModule({
  declarations: [
    My000091Component,
  ],
  imports: [CommonModule],
  exports: [
    My000091Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000071 { }
