// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000143',
  templateUrl: './my.000143.component.html'
})
export class My000143Component {
  @Input() parentName: string;
  myName = 'My000143Component';
}
