// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000456Component } from './my.000456.component';

@NgModule({
  declarations: [
    My000456Component,
  ],
  imports: [CommonModule],
  exports: [
    My000456Component,
  ]
})
export class Module000256 { }
