// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000356Component } from './my.000356.component';

@NgModule({
  declarations: [
    My000356Component,
  ],
  imports: [CommonModule],
  exports: [
    My000356Component,
  ]
})
export class Module000256 { }
