// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000989Component } from './my.000989.component';

@NgModule({
  declarations: [
    My000989Component,
  ],
  imports: [CommonModule],
  exports: [
    My000989Component,
  ]
})
export class Module000789 { }
