// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000989',
  templateUrl: './my.000989.component.html'
})
export class My000989Component {
  @Input() parentName: string;
  myName = 'My000989Component';
}
