// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000889',
  templateUrl: './my.000889.component.html'
})
export class My000889Component {
  @Input() parentName: string;
  myName = 'My000889Component';
}
