// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000604',
  templateUrl: './my.000604.component.html'
})
export class My000604Component {
  @Input() parentName: string;
  myName = 'My000604Component';
}
