// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000772',
  templateUrl: './my.000772.component.html'
})
export class My000772Component {
  @Input() parentName: string;
  myName = 'My000772Component';
}
