// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000254Component } from './my.000254.component';
import { My000255Component } from './my.000255.component';

@NgModule({
  declarations: [
    My000254Component,
    My000255Component,
  ],
  imports: [CommonModule],
  exports: [
    My000254Component,
  ]
})
export class Module000127 { }
