// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000227',
  templateUrl: './my.000227.component.html'
})
export class My000227Component {
  @Input() parentName: string;
  myName = 'My000227Component';
}
