// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000957Component } from './my.000957.component';

@NgModule({
  declarations: [
    My000957Component,
  ],
  imports: [CommonModule],
  exports: [
    My000957Component,
  ]
})
export class Module000857 { }
