// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000957',
  templateUrl: './my.000957.component.html'
})
export class My000957Component {
  @Input() parentName: string;
  myName = 'My000957Component';
}
