// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001057',
  templateUrl: './my.001057.component.html'
})
export class My001057Component {
  @Input() parentName: string;
  myName = 'My001057Component';
}
