// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000935',
  templateUrl: './my.000935.component.html'
})
export class My000935Component {
  @Input() parentName: string;
  myName = 'My000935Component';
}
