// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000984Component } from './my.000984.component';

@NgModule({
  declarations: [
    My000984Component,
  ],
  imports: [CommonModule],
  exports: [
    My000984Component,
  ]
})
export class Module000784 { }
