// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000849Component } from './my.000849.component';

@NgModule({
  declarations: [
    My000849Component,
  ],
  imports: [CommonModule],
  exports: [
    My000849Component,
  ]
})
export class Module000649 { }
