// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000749Component } from './my.000749.component';

@NgModule({
  declarations: [
    My000749Component,
  ],
  imports: [CommonModule],
  exports: [
    My000749Component,
  ]
})
export class Module000649 { }
