// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000623Component } from './my.000623.component';

@NgModule({
  declarations: [
    My000623Component,
  ],
  imports: [CommonModule],
  exports: [
    My000623Component,
  ]
})
export class Module000523 { }
