// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000941Component } from './my.000941.component';

@NgModule({
  declarations: [
    My000941Component,
  ],
  imports: [CommonModule],
  exports: [
    My000941Component,
  ]
})
export class Module000741 { }
