// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000641Component } from './my.000641.component';

@NgModule({
  declarations: [
    My000641Component,
  ],
  imports: [CommonModule],
  exports: [
    My000641Component,
  ]
})
export class Module000541 { }
