// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000317Component } from './my.000317.component';

@NgModule({
  declarations: [
    My000317Component,
  ],
  imports: [CommonModule],
  exports: [
    My000317Component,
  ]
})
export class Module000217 { }
