// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000519Component } from './my.000519.component';

@NgModule({
  declarations: [
    My000519Component,
  ],
  imports: [CommonModule],
  exports: [
    My000519Component,
  ]
})
export class Module000419 { }
