// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000532',
  templateUrl: './my.000532.component.html'
})
export class My000532Component {
  @Input() parentName: string;
  myName = 'My000532Component';
}
