// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000480Component } from './my.000480.component';

@NgModule({
  declarations: [
    My000480Component,
  ],
  imports: [CommonModule],
  exports: [
    My000480Component,
  ]
})
export class Module000280 { }
