// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000480',
  templateUrl: './my.000480.component.html'
})
export class My000480Component {
  @Input() parentName: string;
  myName = 'My000480Component';
}
