// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000380',
  templateUrl: './my.000380.component.html'
})
export class My000380Component {
  @Input() parentName: string;
  myName = 'My000380Component';
}
