// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001060Component } from './my.001060.component';

@NgModule({
  declarations: [
    My001060Component,
  ],
  imports: [CommonModule],
  exports: [
    My001060Component,
  ]
})
export class Module000960 { }
