// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000565',
  templateUrl: './my.000565.component.html'
})
export class My000565Component {
  @Input() parentName: string;
  myName = 'My000565Component';
}
