// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000697',
  templateUrl: './my.000697.component.html'
})
export class My000697Component {
  @Input() parentName: string;
  myName = 'My000697Component';
}
