// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000642Component } from './my.000642.component';

@NgModule({
  declarations: [
    My000642Component,
  ],
  imports: [CommonModule],
  exports: [
    My000642Component,
  ]
})
export class Module000542 { }
