// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000855Component } from './my.000855.component';

@NgModule({
  declarations: [
    My000855Component,
  ],
  imports: [CommonModule],
  exports: [
    My000855Component,
  ]
})
export class Module000655 { }
