// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000462Component } from './my.000462.component';

@NgModule({
  declarations: [
    My000462Component,
  ],
  imports: [CommonModule],
  exports: [
    My000462Component,
  ]
})
export class Module000262 { }
