// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000362',
  templateUrl: './my.000362.component.html'
})
export class My000362Component {
  @Input() parentName: string;
  myName = 'My000362Component';
}
