// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001048Component } from './my.001048.component';

@NgModule({
  declarations: [
    My001048Component,
  ],
  imports: [CommonModule],
  exports: [
    My001048Component,
  ]
})
export class Module000848 { }
