// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000948Component } from './my.000948.component';

@NgModule({
  declarations: [
    My000948Component,
  ],
  imports: [CommonModule],
  exports: [
    My000948Component,
  ]
})
export class Module000848 { }
