// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000386Component } from './my.000386.component';
import { My000387Component } from './my.000387.component';

@NgModule({
  declarations: [
    My000386Component,
    My000387Component,
  ],
  imports: [CommonModule],
  exports: [
    My000386Component,
  ]
})
export class Module000193 { }
