// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000386',
  templateUrl: './my.000386.component.html'
})
export class My000386Component {
  @Input() parentName: string;
  myName = 'My000386Component';
}
