// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000293',
  templateUrl: './my.000293.component.html'
})
export class My000293Component {
  @Input() parentName: string;
  myName = 'My000293Component';
}
