// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000515Component } from './my.000515.component';

@NgModule({
  declarations: [
    My000515Component,
  ],
  imports: [CommonModule],
  exports: [
    My000515Component,
  ]
})
export class Module000315 { }
