// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000415',
  templateUrl: './my.000415.component.html'
})
export class My000415Component {
  @Input() parentName: string;
  myName = 'My000415Component';
}
