// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000515',
  templateUrl: './my.000515.component.html'
})
export class My000515Component {
  @Input() parentName: string;
  myName = 'My000515Component';
}
