// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000396Component } from './my.000396.component';
import { My000397Component } from './my.000397.component';

@NgModule({
  declarations: [
    My000396Component,
    My000397Component,
  ],
  imports: [CommonModule],
  exports: [
    My000396Component,
  ]
})
export class Module000198 { }
