// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000298',
  templateUrl: './my.000298.component.html'
})
export class My000298Component {
  @Input() parentName: string;
  myName = 'My000298Component';
}
