// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000396',
  templateUrl: './my.000396.component.html'
})
export class My000396Component {
  @Input() parentName: string;
  myName = 'My000396Component';
}
