// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000887Component } from './my.000887.component';

@NgModule({
  declarations: [
    My000887Component,
  ],
  imports: [CommonModule],
  exports: [
    My000887Component,
  ]
})
export class Module000787 { }
