// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000887',
  templateUrl: './my.000887.component.html'
})
export class My000887Component {
  @Input() parentName: string;
  myName = 'My000887Component';
}
