// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000095Component } from './my.000095.component';

@NgModule({
  declarations: [
    My000095Component,
  ],
  imports: [CommonModule],
  exports: [
    My000095Component,
  ]
})
export class Module000075 { }
