// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000150Component } from './my.000150.component';
import { My000151Component } from './my.000151.component';

@NgModule({
  declarations: [
    My000150Component,
    My000151Component,
  ],
  imports: [CommonModule],
  exports: [
    My000150Component,
=======
import { My000095Component } from './my.000095.component';

@NgModule({
  declarations: [
    My000095Component,
  ],
  imports: [CommonModule],
  exports: [
    My000095Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000075 { }
