// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000151',
  templateUrl: './my.000151.component.html'
})
export class My000151Component {
  @Input() parentName: string;
  myName = 'My000151Component';
}
