// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000882',
  templateUrl: './my.000882.component.html'
})
export class My000882Component {
  @Input() parentName: string;
  myName = 'My000882Component';
}
