// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000537Component } from './my.000537.component';

@NgModule({
  declarations: [
    My000537Component,
  ],
  imports: [CommonModule],
  exports: [
    My000537Component,
  ]
})
export class Module000337 { }
