// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000437Component } from './my.000437.component';

@NgModule({
  declarations: [
    My000437Component,
  ],
  imports: [CommonModule],
  exports: [
    My000437Component,
  ]
})
export class Module000337 { }
