// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000574Component } from './my.000574.component';

@NgModule({
  declarations: [
    My000574Component,
  ],
  imports: [CommonModule],
  exports: [
    My000574Component,
  ]
})
export class Module000474 { }
