// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000674Component } from './my.000674.component';

@NgModule({
  declarations: [
    My000674Component,
  ],
  imports: [CommonModule],
  exports: [
    My000674Component,
  ]
})
export class Module000474 { }
