// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000863Component } from './my.000863.component';

@NgModule({
  declarations: [
    My000863Component,
  ],
  imports: [CommonModule],
  exports: [
    My000863Component,
  ]
})
export class Module000663 { }
