// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000763',
  templateUrl: './my.000763.component.html'
})
export class My000763Component {
  @Input() parentName: string;
  myName = 'My000763Component';
}
