// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000135',
  templateUrl: './my.000135.component.html'
})
export class My000135Component {
  @Input() parentName: string;
  myName = 'My000135Component';
}
