// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000087',
  templateUrl: './my.000087.component.html'
})
export class My000087Component {
  @Input() parentName: string;
  myName = 'My000087Component';
}
