// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000012Component } from './my.000012.component';
import { My000013Component } from './my.000013.component';

@NgModule({
  declarations: [
    My000012Component,
    My000013Component,
  ],
  imports: [CommonModule],
  exports: [
    My000012Component,
  ]
})
export class Module000006 { }
