// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000013',
  templateUrl: './my.000013.component.html'
})
export class My000013Component {
  @Input() parentName: string;
  myName = 'My000013Component';
}
