// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000041Component } from './my.000041.component';

@NgModule({
  declarations: [
    My000041Component,
  ],
  imports: [CommonModule],
  exports: [
    My000041Component,
  ]
})
export class Module000021 { }
