// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000042',
  templateUrl: './my.000042.component.html'
})
export class My000042Component {
  @Input() parentName: string;
  myName = 'My000042Component';
}
