// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000043',
  templateUrl: './my.000043.component.html'
})
export class My000043Component {
  @Input() parentName: string;
  myName = 'My000043Component';
}
