// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001003Component } from './my.001003.component';

@NgModule({
  declarations: [
    My001003Component,
  ],
  imports: [CommonModule],
  exports: [
    My001003Component,
  ]
})
export class Module000903 { }
