// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001103Component } from './my.001103.component';

@NgModule({
  declarations: [
    My001103Component,
  ],
  imports: [CommonModule],
  exports: [
    My001103Component,
  ]
})
export class Module000903 { }
