// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000262',
  templateUrl: './my.000262.component.html'
})
export class My000262Component {
  @Input() parentName: string;
  myName = 'My000262Component';
}
