// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000089Component } from './my.000089.component';

@NgModule({
  declarations: [
    My000089Component,
  ],
  imports: [CommonModule],
  exports: [
    My000089Component,
  ]
})
export class Module000069 { }
