// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000139',
  templateUrl: './my.000139.component.html'
})
export class My000139Component {
  @Input() parentName: string;
  myName = 'My000139Component';
}
