// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000138',
  templateUrl: './my.000138.component.html'
})
export class My000138Component {
  @Input() parentName: string;
  myName = 'My000138Component';
}
