// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000603Component } from './my.000603.component';

@NgModule({
  declarations: [
    My000603Component,
  ],
  imports: [CommonModule],
  exports: [
    My000603Component,
  ]
})
export class Module000503 { }
