// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000286Component } from './my.000286.component';
import { My000287Component } from './my.000287.component';

@NgModule({
  declarations: [
    My000286Component,
    My000287Component,
  ],
  imports: [CommonModule],
  exports: [
    My000286Component,
  ]
})
export class Module000143 { }
