// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000880Component } from './my.000880.component';

@NgModule({
  declarations: [
    My000880Component,
  ],
  imports: [CommonModule],
  exports: [
    My000880Component,
  ]
})
export class Module000680 { }
