// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000939Component } from './my.000939.component';

@NgModule({
  declarations: [
    My000939Component,
  ],
  imports: [CommonModule],
  exports: [
    My000939Component,
  ]
})
export class Module000739 { }
