// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001117Component } from './my.001117.component';

@NgModule({
  declarations: [
    My001117Component,
  ],
  imports: [CommonModule],
  exports: [
    My001117Component,
  ]
})
export class Module000917 { }
