// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001117',
  templateUrl: './my.001117.component.html'
})
export class My001117Component {
  @Input() parentName: string;
  myName = 'My001117Component';
}
