// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000217Component } from './my.000217.component';

@NgModule({
  declarations: [
    My000217Component,
  ],
  imports: [CommonModule],
  exports: [
    My000217Component,
  ]
})
export class Module000117 { }
