// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000234Component } from './my.000234.component';
import { My000235Component } from './my.000235.component';

@NgModule({
  declarations: [
    My000234Component,
    My000235Component,
  ],
  imports: [CommonModule],
  exports: [
    My000234Component,
  ]
})
export class Module000117 { }
