// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000228Component } from './my.000228.component';
import { My000229Component } from './my.000229.component';

@NgModule({
  declarations: [
    My000228Component,
    My000229Component,
  ],
  imports: [CommonModule],
  exports: [
    My000228Component,
  ]
})
export class Module000114 { }
