// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000228',
  templateUrl: './my.000228.component.html'
})
export class My000228Component {
  @Input() parentName: string;
  myName = 'My000228Component';
}
