// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000214',
  templateUrl: './my.000214.component.html'
})
export class My000214Component {
  @Input() parentName: string;
  myName = 'My000214Component';
}
