// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000204Component } from './my.000204.component';

@NgModule({
  declarations: [
    My000204Component,
  ],
  imports: [CommonModule],
  exports: [
    My000204Component,
  ]
})
export class Module000104 { }
