// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000204',
  templateUrl: './my.000204.component.html'
})
export class My000204Component {
  @Input() parentName: string;
  myName = 'My000204Component';
}
