// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000427',
  templateUrl: './my.000427.component.html'
})
export class My000427Component {
  @Input() parentName: string;
  myName = 'My000427Component';
}
