// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001016',
  templateUrl: './my.001016.component.html'
})
export class My001016Component {
  @Input() parentName: string;
  myName = 'My001016Component';
}
