// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000312Component } from './my.000312.component';

@NgModule({
  declarations: [
    My000312Component,
  ],
  imports: [CommonModule],
  exports: [
    My000312Component,
  ]
})
export class Module000212 { }
