// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000934',
  templateUrl: './my.000934.component.html'
})
export class My000934Component {
  @Input() parentName: string;
  myName = 'My000934Component';
}
