// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001189Component } from './my.001189.component';

@NgModule({
  declarations: [
    My001189Component,
  ],
  imports: [CommonModule],
  exports: [
    My001189Component,
  ]
})
export class Module000989 { }
