// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001114',
  templateUrl: './my.001114.component.html'
})
export class My001114Component {
  @Input() parentName: string;
  myName = 'My001114Component';
}
