// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000823Component } from './my.000823.component';

@NgModule({
  declarations: [
    My000823Component,
  ],
  imports: [CommonModule],
  exports: [
    My000823Component,
  ]
})
export class Module000623 { }
