// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000723',
  templateUrl: './my.000723.component.html'
})
export class My000723Component {
  @Input() parentName: string;
  myName = 'My000723Component';
}
