// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000235Component } from './my.000235.component';

@NgModule({
  declarations: [
    My000235Component,
  ],
  imports: [CommonModule],
  exports: [
    My000235Component,
  ]
})
export class Module000135 { }
