// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000998Component } from './my.000998.component';

@NgModule({
  declarations: [
    My000998Component,
  ],
  imports: [CommonModule],
  exports: [
    My000998Component,
  ]
})
export class Module000898 { }
