// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000998',
  templateUrl: './my.000998.component.html'
})
export class My000998Component {
  @Input() parentName: string;
  myName = 'My000998Component';
}
