// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000712Component } from './my.000712.component';

@NgModule({
  declarations: [
    My000712Component,
  ],
  imports: [CommonModule],
  exports: [
    My000712Component,
  ]
})
export class Module000512 { }
