// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000612Component } from './my.000612.component';

@NgModule({
  declarations: [
    My000612Component,
  ],
  imports: [CommonModule],
  exports: [
    My000612Component,
  ]
})
export class Module000512 { }
