// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000712',
  templateUrl: './my.000712.component.html'
})
export class My000712Component {
  @Input() parentName: string;
  myName = 'My000712Component';
}
