// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000451',
  templateUrl: './my.000451.component.html'
})
export class My000451Component {
  @Input() parentName: string;
  myName = 'My000451Component';
}
