// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000551',
  templateUrl: './my.000551.component.html'
})
export class My000551Component {
  @Input() parentName: string;
  myName = 'My000551Component';
}
