// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000696Component } from './my.000696.component';

@NgModule({
  declarations: [
    My000696Component,
  ],
  imports: [CommonModule],
  exports: [
    My000696Component,
  ]
})
export class Module000596 { }
