// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000696',
  templateUrl: './my.000696.component.html'
})
export class My000696Component {
  @Input() parentName: string;
  myName = 'My000696Component';
}
