// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000090Component } from './my.000090.component';
import { My000091Component } from './my.000091.component';

@NgModule({
  declarations: [
    My000090Component,
    My000091Component,
  ],
  imports: [CommonModule],
  exports: [
    My000090Component,
  ]
})
export class Module000045 { }
