// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001033Component } from './my.001033.component';

@NgModule({
  declarations: [
    My001033Component,
  ],
  imports: [CommonModule],
  exports: [
    My001033Component,
  ]
})
export class Module000933 { }
