// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000882Component } from './my.000882.component';

@NgModule({
  declarations: [
    My000882Component,
  ],
  imports: [CommonModule],
  exports: [
    My000882Component,
  ]
})
export class Module000782 { }
