// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000982Component } from './my.000982.component';

@NgModule({
  declarations: [
    My000982Component,
  ],
  imports: [CommonModule],
  exports: [
    My000982Component,
  ]
})
export class Module000782 { }
