// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000321Component } from './my.000321.component';

@NgModule({
  declarations: [
    My000321Component,
  ],
  imports: [CommonModule],
  exports: [
    My000321Component,
  ]
})
export class Module000221 { }
