// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000358Component } from './my.000358.component';

@NgModule({
  declarations: [
    My000358Component,
  ],
  imports: [CommonModule],
  exports: [
    My000358Component,
  ]
})
export class Module000258 { }
