// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000358',
  templateUrl: './my.000358.component.html'
})
export class My000358Component {
  @Input() parentName: string;
  myName = 'My000358Component';
}
