// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000942',
  templateUrl: './my.000942.component.html'
})
export class My000942Component {
  @Input() parentName: string;
  myName = 'My000942Component';
}
