// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001042',
  templateUrl: './my.001042.component.html'
})
export class My001042Component {
  @Input() parentName: string;
  myName = 'My001042Component';
}
