// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000509Component } from './my.000509.component';

@NgModule({
  declarations: [
    My000509Component,
  ],
  imports: [CommonModule],
  exports: [
    My000509Component,
  ]
})
export class Module000309 { }
