// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000527Component } from './my.000527.component';

@NgModule({
  declarations: [
    My000527Component,
  ],
  imports: [CommonModule],
  exports: [
    My000527Component,
  ]
})
export class Module000427 { }
