// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000627Component } from './my.000627.component';

@NgModule({
  declarations: [
    My000627Component,
  ],
  imports: [CommonModule],
  exports: [
    My000627Component,
  ]
})
export class Module000427 { }
