// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000527',
  templateUrl: './my.000527.component.html'
})
export class My000527Component {
  @Input() parentName: string;
  myName = 'My000527Component';
}
