// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000464Component } from './my.000464.component';

@NgModule({
  declarations: [
    My000464Component,
  ],
  imports: [CommonModule],
  exports: [
    My000464Component,
  ]
})
export class Module000364 { }
