// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000564Component } from './my.000564.component';

@NgModule({
  declarations: [
    My000564Component,
  ],
  imports: [CommonModule],
  exports: [
    My000564Component,
  ]
})
export class Module000364 { }
