// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000501Component } from './my.000501.component';

@NgModule({
  declarations: [
    My000501Component,
  ],
  imports: [CommonModule],
  exports: [
    My000501Component,
  ]
})
export class Module000301 { }
