// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000851Component } from './my.000851.component';

@NgModule({
  declarations: [
    My000851Component,
  ],
  imports: [CommonModule],
  exports: [
    My000851Component,
  ]
})
export class Module000751 { }
