// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000686Component } from './my.000686.component';

@NgModule({
  declarations: [
    My000686Component,
  ],
  imports: [CommonModule],
  exports: [
    My000686Component,
  ]
})
export class Module000486 { }
