// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000586Component } from './my.000586.component';

@NgModule({
  declarations: [
    My000586Component,
  ],
  imports: [CommonModule],
  exports: [
    My000586Component,
  ]
})
export class Module000486 { }
