// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000586',
  templateUrl: './my.000586.component.html'
})
export class My000586Component {
  @Input() parentName: string;
  myName = 'My000586Component';
}
