// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000686',
  templateUrl: './my.000686.component.html'
})
export class My000686Component {
  @Input() parentName: string;
  myName = 'My000686Component';
}
