// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000252Component } from './my.000252.component';

@NgModule({
  declarations: [
    My000252Component,
  ],
  imports: [CommonModule],
  exports: [
    My000252Component,
  ]
})
export class Module000152 { }
