// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000304Component } from './my.000304.component';
import { My000305Component } from './my.000305.component';

@NgModule({
  declarations: [
    My000304Component,
    My000305Component,
  ],
  imports: [CommonModule],
  exports: [
    My000304Component,
  ]
})
export class Module000152 { }
