// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000252',
  templateUrl: './my.000252.component.html'
})
export class My000252Component {
  @Input() parentName: string;
  myName = 'My000252Component';
}
