// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000447',
  templateUrl: './my.000447.component.html'
})
export class My000447Component {
  @Input() parentName: string;
  myName = 'My000447Component';
}
