// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000618',
  templateUrl: './my.000618.component.html'
})
export class My000618Component {
  @Input() parentName: string;
  myName = 'My000618Component';
}
