// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001001Component } from './my.001001.component';

@NgModule({
  declarations: [
    My001001Component,
  ],
  imports: [CommonModule],
  exports: [
    My001001Component,
  ]
})
export class Module000901 { }
