// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000299Component } from './my.000299.component';

@NgModule({
  declarations: [
    My000299Component,
  ],
  imports: [CommonModule],
  exports: [
    My000299Component,
  ]
})
export class Module000199 { }
