// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000398Component } from './my.000398.component';
import { My000399Component } from './my.000399.component';

@NgModule({
  declarations: [
    My000398Component,
    My000399Component,
  ],
  imports: [CommonModule],
  exports: [
    My000398Component,
  ]
})
export class Module000199 { }
