// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000299',
  templateUrl: './my.000299.component.html'
})
export class My000299Component {
  @Input() parentName: string;
  myName = 'My000299Component';
}
