// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000277Component } from './my.000277.component';

@NgModule({
  declarations: [
    My000277Component,
  ],
  imports: [CommonModule],
  exports: [
    My000277Component,
  ]
})
export class Module000177 { }
