// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000277',
  templateUrl: './my.000277.component.html'
})
export class My000277Component {
  @Input() parentName: string;
  myName = 'My000277Component';
}
