// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000974Component } from './my.000974.component';

@NgModule({
  declarations: [
    My000974Component,
  ],
  imports: [CommonModule],
  exports: [
    My000974Component,
  ]
})
export class Module000874 { }
