// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000974',
  templateUrl: './my.000974.component.html'
})
export class My000974Component {
  @Input() parentName: string;
  myName = 'My000974Component';
}
