// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000968Component } from './my.000968.component';

@NgModule({
  declarations: [
    My000968Component,
  ],
  imports: [CommonModule],
  exports: [
    My000968Component,
  ]
})
export class Module000868 { }
