// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001051Component } from './my.001051.component';

@NgModule({
  declarations: [
    My001051Component,
  ],
  imports: [CommonModule],
  exports: [
    My001051Component,
  ]
})
export class Module000951 { }
