// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000669',
  templateUrl: './my.000669.component.html'
})
export class My000669Component {
  @Input() parentName: string;
  myName = 'My000669Component';
}
