// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000931',
  templateUrl: './my.000931.component.html'
})
export class My000931Component {
  @Input() parentName: string;
  myName = 'My000931Component';
}
