// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000684Component } from './my.000684.component';

@NgModule({
  declarations: [
    My000684Component,
  ],
  imports: [CommonModule],
  exports: [
    My000684Component,
  ]
})
export class Module000484 { }
