// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000684',
  templateUrl: './my.000684.component.html'
})
export class My000684Component {
  @Input() parentName: string;
  myName = 'My000684Component';
}
