// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000671',
  templateUrl: './my.000671.component.html'
})
export class My000671Component {
  @Input() parentName: string;
  myName = 'My000671Component';
}
