// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000278',
  templateUrl: './my.000278.component.html'
})
export class My000278Component {
  @Input() parentName: string;
  myName = 'My000278Component';
}
