// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000539',
  templateUrl: './my.000539.component.html'
})
export class My000539Component {
  @Input() parentName: string;
  myName = 'My000539Component';
}
