// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000262Component } from './my.000262.component';

@NgModule({
  declarations: [
    My000262Component,
  ],
  imports: [CommonModule],
  exports: [
    My000262Component,
  ]
})
export class Module000162 { }
