// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001120Component } from './my.001120.component';

@NgModule({
  declarations: [
    My001120Component,
  ],
  imports: [CommonModule],
  exports: [
    My001120Component,
  ]
})
export class Module000920 { }
