// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001120',
  templateUrl: './my.001120.component.html'
})
export class My001120Component {
  @Input() parentName: string;
  myName = 'My001120Component';
}
