// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000836Component } from './my.000836.component';

@NgModule({
  declarations: [
    My000836Component,
  ],
  imports: [CommonModule],
  exports: [
    My000836Component,
  ]
})
export class Module000636 { }
