// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000430Component } from './my.000430.component';

@NgModule({
  declarations: [
    My000430Component,
  ],
  imports: [CommonModule],
  exports: [
    My000430Component,
  ]
})
export class Module000230 { }
