// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000058Component } from './my.000058.component';
import { My000059Component } from './my.000059.component';

@NgModule({
  declarations: [
    My000058Component,
    My000059Component,
  ],
  imports: [CommonModule],
  exports: [
    My000058Component,
  ]
})
export class Module000029 { }
