// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000049Component } from './my.000049.component';

@NgModule({
  declarations: [
    My000049Component,
  ],
  imports: [CommonModule],
  exports: [
    My000049Component,
  ]
})
export class Module000029 { }
