// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000049',
  templateUrl: './my.000049.component.html'
})
export class My000049Component {
  @Input() parentName: string;
  myName = 'My000049Component';
}
