// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000966',
  templateUrl: './my.000966.component.html'
})
export class My000966Component {
  @Input() parentName: string;
  myName = 'My000966Component';
}
