// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000376Component } from './my.000376.component';
import { My000377Component } from './my.000377.component';

@NgModule({
  declarations: [
    My000376Component,
    My000377Component,
  ],
  imports: [CommonModule],
  exports: [
    My000376Component,
  ]
})
export class Module000188 { }
