// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000288',
  templateUrl: './my.000288.component.html'
})
export class My000288Component {
  @Input() parentName: string;
  myName = 'My000288Component';
}
