// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000995',
  templateUrl: './my.000995.component.html'
})
export class My000995Component {
  @Input() parentName: string;
  myName = 'My000995Component';
}
