// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001095',
  templateUrl: './my.001095.component.html'
})
export class My001095Component {
  @Input() parentName: string;
  myName = 'My001095Component';
}
