// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000495Component } from './my.000495.component';

@NgModule({
  declarations: [
    My000495Component,
  ],
  imports: [CommonModule],
  exports: [
    My000495Component,
  ]
})
export class Module000395 { }
