// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000595Component } from './my.000595.component';

@NgModule({
  declarations: [
    My000595Component,
  ],
  imports: [CommonModule],
  exports: [
    My000595Component,
  ]
})
export class Module000395 { }
