// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000815Component } from './my.000815.component';

@NgModule({
  declarations: [
    My000815Component,
  ],
  imports: [CommonModule],
  exports: [
    My000815Component,
  ]
})
export class Module000615 { }
