// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000815',
  templateUrl: './my.000815.component.html'
})
export class My000815Component {
  @Input() parentName: string;
  myName = 'My000815Component';
}
