// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000715',
  templateUrl: './my.000715.component.html'
})
export class My000715Component {
  @Input() parentName: string;
  myName = 'My000715Component';
}
