// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000950Component } from './my.000950.component';

@NgModule({
  declarations: [
    My000950Component,
  ],
  imports: [CommonModule],
  exports: [
    My000950Component,
  ]
})
export class Module000750 { }
