// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000904Component } from './my.000904.component';

@NgModule({
  declarations: [
    My000904Component,
  ],
  imports: [CommonModule],
  exports: [
    My000904Component,
  ]
})
export class Module000804 { }
