// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000904',
  templateUrl: './my.000904.component.html'
})
export class My000904Component {
  @Input() parentName: string;
  myName = 'My000904Component';
}
