// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000709Component } from './my.000709.component';

@NgModule({
  declarations: [
    My000709Component,
  ],
  imports: [CommonModule],
  exports: [
    My000709Component,
  ]
})
export class Module000609 { }
