// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000809Component } from './my.000809.component';

@NgModule({
  declarations: [
    My000809Component,
  ],
  imports: [CommonModule],
  exports: [
    My000809Component,
  ]
})
export class Module000609 { }
