// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000809',
  templateUrl: './my.000809.component.html'
})
export class My000809Component {
  @Input() parentName: string;
  myName = 'My000809Component';
}
