// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000734Component } from './my.000734.component';

@NgModule({
  declarations: [
    My000734Component,
  ],
  imports: [CommonModule],
  exports: [
    My000734Component,
  ]
})
export class Module000534 { }
