// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000634Component } from './my.000634.component';

@NgModule({
  declarations: [
    My000634Component,
  ],
  imports: [CommonModule],
  exports: [
    My000634Component,
  ]
})
export class Module000534 { }
