// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000734',
  templateUrl: './my.000734.component.html'
})
export class My000734Component {
  @Input() parentName: string;
  myName = 'My000734Component';
}
