// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001153Component } from './my.001153.component';

@NgModule({
  declarations: [
    My001153Component,
  ],
  imports: [CommonModule],
  exports: [
    My001153Component,
  ]
})
export class Module000953 { }
