// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001153',
  templateUrl: './my.001153.component.html'
})
export class My001153Component {
  @Input() parentName: string;
  myName = 'My001153Component';
}
