// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000236',
  templateUrl: './my.000236.component.html'
})
export class My000236Component {
  @Input() parentName: string;
  myName = 'My000236Component';
}
