// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000272',
  templateUrl: './my.000272.component.html'
})
export class My000272Component {
  @Input() parentName: string;
  myName = 'My000272Component';
}
