// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001057Component } from './my.001057.component';

@NgModule({
  declarations: [
    My001057Component,
  ],
  imports: [CommonModule],
  exports: [
    My001057Component,
  ]
})
export class Module000957 { }
