// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000169',
  templateUrl: './my.000169.component.html'
})
export class My000169Component {
  @Input() parentName: string;
  myName = 'My000169Component';
}
