// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000224Component } from './my.000224.component';
import { My000225Component } from './my.000225.component';

@NgModule({
  declarations: [
    My000224Component,
    My000225Component,
  ],
  imports: [CommonModule],
  exports: [
    My000224Component,
  ]
})
export class Module000112 { }
