// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000212Component } from './my.000212.component';

@NgModule({
  declarations: [
    My000212Component,
  ],
  imports: [CommonModule],
  exports: [
    My000212Component,
  ]
})
export class Module000112 { }
