// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000583Component } from './my.000583.component';

@NgModule({
  declarations: [
    My000583Component,
  ],
  imports: [CommonModule],
  exports: [
    My000583Component,
  ]
})
export class Module000383 { }
