// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000687Component } from './my.000687.component';

@NgModule({
  declarations: [
    My000687Component,
  ],
  imports: [CommonModule],
  exports: [
    My000687Component,
  ]
})
export class Module000587 { }
