// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000787',
  templateUrl: './my.000787.component.html'
})
export class My000787Component {
  @Input() parentName: string;
  myName = 'My000787Component';
}
