// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000593',
  templateUrl: './my.000593.component.html'
})
export class My000593Component {
  @Input() parentName: string;
  myName = 'My000593Component';
}
