// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000080',
  templateUrl: './my.000080.component.html'
})
export class My000080Component {
  @Input() parentName: string;
  myName = 'My000080Component';
}
