// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000120',
  templateUrl: './my.000120.component.html'
})
export class My000120Component {
  @Input() parentName: string;
  myName = 'My000120Component';
}
