// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001104Component } from './my.001104.component';

@NgModule({
  declarations: [
    My001104Component,
  ],
  imports: [CommonModule],
  exports: [
    My001104Component,
  ]
})
export class Module000904 { }
