// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000364Component } from './my.000364.component';

@NgModule({
  declarations: [
    My000364Component,
  ],
  imports: [CommonModule],
  exports: [
    My000364Component,
  ]
})
export class Module000264 { }
