// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000464',
  templateUrl: './my.000464.component.html'
})
export class My000464Component {
  @Input() parentName: string;
  myName = 'My000464Component';
}
