// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000571',
  templateUrl: './my.000571.component.html'
})
export class My000571Component {
  @Input() parentName: string;
  myName = 'My000571Component';
}
