// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000280Component } from './my.000280.component';
import { My000281Component } from './my.000281.component';

@NgModule({
  declarations: [
    My000280Component,
    My000281Component,
  ],
  imports: [CommonModule],
  exports: [
    My000280Component,
  ]
})
export class Module000140 { }
