// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000280',
  templateUrl: './my.000280.component.html'
})
export class My000280Component {
  @Input() parentName: string;
  myName = 'My000280Component';
}
