// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000054',
  templateUrl: './my.000054.component.html'
})
export class My000054Component {
  @Input() parentName: string;
  myName = 'My000054Component';
}
