// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000068',
  templateUrl: './my.000068.component.html'
})
export class My000068Component {
  @Input() parentName: string;
  myName = 'My000068Component';
}
