// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000267Component } from './my.000267.component';

@NgModule({
  declarations: [
    My000267Component,
  ],
  imports: [CommonModule],
  exports: [
    My000267Component,
  ]
})
export class Module000167 { }
