// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000366Component } from './my.000366.component';

@NgModule({
  declarations: [
    My000366Component,
  ],
  imports: [CommonModule],
  exports: [
    My000366Component,
  ]
})
export class Module000266 { }
