// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001010Component } from './my.001010.component';

@NgModule({
  declarations: [
    My001010Component,
  ],
  imports: [CommonModule],
  exports: [
    My001010Component,
  ]
})
export class Module000910 { }
