// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001010',
  templateUrl: './my.001010.component.html'
})
export class My001010Component {
  @Input() parentName: string;
  myName = 'My001010Component';
}
