// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000814Component } from './my.000814.component';

@NgModule({
  declarations: [
    My000814Component,
  ],
  imports: [CommonModule],
  exports: [
    My000814Component,
  ]
})
export class Module000614 { }
