// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000714',
  templateUrl: './my.000714.component.html'
})
export class My000714Component {
  @Input() parentName: string;
  myName = 'My000714Component';
}
