// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000496Component } from './my.000496.component';

@NgModule({
  declarations: [
    My000496Component,
  ],
  imports: [CommonModule],
  exports: [
    My000496Component,
  ]
})
export class Module000296 { }
