// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000233Component } from './my.000233.component';

@NgModule({
  declarations: [
    My000233Component,
  ],
  imports: [CommonModule],
  exports: [
    My000233Component,
  ]
})
export class Module000133 { }
