// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000266',
  templateUrl: './my.000266.component.html'
})
export class My000266Component {
  @Input() parentName: string;
  myName = 'My000266Component';
}
