// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000711Component } from './my.000711.component';

@NgModule({
  declarations: [
    My000711Component,
  ],
  imports: [CommonModule],
  exports: [
    My000711Component,
  ]
})
export class Module000511 { }
