// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000711',
  templateUrl: './my.000711.component.html'
})
export class My000711Component {
  @Input() parentName: string;
  myName = 'My000711Component';
}
