// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000116',
  templateUrl: './my.000116.component.html'
})
export class My000116Component {
  @Input() parentName: string;
  myName = 'My000116Component';
}
