// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000192',
  templateUrl: './my.000192.component.html'
})
export class My000192Component {
  @Input() parentName: string;
  myName = 'My000192Component';
}
