// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000086Component } from './my.000086.component';
import { My000087Component } from './my.000087.component';

@NgModule({
  declarations: [
    My000086Component,
    My000087Component,
  ],
  imports: [CommonModule],
  exports: [
    My000086Component,
=======
import { My000063Component } from './my.000063.component';

@NgModule({
  declarations: [
    My000063Component,
  ],
  imports: [CommonModule],
  exports: [
    My000063Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000043 { }
