// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000063',
  templateUrl: './my.000063.component.html'
})
export class My000063Component {
  @Input() parentName: string;
  myName = 'My000063Component';
}
