// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000202Component } from './my.000202.component';
import { My000203Component } from './my.000203.component';

@NgModule({
  declarations: [
    My000202Component,
    My000203Component,
  ],
  imports: [CommonModule],
  exports: [
    My000202Component,
  ]
})
export class Module000101 { }
