// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000201',
  templateUrl: './my.000201.component.html'
})
export class My000201Component {
  @Input() parentName: string;
  myName = 'My000201Component';
}
