// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000923',
  templateUrl: './my.000923.component.html'
})
export class My000923Component {
  @Input() parentName: string;
  myName = 'My000923Component';
}
