// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000115Component } from './my.000115.component';

@NgModule({
  declarations: [
    My000115Component,
  ],
  imports: [CommonModule],
  exports: [
    My000115Component,
  ]
})
export class Module000095 { }
