// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000190',
  templateUrl: './my.000190.component.html'
})
export class My000190Component {
  @Input() parentName: string;
  myName = 'My000190Component';
}
