// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000695Component } from './my.000695.component';

@NgModule({
  declarations: [
    My000695Component,
  ],
  imports: [CommonModule],
  exports: [
    My000695Component,
  ]
})
export class Module000595 { }
