// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000098Component } from './my.000098.component';
import { My000099Component } from './my.000099.component';

@NgModule({
  declarations: [
    My000098Component,
    My000099Component,
  ],
  imports: [CommonModule],
  exports: [
    My000098Component,
  ]
})
export class Module000049 { }
