// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000099',
  templateUrl: './my.000099.component.html'
})
export class My000099Component {
  @Input() parentName: string;
  myName = 'My000099Component';
}
