// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001000',
  templateUrl: './my.001000.component.html'
})
export class My001000Component {
  @Input() parentName: string;
  myName = 'My001000Component';
}
