// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000909Component } from './my.000909.component';

@NgModule({
  declarations: [
    My000909Component,
  ],
  imports: [CommonModule],
  exports: [
    My000909Component,
  ]
})
export class Module000709 { }
