// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000909',
  templateUrl: './my.000909.component.html'
})
export class My000909Component {
  @Input() parentName: string;
  myName = 'My000909Component';
}
