// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000830Component } from './my.000830.component';

@NgModule({
  declarations: [
    My000830Component,
  ],
  imports: [CommonModule],
  exports: [
    My000830Component,
  ]
})
export class Module000630 { }
