// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000915',
  templateUrl: './my.000915.component.html'
})
export class My000915Component {
  @Input() parentName: string;
  myName = 'My000915Component';
}
