// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000801Component } from './my.000801.component';

@NgModule({
  declarations: [
    My000801Component,
  ],
  imports: [CommonModule],
  exports: [
    My000801Component,
  ]
})
export class Module000701 { }
