// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000801',
  templateUrl: './my.000801.component.html'
})
export class My000801Component {
  @Input() parentName: string;
  myName = 'My000801Component';
}
