// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000221Component } from './my.000221.component';

@NgModule({
  declarations: [
    My000221Component,
  ],
  imports: [CommonModule],
  exports: [
    My000221Component,
  ]
})
export class Module000121 { }
