// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001016Component } from './my.001016.component';

@NgModule({
  declarations: [
    My001016Component,
  ],
  imports: [CommonModule],
  exports: [
    My001016Component,
  ]
})
export class Module000816 { }
