// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000916Component } from './my.000916.component';

@NgModule({
  declarations: [
    My000916Component,
  ],
  imports: [CommonModule],
  exports: [
    My000916Component,
  ]
})
export class Module000816 { }
