// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001056Component } from './my.001056.component';

@NgModule({
  declarations: [
    My001056Component,
  ],
  imports: [CommonModule],
  exports: [
    My001056Component,
  ]
})
export class Module000856 { }
