// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001056',
  templateUrl: './my.001056.component.html'
})
export class My001056Component {
  @Input() parentName: string;
  myName = 'My001056Component';
}
