// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000352Component } from './my.000352.component';

@NgModule({
  declarations: [
    My000352Component,
  ],
  imports: [CommonModule],
  exports: [
    My000352Component,
  ]
})
export class Module000252 { }
