// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000320Component } from './my.000320.component';

@NgModule({
  declarations: [
    My000320Component,
  ],
  imports: [CommonModule],
  exports: [
    My000320Component,
  ]
})
export class Module000220 { }
