// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001053',
  templateUrl: './my.001053.component.html'
})
export class My001053Component {
  @Input() parentName: string;
  myName = 'My001053Component';
}
