// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001141',
  templateUrl: './my.001141.component.html'
})
export class My001141Component {
  @Input() parentName: string;
  myName = 'My001141Component';
}
