// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001174Component } from './my.001174.component';

@NgModule({
  declarations: [
    My001174Component,
  ],
  imports: [CommonModule],
  exports: [
    My001174Component,
  ]
})
export class Module000974 { }
