// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001174',
  templateUrl: './my.001174.component.html'
})
export class My001174Component {
  @Input() parentName: string;
  myName = 'My001174Component';
}
