// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000581Component } from './my.000581.component';

@NgModule({
  declarations: [
    My000581Component,
  ],
  imports: [CommonModule],
  exports: [
    My000581Component,
  ]
})
export class Module000481 { }
