// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000681Component } from './my.000681.component';

@NgModule({
  declarations: [
    My000681Component,
  ],
  imports: [CommonModule],
  exports: [
    My000681Component,
  ]
})
export class Module000481 { }
