// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000840Component } from './my.000840.component';

@NgModule({
  declarations: [
    My000840Component,
  ],
  imports: [CommonModule],
  exports: [
    My000840Component,
  ]
})
export class Module000640 { }
