// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000599Component } from './my.000599.component';

@NgModule({
  declarations: [
    My000599Component,
  ],
  imports: [CommonModule],
  exports: [
    My000599Component,
  ]
})
export class Module000499 { }
