// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000545Component } from './my.000545.component';

@NgModule({
  declarations: [
    My000545Component,
  ],
  imports: [CommonModule],
  exports: [
    My000545Component,
  ]
})
export class Module000345 { }
