// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000666Component } from './my.000666.component';

@NgModule({
  declarations: [
    My000666Component,
  ],
  imports: [CommonModule],
  exports: [
    My000666Component,
  ]
})
export class Module000566 { }
