// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000990Component } from './my.000990.component';

@NgModule({
  declarations: [
    My000990Component,
  ],
  imports: [CommonModule],
  exports: [
    My000990Component,
  ]
})
export class Module000890 { }
