// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001188Component } from './my.001188.component';

@NgModule({
  declarations: [
    My001188Component,
  ],
  imports: [CommonModule],
  exports: [
    My001188Component,
  ]
})
export class Module000988 { }
