// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001088',
  templateUrl: './my.001088.component.html'
})
export class My001088Component {
  @Input() parentName: string;
  myName = 'My001088Component';
}
