// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000071Component } from './my.000071.component';

@NgModule({
  declarations: [
    My000071Component,
  ],
  imports: [CommonModule],
  exports: [
    My000071Component,
  ]
})
export class Module000051 { }
