// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000102Component } from './my.000102.component';
import { My000103Component } from './my.000103.component';

@NgModule({
  declarations: [
    My000102Component,
    My000103Component,
  ],
  imports: [CommonModule],
  exports: [
    My000102Component,
=======
import { My000071Component } from './my.000071.component';

@NgModule({
  declarations: [
    My000071Component,
  ],
  imports: [CommonModule],
  exports: [
    My000071Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000051 { }
