// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000103',
  templateUrl: './my.000103.component.html'
})
export class My000103Component {
  @Input() parentName: string;
  myName = 'My000103Component';
}
