// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000373',
  templateUrl: './my.000373.component.html'
})
export class My000373Component {
  @Input() parentName: string;
  myName = 'My000373Component';
}
