// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000391',
  templateUrl: './my.000391.component.html'
})
export class My000391Component {
  @Input() parentName: string;
  myName = 'My000391Component';
}
