// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000081Component } from './my.000081.component';

@NgModule({
  declarations: [
    My000081Component,
  ],
  imports: [CommonModule],
  exports: [
    My000081Component,
  ]
})
export class Module000061 { }
