// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000122Component } from './my.000122.component';
import { My000123Component } from './my.000123.component';

@NgModule({
  declarations: [
    My000122Component,
    My000123Component,
  ],
  imports: [CommonModule],
  exports: [
    My000122Component,
  ]
})
export class Module000061 { }
