// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000122Component } from './my.000122.component';
import { My000123Component } from './my.000123.component';

@NgModule({
  declarations: [
    My000122Component,
    My000123Component,
  ],
  imports: [CommonModule],
  exports: [
    My000122Component,
=======
import { My000081Component } from './my.000081.component';

@NgModule({
  declarations: [
    My000081Component,
  ],
  imports: [CommonModule],
  exports: [
    My000081Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000061 { }
