// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000123',
  templateUrl: './my.000123.component.html'
})
export class My000123Component {
  @Input() parentName: string;
  myName = 'My000123Component';
}
