// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001027Component } from './my.001027.component';

@NgModule({
  declarations: [
    My001027Component,
  ],
  imports: [CommonModule],
  exports: [
    My001027Component,
  ]
})
export class Module000927 { }
