// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001127Component } from './my.001127.component';

@NgModule({
  declarations: [
    My001127Component,
  ],
  imports: [CommonModule],
  exports: [
    My001127Component,
  ]
})
export class Module000927 { }
