// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001027',
  templateUrl: './my.001027.component.html'
})
export class My001027Component {
  @Input() parentName: string;
  myName = 'My001027Component';
}
