// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000064Component } from './my.000064.component';

@NgModule({
  declarations: [
    My000064Component,
  ],
  imports: [CommonModule],
  exports: [
    My000064Component,
  ]
})
export class Module000044 { }
