// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000393',
  templateUrl: './my.000393.component.html'
})
export class My000393Component {
  @Input() parentName: string;
  myName = 'My000393Component';
}
