// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000308Component } from './my.000308.component';

@NgModule({
  declarations: [
    My000308Component,
  ],
  imports: [CommonModule],
  exports: [
    My000308Component,
  ]
})
export class Module000208 { }
