// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000996Component } from './my.000996.component';

@NgModule({
  declarations: [
    My000996Component,
  ],
  imports: [CommonModule],
  exports: [
    My000996Component,
  ]
})
export class Module000796 { }
