// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000579Component } from './my.000579.component';

@NgModule({
  declarations: [
    My000579Component,
  ],
  imports: [CommonModule],
  exports: [
    My000579Component,
  ]
})
export class Module000479 { }
