// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000679Component } from './my.000679.component';

@NgModule({
  declarations: [
    My000679Component,
  ],
  imports: [CommonModule],
  exports: [
    My000679Component,
  ]
})
export class Module000479 { }
