// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000579',
  templateUrl: './my.000579.component.html'
})
export class My000579Component {
  @Input() parentName: string;
  myName = 'My000579Component';
}
