// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000016',
  templateUrl: './my.000016.component.html'
})
export class My000016Component {
  @Input() parentName: string;
  myName = 'My000016Component';
}
