// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000017',
  templateUrl: './my.000017.component.html'
})
export class My000017Component {
  @Input() parentName: string;
  myName = 'My000017Component';
}
