// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000621Component } from './my.000621.component';

@NgModule({
  declarations: [
    My000621Component,
  ],
  imports: [CommonModule],
  exports: [
    My000621Component,
  ]
})
export class Module000521 { }
