// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000721',
  templateUrl: './my.000721.component.html'
})
export class My000721Component {
  @Input() parentName: string;
  myName = 'My000721Component';
}
