// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000621',
  templateUrl: './my.000621.component.html'
})
export class My000621Component {
  @Input() parentName: string;
  myName = 'My000621Component';
}
