// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000853Component } from './my.000853.component';

@NgModule({
  declarations: [
    My000853Component,
  ],
  imports: [CommonModule],
  exports: [
    My000853Component,
  ]
})
export class Module000653 { }
