// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000753',
  templateUrl: './my.000753.component.html'
})
export class My000753Component {
  @Input() parentName: string;
  myName = 'My000753Component';
}
