// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000853',
  templateUrl: './my.000853.component.html'
})
export class My000853Component {
  @Input() parentName: string;
  myName = 'My000853Component';
}
