// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000797Component } from './my.000797.component';

@NgModule({
  declarations: [
    My000797Component,
  ],
  imports: [CommonModule],
  exports: [
    My000797Component,
  ]
})
export class Module000697 { }
