// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000906',
  templateUrl: './my.000906.component.html'
})
export class My000906Component {
  @Input() parentName: string;
  myName = 'My000906Component';
}
