// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000673Component } from './my.000673.component';

@NgModule({
  declarations: [
    My000673Component,
  ],
  imports: [CommonModule],
  exports: [
    My000673Component,
  ]
})
export class Module000473 { }
