// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000048Component } from './my.000048.component';
import { My000049Component } from './my.000049.component';

@NgModule({
  declarations: [
    My000048Component,
    My000049Component,
  ],
  imports: [CommonModule],
  exports: [
    My000048Component,
  ]
})
export class Module000024 { }
