// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000440Component } from './my.000440.component';

@NgModule({
  declarations: [
    My000440Component,
  ],
  imports: [CommonModule],
  exports: [
    My000440Component,
  ]
})
export class Module000340 { }
