// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000540',
  templateUrl: './my.000540.component.html'
})
export class My000540Component {
  @Input() parentName: string;
  myName = 'My000540Component';
}
