// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000433Component } from './my.000433.component';

@NgModule({
  declarations: [
    My000433Component,
  ],
  imports: [CommonModule],
  exports: [
    My000433Component,
  ]
})
export class Module000233 { }
