// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000333Component } from './my.000333.component';

@NgModule({
  declarations: [
    My000333Component,
  ],
  imports: [CommonModule],
  exports: [
    My000333Component,
  ]
})
export class Module000233 { }
