// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000433',
  templateUrl: './my.000433.component.html'
})
export class My000433Component {
  @Input() parentName: string;
  myName = 'My000433Component';
}
