// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001177Component } from './my.001177.component';

@NgModule({
  declarations: [
    My001177Component,
  ],
  imports: [CommonModule],
  exports: [
    My001177Component,
  ]
})
export class Module000977 { }
