// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000786Component } from './my.000786.component';

@NgModule({
  declarations: [
    My000786Component,
  ],
  imports: [CommonModule],
  exports: [
    My000786Component,
  ]
})
export class Module000586 { }
