// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000786',
  templateUrl: './my.000786.component.html'
})
export class My000786Component {
  @Input() parentName: string;
  myName = 'My000786Component';
}
