// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000519',
  templateUrl: './my.000519.component.html'
})
export class My000519Component {
  @Input() parentName: string;
  myName = 'My000519Component';
}
