// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000975Component } from './my.000975.component';

@NgModule({
  declarations: [
    My000975Component,
  ],
  imports: [CommonModule],
  exports: [
    My000975Component,
  ]
})
export class Module000875 { }
