// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001075',
  templateUrl: './my.001075.component.html'
})
export class My001075Component {
  @Input() parentName: string;
  myName = 'My001075Component';
}
