// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000268',
  templateUrl: './my.000268.component.html'
})
export class My000268Component {
  @Input() parentName: string;
  myName = 'My000268Component';
}
