// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000234',
  templateUrl: './my.000234.component.html'
})
export class My000234Component {
  @Input() parentName: string;
  myName = 'My000234Component';
}
