// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000907Component } from './my.000907.component';

@NgModule({
  declarations: [
    My000907Component,
  ],
  imports: [CommonModule],
  exports: [
    My000907Component,
  ]
})
export class Module000707 { }
