// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000807',
  templateUrl: './my.000807.component.html'
})
export class My000807Component {
  @Input() parentName: string;
  myName = 'My000807Component';
}
