// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000348',
  templateUrl: './my.000348.component.html'
})
export class My000348Component {
  @Input() parentName: string;
  myName = 'My000348Component';
}
