// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000274',
  templateUrl: './my.000274.component.html'
})
export class My000274Component {
  @Input() parentName: string;
  myName = 'My000274Component';
}
