// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000349',
  templateUrl: './my.000349.component.html'
})
export class My000349Component {
  @Input() parentName: string;
  myName = 'My000349Component';
}
