// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000960Component } from './my.000960.component';

@NgModule({
  declarations: [
    My000960Component,
  ],
  imports: [CommonModule],
  exports: [
    My000960Component,
  ]
})
export class Module000860 { }
