// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000960',
  templateUrl: './my.000960.component.html'
})
export class My000960Component {
  @Input() parentName: string;
  myName = 'My000960Component';
}
