// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000653Component } from './my.000653.component';

@NgModule({
  declarations: [
    My000653Component,
  ],
  imports: [CommonModule],
  exports: [
    My000653Component,
  ]
})
export class Module000553 { }
