// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000653',
  templateUrl: './my.000653.component.html'
})
export class My000653Component {
  @Input() parentName: string;
  myName = 'My000653Component';
}
