// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000284Component } from './my.000284.component';
import { My000285Component } from './my.000285.component';

@NgModule({
  declarations: [
    My000284Component,
    My000285Component,
  ],
  imports: [CommonModule],
  exports: [
    My000284Component,
  ]
})
export class Module000142 { }
