// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000242Component } from './my.000242.component';

@NgModule({
  declarations: [
    My000242Component,
  ],
  imports: [CommonModule],
  exports: [
    My000242Component,
  ]
})
export class Module000142 { }
