// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001084',
  templateUrl: './my.001084.component.html'
})
export class My001084Component {
  @Input() parentName: string;
  myName = 'My001084Component';
}
