// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001184Component } from './my.001184.component';

@NgModule({
  declarations: [
    My001184Component,
  ],
  imports: [CommonModule],
  exports: [
    My001184Component,
  ]
})
export class Module000984 { }
