// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001184',
  templateUrl: './my.001184.component.html'
})
export class My001184Component {
  @Input() parentName: string;
  myName = 'My001184Component';
}
