// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000533',
  templateUrl: './my.000533.component.html'
})
export class My000533Component {
  @Input() parentName: string;
  myName = 'My000533Component';
}
