// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000773',
  templateUrl: './my.000773.component.html'
})
export class My000773Component {
  @Input() parentName: string;
  myName = 'My000773Component';
}
