// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000673',
  templateUrl: './my.000673.component.html'
})
export class My000673Component {
  @Input() parentName: string;
  myName = 'My000673Component';
}
