// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000349Component } from './my.000349.component';

@NgModule({
  declarations: [
    My000349Component,
  ],
  imports: [CommonModule],
  exports: [
    My000349Component,
  ]
})
export class Module000249 { }
