// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000449',
  templateUrl: './my.000449.component.html'
})
export class My000449Component {
  @Input() parentName: string;
  myName = 'My000449Component';
}
