// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000836',
  templateUrl: './my.000836.component.html'
})
export class My000836Component {
  @Input() parentName: string;
  myName = 'My000836Component';
}
