// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000910',
  templateUrl: './my.000910.component.html'
})
export class My000910Component {
  @Input() parentName: string;
  myName = 'My000910Component';
}
