// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000918Component } from './my.000918.component';

@NgModule({
  declarations: [
    My000918Component,
  ],
  imports: [CommonModule],
  exports: [
    My000918Component,
  ]
})
export class Module000718 { }
