// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000818',
  templateUrl: './my.000818.component.html'
})
export class My000818Component {
  @Input() parentName: string;
  myName = 'My000818Component';
}
