// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001054Component } from './my.001054.component';

@NgModule({
  declarations: [
    My001054Component,
  ],
  imports: [CommonModule],
  exports: [
    My001054Component,
  ]
})
export class Module000954 { }
