// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001154Component } from './my.001154.component';

@NgModule({
  declarations: [
    My001154Component,
  ],
  imports: [CommonModule],
  exports: [
    My001154Component,
  ]
})
export class Module000954 { }
