// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001154',
  templateUrl: './my.001154.component.html'
})
export class My001154Component {
  @Input() parentName: string;
  myName = 'My001154Component';
}
