// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000297Component } from './my.000297.component';

@NgModule({
  declarations: [
    My000297Component,
  ],
  imports: [CommonModule],
  exports: [
    My000297Component,
  ]
})
export class Module000197 { }
