// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000394Component } from './my.000394.component';
import { My000395Component } from './my.000395.component';

@NgModule({
  declarations: [
    My000394Component,
    My000395Component,
  ],
  imports: [CommonModule],
  exports: [
    My000394Component,
  ]
})
export class Module000197 { }
