// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000838Component } from './my.000838.component';

@NgModule({
  declarations: [
    My000838Component,
  ],
  imports: [CommonModule],
  exports: [
    My000838Component,
  ]
})
export class Module000738 { }
