// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000720Component } from './my.000720.component';

@NgModule({
  declarations: [
    My000720Component,
  ],
  imports: [CommonModule],
  exports: [
    My000720Component,
  ]
})
export class Module000520 { }
