// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000626Component } from './my.000626.component';

@NgModule({
  declarations: [
    My000626Component,
  ],
  imports: [CommonModule],
  exports: [
    My000626Component,
  ]
})
export class Module000426 { }
