// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000526',
  templateUrl: './my.000526.component.html'
})
export class My000526Component {
  @Input() parentName: string;
  myName = 'My000526Component';
}
