// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000105Component } from './my.000105.component';

@NgModule({
  declarations: [
    My000105Component,
  ],
  imports: [CommonModule],
  exports: [
    My000105Component,
  ]
})
export class Module000085 { }
