// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000170',
  templateUrl: './my.000170.component.html'
})
export class My000170Component {
  @Input() parentName: string;
  myName = 'My000170Component';
}
