// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000917Component } from './my.000917.component';

@NgModule({
  declarations: [
    My000917Component,
  ],
  imports: [CommonModule],
  exports: [
    My000917Component,
  ]
})
export class Module000717 { }
