// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000917',
  templateUrl: './my.000917.component.html'
})
export class My000917Component {
  @Input() parentName: string;
  myName = 'My000917Component';
}
