// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000210Component } from './my.000210.component';
import { My000211Component } from './my.000211.component';

@NgModule({
  declarations: [
    My000210Component,
    My000211Component,
  ],
  imports: [CommonModule],
  exports: [
    My000210Component,
  ]
})
export class Module000105 { }
