// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000210',
  templateUrl: './my.000210.component.html'
})
export class My000210Component {
  @Input() parentName: string;
  myName = 'My000210Component';
}
