// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000630',
  templateUrl: './my.000630.component.html'
})
export class My000630Component {
  @Input() parentName: string;
  myName = 'My000630Component';
}
