// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000367Component } from './my.000367.component';

@NgModule({
  declarations: [
    My000367Component,
  ],
  imports: [CommonModule],
  exports: [
    My000367Component,
  ]
})
export class Module000267 { }
