// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000367',
  templateUrl: './my.000367.component.html'
})
export class My000367Component {
  @Input() parentName: string;
  myName = 'My000367Component';
}
