// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000671Component } from './my.000671.component';

@NgModule({
  declarations: [
    My000671Component,
  ],
  imports: [CommonModule],
  exports: [
    My000671Component,
  ]
})
export class Module000571 { }
