// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000771Component } from './my.000771.component';

@NgModule({
  declarations: [
    My000771Component,
  ],
  imports: [CommonModule],
  exports: [
    My000771Component,
  ]
})
export class Module000571 { }
