// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000541',
  templateUrl: './my.000541.component.html'
})
export class My000541Component {
  @Input() parentName: string;
  myName = 'My000541Component';
}
