// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000448Component } from './my.000448.component';

@NgModule({
  declarations: [
    My000448Component,
  ],
  imports: [CommonModule],
  exports: [
    My000448Component,
  ]
})
export class Module000348 { }
