// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000993Component } from './my.000993.component';

@NgModule({
  declarations: [
    My000993Component,
  ],
  imports: [CommonModule],
  exports: [
    My000993Component,
  ]
})
export class Module000793 { }
