// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000893Component } from './my.000893.component';

@NgModule({
  declarations: [
    My000893Component,
  ],
  imports: [CommonModule],
  exports: [
    My000893Component,
  ]
})
export class Module000793 { }
