// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000355Component } from './my.000355.component';

@NgModule({
  declarations: [
    My000355Component,
  ],
  imports: [CommonModule],
  exports: [
    My000355Component,
  ]
})
export class Module000255 { }
