// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000601Component } from './my.000601.component';

@NgModule({
  declarations: [
    My000601Component,
  ],
  imports: [CommonModule],
  exports: [
    My000601Component,
  ]
})
export class Module000401 { }
