// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000423Component } from './my.000423.component';

@NgModule({
  declarations: [
    My000423Component,
  ],
  imports: [CommonModule],
  exports: [
    My000423Component,
  ]
})
export class Module000223 { }
