// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000454Component } from './my.000454.component';

@NgModule({
  declarations: [
    My000454Component,
  ],
  imports: [CommonModule],
  exports: [
    My000454Component,
  ]
})
export class Module000354 { }
