// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000554Component } from './my.000554.component';

@NgModule({
  declarations: [
    My000554Component,
  ],
  imports: [CommonModule],
  exports: [
    My000554Component,
  ]
})
export class Module000354 { }
