// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000554',
  templateUrl: './my.000554.component.html'
})
export class My000554Component {
  @Input() parentName: string;
  myName = 'My000554Component';
}
