// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000454',
  templateUrl: './my.000454.component.html'
})
export class My000454Component {
  @Input() parentName: string;
  myName = 'My000454Component';
}
