// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000334Component } from './my.000334.component';

@NgModule({
  declarations: [
    My000334Component,
  ],
  imports: [CommonModule],
  exports: [
    My000334Component,
  ]
})
export class Module000234 { }
