// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000032Component } from './my.000032.component';
import { My000033Component } from './my.000033.component';

@NgModule({
  declarations: [
    My000032Component,
    My000033Component,
  ],
  imports: [CommonModule],
  exports: [
    My000032Component,
  ]
})
export class Module000016 { }
