// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000613',
  templateUrl: './my.000613.component.html'
})
export class My000613Component {
  @Input() parentName: string;
  myName = 'My000613Component';
}
