// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000936Component } from './my.000936.component';

@NgModule({
  declarations: [
    My000936Component,
  ],
  imports: [CommonModule],
  exports: [
    My000936Component,
  ]
})
export class Module000836 { }
