// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001036',
  templateUrl: './my.001036.component.html'
})
export class My001036Component {
  @Input() parentName: string;
  myName = 'My001036Component';
}
