// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000538Component } from './my.000538.component';

@NgModule({
  declarations: [
    My000538Component,
  ],
  imports: [CommonModule],
  exports: [
    My000538Component,
  ]
})
export class Module000338 { }
