// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000438Component } from './my.000438.component';

@NgModule({
  declarations: [
    My000438Component,
  ],
  imports: [CommonModule],
  exports: [
    My000438Component,
  ]
})
export class Module000338 { }
