// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000828',
  templateUrl: './my.000828.component.html'
})
export class My000828Component {
  @Input() parentName: string;
  myName = 'My000828Component';
}
