// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000322Component } from './my.000322.component';

@NgModule({
  declarations: [
    My000322Component,
  ],
  imports: [CommonModule],
  exports: [
    My000322Component,
  ]
})
export class Module000222 { }
