// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000422',
  templateUrl: './my.000422.component.html'
})
export class My000422Component {
  @Input() parentName: string;
  myName = 'My000422Component';
}
