// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000958Component } from './my.000958.component';

@NgModule({
  declarations: [
    My000958Component,
  ],
  imports: [CommonModule],
  exports: [
    My000958Component,
  ]
})
export class Module000758 { }
