// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000858',
  templateUrl: './my.000858.component.html'
})
export class My000858Component {
  @Input() parentName: string;
  myName = 'My000858Component';
}
