// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000617Component } from './my.000617.component';

@NgModule({
  declarations: [
    My000617Component,
  ],
  imports: [CommonModule],
  exports: [
    My000617Component,
  ]
})
export class Module000417 { }
