// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000517',
  templateUrl: './my.000517.component.html'
})
export class My000517Component {
  @Input() parentName: string;
  myName = 'My000517Component';
}
