// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000516Component } from './my.000516.component';

@NgModule({
  declarations: [
    My000516Component,
  ],
  imports: [CommonModule],
  exports: [
    My000516Component,
  ]
})
export class Module000316 { }
