// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000416Component } from './my.000416.component';

@NgModule({
  declarations: [
    My000416Component,
  ],
  imports: [CommonModule],
  exports: [
    My000416Component,
  ]
})
export class Module000316 { }
