// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001038Component } from './my.001038.component';

@NgModule({
  declarations: [
    My001038Component,
  ],
  imports: [CommonModule],
  exports: [
    My001038Component,
  ]
})
export class Module000938 { }
