// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001138Component } from './my.001138.component';

@NgModule({
  declarations: [
    My001138Component,
  ],
  imports: [CommonModule],
  exports: [
    My001138Component,
  ]
})
export class Module000938 { }
