// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000444Component } from './my.000444.component';

@NgModule({
  declarations: [
    My000444Component,
  ],
  imports: [CommonModule],
  exports: [
    My000444Component,
  ]
})
export class Module000344 { }
