// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000108Component } from './my.000108.component';
import { My000109Component } from './my.000109.component';

@NgModule({
  declarations: [
    My000108Component,
    My000109Component,
  ],
  imports: [CommonModule],
  exports: [
    My000108Component,
  ]
})
export class Module000054 { }
