// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000302',
  templateUrl: './my.000302.component.html'
})
export class My000302Component {
  @Input() parentName: string;
  myName = 'My000302Component';
}
