// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001165Component } from './my.001165.component';

@NgModule({
  declarations: [
    My001165Component,
  ],
  imports: [CommonModule],
  exports: [
    My001165Component,
  ]
})
export class Module000965 { }
