// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001065',
  templateUrl: './my.001065.component.html'
})
export class My001065Component {
  @Input() parentName: string;
  myName = 'My001065Component';
}
