// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000704Component } from './my.000704.component';

@NgModule({
  declarations: [
    My000704Component,
  ],
  imports: [CommonModule],
  exports: [
    My000704Component,
  ]
})
export class Module000604 { }
