// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000804',
  templateUrl: './my.000804.component.html'
})
export class My000804Component {
  @Input() parentName: string;
  myName = 'My000804Component';
}
