// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000376Component } from './my.000376.component';

@NgModule({
  declarations: [
    My000376Component,
  ],
  imports: [CommonModule],
  exports: [
    My000376Component,
  ]
})
export class Module000276 { }
