// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000060Component } from './my.000060.component';
import { My000061Component } from './my.000061.component';

@NgModule({
  declarations: [
    My000060Component,
    My000061Component,
  ],
  imports: [CommonModule],
  exports: [
    My000060Component,
=======
import { My000050Component } from './my.000050.component';

@NgModule({
  declarations: [
    My000050Component,
  ],
  imports: [CommonModule],
  exports: [
    My000050Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000030 { }
