// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000370Component } from './my.000370.component';
import { My000371Component } from './my.000371.component';

@NgModule({
  declarations: [
    My000370Component,
    My000371Component,
  ],
  imports: [CommonModule],
  exports: [
    My000370Component,
  ]
})
export class Module000185 { }
