// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000370',
  templateUrl: './my.000370.component.html'
})
export class My000370Component {
  @Input() parentName: string;
  myName = 'My000370Component';
}
