// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001105Component } from './my.001105.component';

@NgModule({
  declarations: [
    My001105Component,
  ],
  imports: [CommonModule],
  exports: [
    My001105Component,
  ]
})
export class Module000905 { }
