// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001005',
  templateUrl: './my.001005.component.html'
})
export class My001005Component {
  @Input() parentName: string;
  myName = 'My001005Component';
}
