// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000218Component } from './my.000218.component';

@NgModule({
  declarations: [
    My000218Component,
  ],
  imports: [CommonModule],
  exports: [
    My000218Component,
  ]
})
export class Module000118 { }
