// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000218',
  templateUrl: './my.000218.component.html'
})
export class My000218Component {
  @Input() parentName: string;
  myName = 'My000218Component';
}
