// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000237',
  templateUrl: './my.000237.component.html'
})
export class My000237Component {
  @Input() parentName: string;
  myName = 'My000237Component';
}
