// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000315',
  templateUrl: './my.000315.component.html'
})
export class My000315Component {
  @Input() parentName: string;
  myName = 'My000315Component';
}
