// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001002Component } from './my.001002.component';

@NgModule({
  declarations: [
    My001002Component,
  ],
  imports: [CommonModule],
  exports: [
    My001002Component,
  ]
})
export class Module000902 { }
