// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001002',
  templateUrl: './my.001002.component.html'
})
export class My001002Component {
  @Input() parentName: string;
  myName = 'My001002Component';
}
