// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001044',
  templateUrl: './my.001044.component.html'
})
export class My001044Component {
  @Input() parentName: string;
  myName = 'My001044Component';
}
