// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001144',
  templateUrl: './my.001144.component.html'
})
export class My001144Component {
  @Input() parentName: string;
  myName = 'My001144Component';
}
