// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000659',
  templateUrl: './my.000659.component.html'
})
export class My000659Component {
  @Input() parentName: string;
  myName = 'My000659Component';
}
