// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000066Component } from './my.000066.component';

@NgModule({
  declarations: [
    My000066Component,
  ],
  imports: [CommonModule],
  exports: [
    My000066Component,
  ]
})
export class Module000046 { }
