// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000868Component } from './my.000868.component';

@NgModule({
  declarations: [
    My000868Component,
  ],
  imports: [CommonModule],
  exports: [
    My000868Component,
  ]
})
export class Module000668 { }
