// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000768',
  templateUrl: './my.000768.component.html'
})
export class My000768Component {
  @Input() parentName: string;
  myName = 'My000768Component';
}
