// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000868',
  templateUrl: './my.000868.component.html'
})
export class My000868Component {
  @Input() parentName: string;
  myName = 'My000868Component';
}
