// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000735Component } from './my.000735.component';

@NgModule({
  declarations: [
    My000735Component,
  ],
  imports: [CommonModule],
  exports: [
    My000735Component,
  ]
})
export class Module000535 { }
