// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000336Component } from './my.000336.component';
import { My000337Component } from './my.000337.component';

@NgModule({
  declarations: [
    My000336Component,
    My000337Component,
  ],
  imports: [CommonModule],
  exports: [
    My000336Component,
  ]
})
export class Module000168 { }
