// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000581',
  templateUrl: './my.000581.component.html'
})
export class My000581Component {
  @Input() parentName: string;
  myName = 'My000581Component';
}
