// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001034Component } from './my.001034.component';

@NgModule({
  declarations: [
    My001034Component,
  ],
  imports: [CommonModule],
  exports: [
    My001034Component,
  ]
})
export class Module000934 { }
