// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001134',
  templateUrl: './my.001134.component.html'
})
export class My001134Component {
  @Input() parentName: string;
  myName = 'My001134Component';
}
