// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000800Component } from './my.000800.component';

@NgModule({
  declarations: [
    My000800Component,
  ],
  imports: [CommonModule],
  exports: [
    My000800Component,
  ]
})
export class Module000600 { }
