// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000241Component } from './my.000241.component';

@NgModule({
  declarations: [
    My000241Component,
  ],
  imports: [CommonModule],
  exports: [
    My000241Component,
  ]
})
export class Module000141 { }
