// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000282Component } from './my.000282.component';
import { My000283Component } from './my.000283.component';

@NgModule({
  declarations: [
    My000282Component,
    My000283Component,
  ],
  imports: [CommonModule],
  exports: [
    My000282Component,
  ]
})
export class Module000141 { }
