// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000241',
  templateUrl: './my.000241.component.html'
})
export class My000241Component {
  @Input() parentName: string;
  myName = 'My000241Component';
}
