// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000283',
  templateUrl: './my.000283.component.html'
})
export class My000283Component {
  @Input() parentName: string;
  myName = 'My000283Component';
}
