// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000300Component } from './my.000300.component';

@NgModule({
  declarations: [
    My000300Component,
  ],
  imports: [CommonModule],
  exports: [
    My000300Component,
  ]
})
export class Module000200 { }
