// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000528Component } from './my.000528.component';

@NgModule({
  declarations: [
    My000528Component,
  ],
  imports: [CommonModule],
  exports: [
    My000528Component,
  ]
})
export class Module000428 { }
