// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000528',
  templateUrl: './my.000528.component.html'
})
export class My000528Component {
  @Input() parentName: string;
  myName = 'My000528Component';
}
