// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000357Component } from './my.000357.component';

@NgModule({
  declarations: [
    My000357Component,
  ],
  imports: [CommonModule],
  exports: [
    My000357Component,
  ]
})
export class Module000257 { }
