// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000701',
  templateUrl: './my.000701.component.html'
})
export class My000701Component {
  @Input() parentName: string;
  myName = 'My000701Component';
}
