// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000591',
  templateUrl: './my.000591.component.html'
})
export class My000591Component {
  @Input() parentName: string;
  myName = 'My000591Component';
}
