// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000908',
  templateUrl: './my.000908.component.html'
})
export class My000908Component {
  @Input() parentName: string;
  myName = 'My000908Component';
}
