// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000986',
  templateUrl: './my.000986.component.html'
})
export class My000986Component {
  @Input() parentName: string;
  myName = 'My000986Component';
}
