// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000343Component } from './my.000343.component';

@NgModule({
  declarations: [
    My000343Component,
  ],
  imports: [CommonModule],
  exports: [
    My000343Component,
  ]
})
export class Module000243 { }
