// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000443',
  templateUrl: './my.000443.component.html'
})
export class My000443Component {
  @Input() parentName: string;
  myName = 'My000443Component';
}
