// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000001Component } from './my.000001.component';
import { My000003Component } from './my.000003.component';
import { My000004Component } from './my.000004.component';

@NgModule({
  declarations: [
    My000001Component,
    My000003Component,
    My000004Component,
  ],
  imports: [CommonModule],
  exports: [
    My000001Component,
  ]
})
export class Module000001 { }
