// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000001',
  templateUrl: './my.000001.component.html'
})
export class My000001Component {
  @Input() parentName: string;
  myName = 'My000001Component';
}
