// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000381Component } from './my.000381.component';

@NgModule({
  declarations: [
    My000381Component,
  ],
  imports: [CommonModule],
  exports: [
    My000381Component,
  ]
})
export class Module000281 { }
