// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000481Component } from './my.000481.component';

@NgModule({
  declarations: [
    My000481Component,
  ],
  imports: [CommonModule],
  exports: [
    My000481Component,
  ]
})
export class Module000281 { }
