// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000481',
  templateUrl: './my.000481.component.html'
})
export class My000481Component {
  @Input() parentName: string;
  myName = 'My000481Component';
}
