// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000445Component } from './my.000445.component';

@NgModule({
  declarations: [
    My000445Component,
  ],
  imports: [CommonModule],
  exports: [
    My000445Component,
  ]
})
export class Module000245 { }
