// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000342Component } from './my.000342.component';

@NgModule({
  declarations: [
    My000342Component,
  ],
  imports: [CommonModule],
  exports: [
    My000342Component,
  ]
})
export class Module000242 { }
