// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000898',
  templateUrl: './my.000898.component.html'
})
export class My000898Component {
  @Input() parentName: string;
  myName = 'My000898Component';
}
