// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001162Component } from './my.001162.component';

@NgModule({
  declarations: [
    My001162Component,
  ],
  imports: [CommonModule],
  exports: [
    My001162Component,
  ]
})
export class Module000962 { }
