// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001162',
  templateUrl: './my.001162.component.html'
})
export class My001162Component {
  @Input() parentName: string;
  myName = 'My001162Component';
}
