// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000498',
  templateUrl: './my.000498.component.html'
})
export class My000498Component {
  @Input() parentName: string;
  myName = 'My000498Component';
}
