// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001041Component } from './my.001041.component';

@NgModule({
  declarations: [
    My001041Component,
  ],
  imports: [CommonModule],
  exports: [
    My001041Component,
  ]
})
export class Module000841 { }
