// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000905',
  templateUrl: './my.000905.component.html'
})
export class My000905Component {
  @Input() parentName: string;
  myName = 'My000905Component';
}
