// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000522',
  templateUrl: './my.000522.component.html'
})
export class My000522Component {
  @Input() parentName: string;
  myName = 'My000522Component';
}
