// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000898Component } from './my.000898.component';

@NgModule({
  declarations: [
    My000898Component,
  ],
  imports: [CommonModule],
  exports: [
    My000898Component,
  ]
})
export class Module000698 { }
