// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000708Component } from './my.000708.component';

@NgModule({
  declarations: [
    My000708Component,
  ],
  imports: [CommonModule],
  exports: [
    My000708Component,
  ]
})
export class Module000508 { }
