// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000608',
  templateUrl: './my.000608.component.html'
})
export class My000608Component {
  @Input() parentName: string;
  myName = 'My000608Component';
}
