// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001195',
  templateUrl: './my.001195.component.html'
})
export class My001195Component {
  @Input() parentName: string;
  myName = 'My001195Component';
}
