// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000553Component } from './my.000553.component';

@NgModule({
  declarations: [
    My000553Component,
  ],
  imports: [CommonModule],
  exports: [
    My000553Component,
  ]
})
export class Module000453 { }
