// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000553',
  templateUrl: './my.000553.component.html'
})
export class My000553Component {
  @Input() parentName: string;
  myName = 'My000553Component';
}
