// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000046',
  templateUrl: './my.000046.component.html'
})
export class My000046Component {
  @Input() parentName: string;
  myName = 'My000046Component';
}
