// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001190Component } from './my.001190.component';

@NgModule({
  declarations: [
    My001190Component,
  ],
  imports: [CommonModule],
  exports: [
    My001190Component,
  ]
})
export class Module000990 { }
