// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001090Component } from './my.001090.component';

@NgModule({
  declarations: [
    My001090Component,
  ],
  imports: [CommonModule],
  exports: [
    My001090Component,
  ]
})
export class Module000990 { }
