// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001090',
  templateUrl: './my.001090.component.html'
})
export class My001090Component {
  @Input() parentName: string;
  myName = 'My001090Component';
}
