// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000891',
  templateUrl: './my.000891.component.html'
})
export class My000891Component {
  @Input() parentName: string;
  myName = 'My000891Component';
}
