// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000819Component } from './my.000819.component';

@NgModule({
  declarations: [
    My000819Component,
  ],
  imports: [CommonModule],
  exports: [
    My000819Component,
  ]
})
export class Module000719 { }
