// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000819',
  templateUrl: './my.000819.component.html'
})
export class My000819Component {
  @Input() parentName: string;
  myName = 'My000819Component';
}
