// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000136Component } from './my.000136.component';
import { My000137Component } from './my.000137.component';

@NgModule({
  declarations: [
    My000136Component,
    My000137Component,
  ],
  imports: [CommonModule],
  exports: [
    My000136Component,
=======
import { My000088Component } from './my.000088.component';

@NgModule({
  declarations: [
    My000088Component,
  ],
  imports: [CommonModule],
  exports: [
    My000088Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000068 { }
