// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000136',
  templateUrl: './my.000136.component.html'
})
export class My000136Component {
  @Input() parentName: string;
  myName = 'My000136Component';
}
