// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000137',
  templateUrl: './my.000137.component.html'
})
export class My000137Component {
  @Input() parentName: string;
  myName = 'My000137Component';
}
