// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001091',
  templateUrl: './my.001091.component.html'
})
export class My001091Component {
  @Input() parentName: string;
  myName = 'My001091Component';
}
