// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000991',
  templateUrl: './my.000991.component.html'
})
export class My000991Component {
  @Input() parentName: string;
  myName = 'My000991Component';
}
