// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000826Component } from './my.000826.component';

@NgModule({
  declarations: [
    My000826Component,
  ],
  imports: [CommonModule],
  exports: [
    My000826Component,
  ]
})
export class Module000626 { }
