// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000994Component } from './my.000994.component';

@NgModule({
  declarations: [
    My000994Component,
  ],
  imports: [CommonModule],
  exports: [
    My000994Component,
  ]
})
export class Module000794 { }
