// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000901',
  templateUrl: './my.000901.component.html'
})
export class My000901Component {
  @Input() parentName: string;
  myName = 'My000901Component';
}
