// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000560Component } from './my.000560.component';

@NgModule({
  declarations: [
    My000560Component,
  ],
  imports: [CommonModule],
  exports: [
    My000560Component,
  ]
})
export class Module000460 { }
