// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000439Component } from './my.000439.component';

@NgModule({
  declarations: [
    My000439Component,
  ],
  imports: [CommonModule],
  exports: [
    My000439Component,
  ]
})
export class Module000239 { }
