// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000439',
  templateUrl: './my.000439.component.html'
})
export class My000439Component {
  @Input() parentName: string;
  myName = 'My000439Component';
}
