// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000729Component } from './my.000729.component';

@NgModule({
  declarations: [
    My000729Component,
  ],
  imports: [CommonModule],
  exports: [
    My000729Component,
  ]
})
export class Module000629 { }
