// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000829',
  templateUrl: './my.000829.component.html'
})
export class My000829Component {
  @Input() parentName: string;
  myName = 'My000829Component';
}
