// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000947Component } from './my.000947.component';

@NgModule({
  declarations: [
    My000947Component,
  ],
  imports: [CommonModule],
  exports: [
    My000947Component,
  ]
})
export class Module000847 { }
