// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000947',
  templateUrl: './my.000947.component.html'
})
export class My000947Component {
  @Input() parentName: string;
  myName = 'My000947Component';
}
