// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000992',
  templateUrl: './my.000992.component.html'
})
export class My000992Component {
  @Input() parentName: string;
  myName = 'My000992Component';
}
