// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001108Component } from './my.001108.component';

@NgModule({
  declarations: [
    My001108Component,
  ],
  imports: [CommonModule],
  exports: [
    My001108Component,
  ]
})
export class Module000908 { }
