// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001008',
  templateUrl: './my.001008.component.html'
})
export class My001008Component {
  @Input() parentName: string;
  myName = 'My001008Component';
}
