// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000929Component } from './my.000929.component';

@NgModule({
  declarations: [
    My000929Component,
  ],
  imports: [CommonModule],
  exports: [
    My000929Component,
  ]
})
export class Module000729 { }
