// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001044Component } from './my.001044.component';

@NgModule({
  declarations: [
    My001044Component,
  ],
  imports: [CommonModule],
  exports: [
    My001044Component,
  ]
})
export class Module000844 { }
