// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000944',
  templateUrl: './my.000944.component.html'
})
export class My000944Component {
  @Input() parentName: string;
  myName = 'My000944Component';
}
