// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000485Component } from './my.000485.component';

@NgModule({
  declarations: [
    My000485Component,
  ],
  imports: [CommonModule],
  exports: [
    My000485Component,
  ]
})
export class Module000385 { }
