// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000655Component } from './my.000655.component';

@NgModule({
  declarations: [
    My000655Component,
  ],
  imports: [CommonModule],
  exports: [
    My000655Component,
  ]
})
export class Module000555 { }
