// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000825Component } from './my.000825.component';

@NgModule({
  declarations: [
    My000825Component,
  ],
  imports: [CommonModule],
  exports: [
    My000825Component,
  ]
})
export class Module000725 { }
