// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000248Component } from './my.000248.component';
import { My000249Component } from './my.000249.component';

@NgModule({
  declarations: [
    My000248Component,
    My000249Component,
  ],
  imports: [CommonModule],
  exports: [
    My000248Component,
  ]
})
export class Module000124 { }
