// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000637Component } from './my.000637.component';

@NgModule({
  declarations: [
    My000637Component,
  ],
  imports: [CommonModule],
  exports: [
    My000637Component,
  ]
})
export class Module000437 { }
