// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000537',
  templateUrl: './my.000537.component.html'
})
export class My000537Component {
  @Input() parentName: string;
  myName = 'My000537Component';
}
