// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000076Component } from './my.000076.component';

@NgModule({
  declarations: [
    My000076Component,
  ],
  imports: [CommonModule],
  exports: [
    My000076Component,
  ]
})
export class Module000056 { }
