// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000263Component } from './my.000263.component';

@NgModule({
  declarations: [
    My000263Component,
  ],
  imports: [CommonModule],
  exports: [
    My000263Component,
  ]
})
export class Module000163 { }
