// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000326',
  templateUrl: './my.000326.component.html'
})
export class My000326Component {
  @Input() parentName: string;
  myName = 'My000326Component';
}
