// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000631Component } from './my.000631.component';

@NgModule({
  declarations: [
    My000631Component,
  ],
  imports: [CommonModule],
  exports: [
    My000631Component,
  ]
})
export class Module000431 { }
