// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000206Component } from './my.000206.component';

@NgModule({
  declarations: [
    My000206Component,
  ],
  imports: [CommonModule],
  exports: [
    My000206Component,
  ]
})
export class Module000106 { }
