// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000213',
  templateUrl: './my.000213.component.html'
})
export class My000213Component {
  @Input() parentName: string;
  myName = 'My000213Component';
}
