// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000206',
  templateUrl: './my.000206.component.html'
})
export class My000206Component {
  @Input() parentName: string;
  myName = 'My000206Component';
}
