// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001155Component } from './my.001155.component';

@NgModule({
  declarations: [
    My001155Component,
  ],
  imports: [CommonModule],
  exports: [
    My001155Component,
  ]
})
export class Module000955 { }
