// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001055',
  templateUrl: './my.001055.component.html'
})
export class My001055Component {
  @Input() parentName: string;
  myName = 'My001055Component';
}
