// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000588Component } from './my.000588.component';

@NgModule({
  declarations: [
    My000588Component,
  ],
  imports: [CommonModule],
  exports: [
    My000588Component,
  ]
})
export class Module000388 { }
