// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000488Component } from './my.000488.component';

@NgModule({
  declarations: [
    My000488Component,
  ],
  imports: [CommonModule],
  exports: [
    My000488Component,
  ]
})
export class Module000388 { }
