// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000381',
  templateUrl: './my.000381.component.html'
})
export class My000381Component {
  @Input() parentName: string;
  myName = 'My000381Component';
}
