// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000020',
  templateUrl: './my.000020.component.html'
})
export class My000020Component {
  @Input() parentName: string;
  myName = 'My000020Component';
}
