// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000834Component } from './my.000834.component';

@NgModule({
  declarations: [
    My000834Component,
  ],
  imports: [CommonModule],
  exports: [
    My000834Component,
  ]
})
export class Module000634 { }
