// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000029',
  templateUrl: './my.000029.component.html'
})
export class My000029Component {
  @Input() parentName: string;
  myName = 'My000029Component';
}
