// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000844Component } from './my.000844.component';

@NgModule({
  declarations: [
    My000844Component,
  ],
  imports: [CommonModule],
  exports: [
    My000844Component,
  ]
})
export class Module000744 { }
