// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000118Component } from './my.000118.component';
import { My000119Component } from './my.000119.component';

@NgModule({
  declarations: [
    My000118Component,
    My000119Component,
  ],
  imports: [CommonModule],
  exports: [
    My000118Component,
=======
import { My000079Component } from './my.000079.component';

@NgModule({
  declarations: [
    My000079Component,
  ],
  imports: [CommonModule],
  exports: [
    My000079Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000059 { }
