// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000079Component } from './my.000079.component';

@NgModule({
  declarations: [
    My000079Component,
  ],
  imports: [CommonModule],
  exports: [
    My000079Component,
  ]
})
export class Module000059 { }
