// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000079',
  templateUrl: './my.000079.component.html'
})
export class My000079Component {
  @Input() parentName: string;
  myName = 'My000079Component';
}
