// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000606',
  templateUrl: './my.000606.component.html'
})
export class My000606Component {
  @Input() parentName: string;
  myName = 'My000606Component';
}
