// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000597',
  templateUrl: './my.000597.component.html'
})
export class My000597Component {
  @Input() parentName: string;
  myName = 'My000597Component';
}
