// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000951',
  templateUrl: './my.000951.component.html'
})
export class My000951Component {
  @Input() parentName: string;
  myName = 'My000951Component';
}
