// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000273Component } from './my.000273.component';

@NgModule({
  declarations: [
    My000273Component,
  ],
  imports: [CommonModule],
  exports: [
    My000273Component,
  ]
})
export class Module000173 { }
