// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000346',
  templateUrl: './my.000346.component.html'
})
export class My000346Component {
  @Input() parentName: string;
  myName = 'My000346Component';
}
