// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001096Component } from './my.001096.component';

@NgModule({
  declarations: [
    My001096Component,
  ],
  imports: [CommonModule],
  exports: [
    My001096Component,
  ]
})
export class Module000896 { }
