// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000996',
  templateUrl: './my.000996.component.html'
})
export class My000996Component {
  @Input() parentName: string;
  myName = 'My000996Component';
}
