// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001029',
  templateUrl: './my.001029.component.html'
})
export class My001029Component {
  @Input() parentName: string;
  myName = 'My001029Component';
}
