// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000084Component } from './my.000084.component';
import { My000085Component } from './my.000085.component';

@NgModule({
  declarations: [
    My000084Component,
    My000085Component,
  ],
  imports: [CommonModule],
  exports: [
    My000084Component,
  ]
})
export class Module000042 { }
