// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000085',
  templateUrl: './my.000085.component.html'
})
export class My000085Component {
  @Input() parentName: string;
  myName = 'My000085Component';
}
