// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000084',
  templateUrl: './my.000084.component.html'
})
export class My000084Component {
  @Input() parentName: string;
  myName = 'My000084Component';
}
