// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000933',
  templateUrl: './my.000933.component.html'
})
export class My000933Component {
  @Input() parentName: string;
  myName = 'My000933Component';
}
