// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000474Component } from './my.000474.component';

@NgModule({
  declarations: [
    My000474Component,
  ],
  imports: [CommonModule],
  exports: [
    My000474Component,
  ]
})
export class Module000274 { }
