// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000474',
  templateUrl: './my.000474.component.html'
})
export class My000474Component {
  @Input() parentName: string;
  myName = 'My000474Component';
}
