// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000842',
  templateUrl: './my.000842.component.html'
})
export class My000842Component {
  @Input() parentName: string;
  myName = 'My000842Component';
}
