// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001123Component } from './my.001123.component';

@NgModule({
  declarations: [
    My001123Component,
  ],
  imports: [CommonModule],
  exports: [
    My001123Component,
  ]
})
export class Module000923 { }
