// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001123',
  templateUrl: './my.001123.component.html'
})
export class My001123Component {
  @Input() parentName: string;
  myName = 'My001123Component';
}
