// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000050Component } from './my.000050.component';
import { My000051Component } from './my.000051.component';

@NgModule({
  declarations: [
    My000050Component,
    My000051Component,
  ],
  imports: [CommonModule],
  exports: [
    My000050Component,
=======
import { My000045Component } from './my.000045.component';

@NgModule({
  declarations: [
    My000045Component,
  ],
  imports: [CommonModule],
  exports: [
    My000045Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000025 { }
