// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000045',
  templateUrl: './my.000045.component.html'
})
export class My000045Component {
  @Input() parentName: string;
  myName = 'My000045Component';
}
