// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000250Component } from './my.000250.component';
import { My000251Component } from './my.000251.component';

@NgModule({
  declarations: [
    My000250Component,
    My000251Component,
  ],
  imports: [CommonModule],
  exports: [
    My000250Component,
  ]
})
export class Module000125 { }
