// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000225',
  templateUrl: './my.000225.component.html'
})
export class My000225Component {
  @Input() parentName: string;
  myName = 'My000225Component';
}
