// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000664',
  templateUrl: './my.000664.component.html'
})
export class My000664Component {
  @Input() parentName: string;
  myName = 'My000664Component';
}
