// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001064Component } from './my.001064.component';

@NgModule({
  declarations: [
    My001064Component,
  ],
  imports: [CommonModule],
  exports: [
    My001064Component,
  ]
})
export class Module000964 { }
