// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001164',
  templateUrl: './my.001164.component.html'
})
export class My001164Component {
  @Input() parentName: string;
  myName = 'My001164Component';
}
