// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000455Component } from './my.000455.component';

@NgModule({
  declarations: [
    My000455Component,
  ],
  imports: [CommonModule],
  exports: [
    My000455Component,
  ]
})
export class Module000355 { }
