// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000455',
  templateUrl: './my.000455.component.html'
})
export class My000455Component {
  @Input() parentName: string;
  myName = 'My000455Component';
}
