// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000770Component } from './my.000770.component';

@NgModule({
  declarations: [
    My000770Component,
  ],
  imports: [CommonModule],
  exports: [
    My000770Component,
  ]
})
export class Module000670 { }
