// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000258Component } from './my.000258.component';

@NgModule({
  declarations: [
    My000258Component,
  ],
  imports: [CommonModule],
  exports: [
    My000258Component,
  ]
})
export class Module000158 { }
