// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000392',
  templateUrl: './my.000392.component.html'
})
export class My000392Component {
  @Input() parentName: string;
  myName = 'My000392Component';
}
