// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000892Component } from './my.000892.component';

@NgModule({
  declarations: [
    My000892Component,
  ],
  imports: [CommonModule],
  exports: [
    My000892Component,
  ]
})
export class Module000692 { }
