// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000792Component } from './my.000792.component';

@NgModule({
  declarations: [
    My000792Component,
  ],
  imports: [CommonModule],
  exports: [
    My000792Component,
  ]
})
export class Module000692 { }
