// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000310Component } from './my.000310.component';

@NgModule({
  declarations: [
    My000310Component,
  ],
  imports: [CommonModule],
  exports: [
    My000310Component,
  ]
})
export class Module000210 { }
