// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000724Component } from './my.000724.component';

@NgModule({
  declarations: [
    My000724Component,
  ],
  imports: [CommonModule],
  exports: [
    My000724Component,
  ]
})
export class Module000524 { }
