// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000724',
  templateUrl: './my.000724.component.html'
})
export class My000724Component {
  @Input() parentName: string;
  myName = 'My000724Component';
}
