// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000331Component } from './my.000331.component';

@NgModule({
  declarations: [
    My000331Component,
  ],
  imports: [CommonModule],
  exports: [
    My000331Component,
  ]
})
export class Module000231 { }
