// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000431',
  templateUrl: './my.000431.component.html'
})
export class My000431Component {
  @Input() parentName: string;
  myName = 'My000431Component';
}
