// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000779Component } from './my.000779.component';

@NgModule({
  declarations: [
    My000779Component,
  ],
  imports: [CommonModule],
  exports: [
    My000779Component,
  ]
})
export class Module000579 { }
