// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000665Component } from './my.000665.component';

@NgModule({
  declarations: [
    My000665Component,
  ],
  imports: [CommonModule],
  exports: [
    My000665Component,
  ]
})
export class Module000565 { }
