// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000765Component } from './my.000765.component';

@NgModule({
  declarations: [
    My000765Component,
  ],
  imports: [CommonModule],
  exports: [
    My000765Component,
  ]
})
export class Module000565 { }
