// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000665',
  templateUrl: './my.000665.component.html'
})
export class My000665Component {
  @Input() parentName: string;
  myName = 'My000665Component';
}
