// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000765',
  templateUrl: './my.000765.component.html'
})
export class My000765Component {
  @Input() parentName: string;
  myName = 'My000765Component';
}
