// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000254',
  templateUrl: './my.000254.component.html'
})
export class My000254Component {
  @Input() parentName: string;
  myName = 'My000254Component';
}
