// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000900Component } from './my.000900.component';

@NgModule({
  declarations: [
    My000900Component,
  ],
  imports: [CommonModule],
  exports: [
    My000900Component,
  ]
})
export class Module000700 { }
