// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000176',
  templateUrl: './my.000176.component.html'
})
export class My000176Component {
  @Input() parentName: string;
  myName = 'My000176Component';
}
