// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000952',
  templateUrl: './my.000952.component.html'
})
export class My000952Component {
  @Input() parentName: string;
  myName = 'My000952Component';
}
