// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000222Component } from './my.000222.component';

@NgModule({
  declarations: [
    My000222Component,
  ],
  imports: [CommonModule],
  exports: [
    My000222Component,
  ]
})
export class Module000122 { }
