// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000857',
  templateUrl: './my.000857.component.html'
})
export class My000857Component {
  @Input() parentName: string;
  myName = 'My000857Component';
}
