// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000245Component } from './my.000245.component';

@NgModule({
  declarations: [
    My000245Component,
  ],
  imports: [CommonModule],
  exports: [
    My000245Component,
  ]
})
export class Module000145 { }
