// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000311',
  templateUrl: './my.000311.component.html'
})
export class My000311Component {
  @Input() parentName: string;
  myName = 'My000311Component';
}
