// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000269Component } from './my.000269.component';

@NgModule({
  declarations: [
    My000269Component,
  ],
  imports: [CommonModule],
  exports: [
    My000269Component,
  ]
})
export class Module000169 { }
