// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000338Component } from './my.000338.component';
import { My000339Component } from './my.000339.component';

@NgModule({
  declarations: [
    My000338Component,
    My000339Component,
  ],
  imports: [CommonModule],
  exports: [
    My000338Component,
  ]
})
export class Module000169 { }
