// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000339',
  templateUrl: './my.000339.component.html'
})
export class My000339Component {
  @Input() parentName: string;
  myName = 'My000339Component';
}
