// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000338',
  templateUrl: './my.000338.component.html'
})
export class My000338Component {
  @Input() parentName: string;
  myName = 'My000338Component';
}
