// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000961Component } from './my.000961.component';

@NgModule({
  declarations: [
    My000961Component,
  ],
  imports: [CommonModule],
  exports: [
    My000961Component,
  ]
})
export class Module000761 { }
