// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001152Component } from './my.001152.component';

@NgModule({
  declarations: [
    My001152Component,
  ],
  imports: [CommonModule],
  exports: [
    My001152Component,
  ]
})
export class Module000952 { }
