// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001152',
  templateUrl: './my.001152.component.html'
})
export class My001152Component {
  @Input() parentName: string;
  myName = 'My001152Component';
}
