// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001142',
  templateUrl: './my.001142.component.html'
})
export class My001142Component {
  @Input() parentName: string;
  myName = 'My001142Component';
}
