// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000473',
  templateUrl: './my.000473.component.html'
})
export class My000473Component {
  @Input() parentName: string;
  myName = 'My000473Component';
}
