// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000573',
  templateUrl: './my.000573.component.html'
})
export class My000573Component {
  @Input() parentName: string;
  myName = 'My000573Component';
}
