// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000729',
  templateUrl: './my.000729.component.html'
})
export class My000729Component {
  @Input() parentName: string;
  myName = 'My000729Component';
}
