// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001148Component } from './my.001148.component';

@NgModule({
  declarations: [
    My001148Component,
  ],
  imports: [CommonModule],
  exports: [
    My001148Component,
  ]
})
export class Module000948 { }
