// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001048',
  templateUrl: './my.001048.component.html'
})
export class My001048Component {
  @Input() parentName: string;
  myName = 'My001048Component';
}
