// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000388Component } from './my.000388.component';
import { My000389Component } from './my.000389.component';

@NgModule({
  declarations: [
    My000388Component,
    My000389Component,
  ],
  imports: [CommonModule],
  exports: [
    My000388Component,
  ]
})
export class Module000194 { }
