// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000294',
  templateUrl: './my.000294.component.html'
})
export class My000294Component {
  @Input() parentName: string;
  myName = 'My000294Component';
}
