// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000389',
  templateUrl: './my.000389.component.html'
})
export class My000389Component {
  @Input() parentName: string;
  myName = 'My000389Component';
}
