// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000802Component } from './my.000802.component';

@NgModule({
  declarations: [
    My000802Component,
  ],
  imports: [CommonModule],
  exports: [
    My000802Component,
  ]
})
export class Module000602 { }
