// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000824',
  templateUrl: './my.000824.component.html'
})
export class My000824Component {
  @Input() parentName: string;
  myName = 'My000824Component';
}
