// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000792',
  templateUrl: './my.000792.component.html'
})
export class My000792Component {
  @Input() parentName: string;
  myName = 'My000792Component';
}
