// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000983Component } from './my.000983.component';

@NgModule({
  declarations: [
    My000983Component,
  ],
  imports: [CommonModule],
  exports: [
    My000983Component,
  ]
})
export class Module000883 { }
