// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000983',
  templateUrl: './my.000983.component.html'
})
export class My000983Component {
  @Input() parentName: string;
  myName = 'My000983Component';
}
