// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001068',
  templateUrl: './my.001068.component.html'
})
export class My001068Component {
  @Input() parentName: string;
  myName = 'My001068Component';
}
