// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001168',
  templateUrl: './my.001168.component.html'
})
export class My001168Component {
  @Input() parentName: string;
  myName = 'My001168Component';
}
