// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000912Component } from './my.000912.component';

@NgModule({
  declarations: [
    My000912Component,
  ],
  imports: [CommonModule],
  exports: [
    My000912Component,
  ]
})
export class Module000712 { }
