// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000812',
  templateUrl: './my.000812.component.html'
})
export class My000812Component {
  @Input() parentName: string;
  myName = 'My000812Component';
}
