// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000912',
  templateUrl: './my.000912.component.html'
})
export class My000912Component {
  @Input() parentName: string;
  myName = 'My000912Component';
}
