// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000538',
  templateUrl: './my.000538.component.html'
})
export class My000538Component {
  @Input() parentName: string;
  myName = 'My000538Component';
}
