// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000179',
  templateUrl: './my.000179.component.html'
})
export class My000179Component {
  @Input() parentName: string;
  myName = 'My000179Component';
}
