// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000109',
  templateUrl: './my.000109.component.html'
})
export class My000109Component {
  @Input() parentName: string;
  myName = 'My000109Component';
}
