// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000932Component } from './my.000932.component';

@NgModule({
  declarations: [
    My000932Component,
  ],
  imports: [CommonModule],
  exports: [
    My000932Component,
  ]
})
export class Module000732 { }
