// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000052Component } from './my.000052.component';

@NgModule({
  declarations: [
    My000052Component,
  ],
  imports: [CommonModule],
  exports: [
    My000052Component,
  ]
})
export class Module000032 { }
