// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000052',
  templateUrl: './my.000052.component.html'
})
export class My000052Component {
  @Input() parentName: string;
  myName = 'My000052Component';
}
