// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000534Component } from './my.000534.component';

@NgModule({
  declarations: [
    My000534Component,
  ],
  imports: [CommonModule],
  exports: [
    My000534Component,
  ]
})
export class Module000434 { }
