// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001011',
  templateUrl: './my.001011.component.html'
})
export class My001011Component {
  @Input() parentName: string;
  myName = 'My001011Component';
}
