// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001182',
  templateUrl: './my.001182.component.html'
})
export class My001182Component {
  @Input() parentName: string;
  myName = 'My001182Component';
}
