// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001180',
  templateUrl: './my.001180.component.html'
})
export class My001180Component {
  @Input() parentName: string;
  myName = 'My001180Component';
}
