// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001080',
  templateUrl: './my.001080.component.html'
})
export class My001080Component {
  @Input() parentName: string;
  myName = 'My001080Component';
}
