// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000301',
  templateUrl: './my.000301.component.html'
})
export class My000301Component {
  @Input() parentName: string;
  myName = 'My000301Component';
}
