// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000813Component } from './my.000813.component';

@NgModule({
  declarations: [
    My000813Component,
  ],
  imports: [CommonModule],
  exports: [
    My000813Component,
  ]
})
export class Module000613 { }
