// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000713',
  templateUrl: './my.000713.component.html'
})
export class My000713Component {
  @Input() parentName: string;
  myName = 'My000713Component';
}
