// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000594Component } from './my.000594.component';

@NgModule({
  declarations: [
    My000594Component,
  ],
  imports: [CommonModule],
  exports: [
    My000594Component,
  ]
})
export class Module000394 { }
