// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000494',
  templateUrl: './my.000494.component.html'
})
export class My000494Component {
  @Input() parentName: string;
  myName = 'My000494Component';
}
