// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000264Component } from './my.000264.component';
import { My000265Component } from './my.000265.component';

@NgModule({
  declarations: [
    My000264Component,
    My000265Component,
  ],
  imports: [CommonModule],
  exports: [
    My000264Component,
  ]
})
export class Module000132 { }
