// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000232',
  templateUrl: './my.000232.component.html'
})
export class My000232Component {
  @Input() parentName: string;
  myName = 'My000232Component';
}
