// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001026Component } from './my.001026.component';

@NgModule({
  declarations: [
    My001026Component,
  ],
  imports: [CommonModule],
  exports: [
    My001026Component,
  ]
})
export class Module000926 { }
