// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001126',
  templateUrl: './my.001126.component.html'
})
export class My001126Component {
  @Input() parentName: string;
  myName = 'My001126Component';
}
