// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000414',
  templateUrl: './my.000414.component.html'
})
export class My000414Component {
  @Input() parentName: string;
  myName = 'My000414Component';
}
