// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001071Component } from './my.001071.component';

@NgModule({
  declarations: [
    My001071Component,
  ],
  imports: [CommonModule],
  exports: [
    My001071Component,
  ]
})
export class Module000971 { }
