// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001171',
  templateUrl: './my.001171.component.html'
})
export class My001171Component {
  @Input() parentName: string;
  myName = 'My001171Component';
}
