// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000874',
  templateUrl: './my.000874.component.html'
})
export class My000874Component {
  @Input() parentName: string;
  myName = 'My000874Component';
}
