// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000914',
  templateUrl: './my.000914.component.html'
})
export class My000914Component {
  @Input() parentName: string;
  myName = 'My000914Component';
}
