// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001014',
  templateUrl: './my.001014.component.html'
})
export class My001014Component {
  @Input() parentName: string;
  myName = 'My001014Component';
}
