// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000580',
  templateUrl: './my.000580.component.html'
})
export class My000580Component {
  @Input() parentName: string;
  myName = 'My000580Component';
}
