// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000086Component } from './my.000086.component';

@NgModule({
  declarations: [
    My000086Component,
  ],
  imports: [CommonModule],
  exports: [
    My000086Component,
  ]
})
export class Module000066 { }
