// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000132Component } from './my.000132.component';
import { My000133Component } from './my.000133.component';

@NgModule({
  declarations: [
    My000132Component,
    My000133Component,
  ],
  imports: [CommonModule],
  exports: [
    My000132Component,
  ]
})
export class Module000066 { }
