// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000879Component } from './my.000879.component';

@NgModule({
  declarations: [
    My000879Component,
  ],
  imports: [CommonModule],
  exports: [
    My000879Component,
  ]
})
export class Module000779 { }
