// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000657Component } from './my.000657.component';

@NgModule({
  declarations: [
    My000657Component,
  ],
  imports: [CommonModule],
  exports: [
    My000657Component,
  ]
})
export class Module000457 { }
