// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000862',
  templateUrl: './my.000862.component.html'
})
export class My000862Component {
  @Input() parentName: string;
  myName = 'My000862Component';
}
