// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000292Component } from './my.000292.component';

@NgModule({
  declarations: [
    My000292Component,
  ],
  imports: [CommonModule],
  exports: [
    My000292Component,
  ]
})
export class Module000192 { }
