// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000292',
  templateUrl: './my.000292.component.html'
})
export class My000292Component {
  @Input() parentName: string;
  myName = 'My000292Component';
}
