// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000822Component } from './my.000822.component';

@NgModule({
  declarations: [
    My000822Component,
  ],
  imports: [CommonModule],
  exports: [
    My000822Component,
  ]
})
export class Module000622 { }
