// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000040Component } from './my.000040.component';

@NgModule({
  declarations: [
    My000040Component,
  ],
  imports: [CommonModule],
  exports: [
    My000040Component,
  ]
})
export class Module000020 { }
