// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000040',
  templateUrl: './my.000040.component.html'
})
export class My000040Component {
  @Input() parentName: string;
  myName = 'My000040Component';
}
