// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000411Component } from './my.000411.component';

@NgModule({
  declarations: [
    My000411Component,
  ],
  imports: [CommonModule],
  exports: [
    My000411Component,
  ]
})
export class Module000311 { }
