// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000411',
  templateUrl: './my.000411.component.html'
})
export class My000411Component {
  @Input() parentName: string;
  myName = 'My000411Component';
}
