// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000130',
  templateUrl: './my.000130.component.html'
})
export class My000130Component {
  @Input() parentName: string;
  myName = 'My000130Component';
}
