// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001018Component } from './my.001018.component';

@NgModule({
  declarations: [
    My001018Component,
  ],
  imports: [CommonModule],
  exports: [
    My001018Component,
  ]
})
export class Module000818 { }
