// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000918',
  templateUrl: './my.000918.component.html'
})
export class My000918Component {
  @Input() parentName: string;
  myName = 'My000918Component';
}
