// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000842Component } from './my.000842.component';

@NgModule({
  declarations: [
    My000842Component,
  ],
  imports: [CommonModule],
  exports: [
    My000842Component,
  ]
})
export class Module000642 { }
