// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000682Component } from './my.000682.component';

@NgModule({
  declarations: [
    My000682Component,
  ],
  imports: [CommonModule],
  exports: [
    My000682Component,
  ]
})
export class Module000482 { }
