// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000577',
  templateUrl: './my.000577.component.html'
})
export class My000577Component {
  @Input() parentName: string;
  myName = 'My000577Component';
}
