// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000344Component } from './my.000344.component';

@NgModule({
  declarations: [
    My000344Component,
  ],
  imports: [CommonModule],
  exports: [
    My000344Component,
  ]
})
export class Module000244 { }
