// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000444',
  templateUrl: './my.000444.component.html'
})
export class My000444Component {
  @Input() parentName: string;
  myName = 'My000444Component';
}
