// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000542Component } from './my.000542.component';

@NgModule({
  declarations: [
    My000542Component,
  ],
  imports: [CommonModule],
  exports: [
    My000542Component,
  ]
})
export class Module000442 { }
