// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000848',
  templateUrl: './my.000848.component.html'
})
export class My000848Component {
  @Input() parentName: string;
  myName = 'My000848Component';
}
