// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000529',
  templateUrl: './my.000529.component.html'
})
export class My000529Component {
  @Input() parentName: string;
  myName = 'My000529Component';
}
