// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000027',
  templateUrl: './my.000027.component.html'
})
export class My000027Component {
  @Input() parentName: string;
  myName = 'My000027Component';
}
