// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000534',
  templateUrl: './my.000534.component.html'
})
export class My000534Component {
  @Input() parentName: string;
  myName = 'My000534Component';
}
