// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000434',
  templateUrl: './my.000434.component.html'
})
export class My000434Component {
  @Input() parentName: string;
  myName = 'My000434Component';
}
