// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000878Component } from './my.000878.component';

@NgModule({
  declarations: [
    My000878Component,
  ],
  imports: [CommonModule],
  exports: [
    My000878Component,
  ]
})
export class Module000678 { }
