// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000878',
  templateUrl: './my.000878.component.html'
})
export class My000878Component {
  @Input() parentName: string;
  myName = 'My000878Component';
}
