// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001140Component } from './my.001140.component';

@NgModule({
  declarations: [
    My001140Component,
  ],
  imports: [CommonModule],
  exports: [
    My001140Component,
  ]
})
export class Module000940 { }
