// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001040',
  templateUrl: './my.001040.component.html'
})
export class My001040Component {
  @Input() parentName: string;
  myName = 'My001040Component';
}
