// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000518',
  templateUrl: './my.000518.component.html'
})
export class My000518Component {
  @Input() parentName: string;
  myName = 'My000518Component';
}
