// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000447Component } from './my.000447.component';

@NgModule({
  declarations: [
    My000447Component,
  ],
  imports: [CommonModule],
  exports: [
    My000447Component,
  ]
})
export class Module000247 { }
