// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000347Component } from './my.000347.component';

@NgModule({
  declarations: [
    My000347Component,
  ],
  imports: [CommonModule],
  exports: [
    My000347Component,
  ]
})
export class Module000247 { }
