// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001006Component } from './my.001006.component';

@NgModule({
  declarations: [
    My001006Component,
  ],
  imports: [CommonModule],
  exports: [
    My001006Component,
  ]
})
export class Module000906 { }
