// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001106',
  templateUrl: './my.001106.component.html'
})
export class My001106Component {
  @Input() parentName: string;
  myName = 'My001106Component';
}
