// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001052',
  templateUrl: './my.001052.component.html'
})
export class My001052Component {
  @Input() parentName: string;
  myName = 'My001052Component';
}
