// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000213Component } from './my.000213.component';

@NgModule({
  declarations: [
    My000213Component,
  ],
  imports: [CommonModule],
  exports: [
    My000213Component,
  ]
})
export class Module000113 { }
