// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000959Component } from './my.000959.component';

@NgModule({
  declarations: [
    My000959Component,
  ],
  imports: [CommonModule],
  exports: [
    My000959Component,
  ]
})
export class Module000759 { }
