// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000113',
  templateUrl: './my.000113.component.html'
})
export class My000113Component {
  @Input() parentName: string;
  myName = 'My000113Component';
}
