// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000187',
  templateUrl: './my.000187.component.html'
})
export class My000187Component {
  @Input() parentName: string;
  myName = 'My000187Component';
}
