// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000105',
  templateUrl: './my.000105.component.html'
})
export class My000105Component {
  @Input() parentName: string;
  myName = 'My000105Component';
}
