// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000977Component } from './my.000977.component';

@NgModule({
  declarations: [
    My000977Component,
  ],
  imports: [CommonModule],
  exports: [
    My000977Component,
  ]
})
export class Module000877 { }
