// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001077',
  templateUrl: './my.001077.component.html'
})
export class My001077Component {
  @Input() parentName: string;
  myName = 'My001077Component';
}
