// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000772Component } from './my.000772.component';

@NgModule({
  declarations: [
    My000772Component,
  ],
  imports: [CommonModule],
  exports: [
    My000772Component,
  ]
})
export class Module000572 { }
