// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000672',
  templateUrl: './my.000672.component.html'
})
export class My000672Component {
  @Input() parentName: string;
  myName = 'My000672Component';
}
