// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000164',
  templateUrl: './my.000164.component.html'
})
export class My000164Component {
  @Input() parentName: string;
  myName = 'My000164Component';
}
