// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000796',
  templateUrl: './my.000796.component.html'
})
export class My000796Component {
  @Input() parentName: string;
  myName = 'My000796Component';
}
