// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000896',
  templateUrl: './my.000896.component.html'
})
export class My000896Component {
  @Input() parentName: string;
  myName = 'My000896Component';
}
