// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001043Component } from './my.001043.component';

@NgModule({
  declarations: [
    My001043Component,
  ],
  imports: [CommonModule],
  exports: [
    My001043Component,
  ]
})
export class Module000843 { }
