// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000970',
  templateUrl: './my.000970.component.html'
})
export class My000970Component {
  @Input() parentName: string;
  myName = 'My000970Component';
}
