// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000870',
  templateUrl: './my.000870.component.html'
})
export class My000870Component {
  @Input() parentName: string;
  myName = 'My000870Component';
}
