// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000632Component } from './my.000632.component';

@NgModule({
  declarations: [
    My000632Component,
  ],
  imports: [CommonModule],
  exports: [
    My000632Component,
  ]
})
export class Module000532 { }
