// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000632',
  templateUrl: './my.000632.component.html'
})
export class My000632Component {
  @Input() parentName: string;
  myName = 'My000632Component';
}
