// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000435Component } from './my.000435.component';

@NgModule({
  declarations: [
    My000435Component,
  ],
  imports: [CommonModule],
  exports: [
    My000435Component,
  ]
})
export class Module000235 { }
