// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000335',
  templateUrl: './my.000335.component.html'
})
export class My000335Component {
  @Input() parentName: string;
  myName = 'My000335Component';
}
