// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000202Component } from './my.000202.component';

@NgModule({
  declarations: [
    My000202Component,
  ],
  imports: [CommonModule],
  exports: [
    My000202Component,
  ]
})
export class Module000102 { }
