// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000204Component } from './my.000204.component';
import { My000205Component } from './my.000205.component';

@NgModule({
  declarations: [
    My000204Component,
    My000205Component,
  ],
  imports: [CommonModule],
  exports: [
    My000204Component,
  ]
})
export class Module000102 { }
