// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000202',
  templateUrl: './my.000202.component.html'
})
export class My000202Component {
  @Input() parentName: string;
  myName = 'My000202Component';
}
