// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000476Component } from './my.000476.component';

@NgModule({
  declarations: [
    My000476Component,
  ],
  imports: [CommonModule],
  exports: [
    My000476Component,
  ]
})
export class Module000376 { }
