// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000930Component } from './my.000930.component';

@NgModule({
  declarations: [
    My000930Component,
  ],
  imports: [CommonModule],
  exports: [
    My000930Component,
  ]
})
export class Module000830 { }
