// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000680',
  templateUrl: './my.000680.component.html'
})
export class My000680Component {
  @Input() parentName: string;
  myName = 'My000680Component';
}
