// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000309Component } from './my.000309.component';

@NgModule({
  declarations: [
    My000309Component,
  ],
  imports: [CommonModule],
  exports: [
    My000309Component,
  ]
})
export class Module000209 { }
