// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000392Component } from './my.000392.component';

@NgModule({
  declarations: [
    My000392Component,
  ],
  imports: [CommonModule],
  exports: [
    My000392Component,
  ]
})
export class Module000292 { }
