// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001172Component } from './my.001172.component';

@NgModule({
  declarations: [
    My001172Component,
  ],
  imports: [CommonModule],
  exports: [
    My001172Component,
  ]
})
export class Module000972 { }
