// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000097Component } from './my.000097.component';

@NgModule({
  declarations: [
    My000097Component,
  ],
  imports: [CommonModule],
  exports: [
    My000097Component,
  ]
})
export class Module000077 { }
