// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000499',
  templateUrl: './my.000499.component.html'
})
export class My000499Component {
  @Input() parentName: string;
  myName = 'My000499Component';
}
