// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000978Component } from './my.000978.component';

@NgModule({
  declarations: [
    My000978Component,
  ],
  imports: [CommonModule],
  exports: [
    My000978Component,
  ]
})
export class Module000878 { }
