// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001163Component } from './my.001163.component';

@NgModule({
  declarations: [
    My001163Component,
  ],
  imports: [CommonModule],
  exports: [
    My001163Component,
  ]
})
export class Module000963 { }
