// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001163',
  templateUrl: './my.001163.component.html'
})
export class My001163Component {
  @Input() parentName: string;
  myName = 'My001163Component';
}
