// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000620Component } from './my.000620.component';

@NgModule({
  declarations: [
    My000620Component,
  ],
  imports: [CommonModule],
  exports: [
    My000620Component,
  ]
})
export class Module000420 { }
