// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000620',
  templateUrl: './my.000620.component.html'
})
export class My000620Component {
  @Input() parentName: string;
  myName = 'My000620Component';
}
