// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000778Component } from './my.000778.component';

@NgModule({
  declarations: [
    My000778Component,
  ],
  imports: [CommonModule],
  exports: [
    My000778Component,
  ]
})
export class Module000578 { }
