// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000494Component } from './my.000494.component';

@NgModule({
  declarations: [
    My000494Component,
  ],
  imports: [CommonModule],
  exports: [
    My000494Component,
  ]
})
export class Module000294 { }
