// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000394Component } from './my.000394.component';

@NgModule({
  declarations: [
    My000394Component,
  ],
  imports: [CommonModule],
  exports: [
    My000394Component,
  ]
})
export class Module000294 { }
