// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000394',
  templateUrl: './my.000394.component.html'
})
export class My000394Component {
  @Input() parentName: string;
  myName = 'My000394Component';
}
