// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001119Component } from './my.001119.component';

@NgModule({
  declarations: [
    My001119Component,
  ],
  imports: [CommonModule],
  exports: [
    My001119Component,
  ]
})
export class Module000919 { }
