// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000570Component } from './my.000570.component';

@NgModule({
  declarations: [
    My000570Component,
  ],
  imports: [CommonModule],
  exports: [
    My000570Component,
  ]
})
export class Module000470 { }
