// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000670Component } from './my.000670.component';

@NgModule({
  declarations: [
    My000670Component,
  ],
  imports: [CommonModule],
  exports: [
    My000670Component,
  ]
})
export class Module000470 { }
