// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000681',
  templateUrl: './my.000681.component.html'
})
export class My000681Component {
  @Input() parentName: string;
  myName = 'My000681Component';
}
