// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000072',
  templateUrl: './my.000072.component.html'
})
export class My000072Component {
  @Input() parentName: string;
  myName = 'My000072Component';
}
