// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000068Component } from './my.000068.component';

@NgModule({
  declarations: [
    My000068Component,
  ],
  imports: [CommonModule],
  exports: [
    My000068Component,
  ]
})
export class Module000048 { }
