// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000698',
  templateUrl: './my.000698.component.html'
})
export class My000698Component {
  @Input() parentName: string;
  myName = 'My000698Component';
}
