// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000897Component } from './my.000897.component';

@NgModule({
  declarations: [
    My000897Component,
  ],
  imports: [CommonModule],
  exports: [
    My000897Component,
  ]
})
export class Module000797 { }
