// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000997',
  templateUrl: './my.000997.component.html'
})
export class My000997Component {
  @Input() parentName: string;
  myName = 'My000997Component';
}
