// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000863',
  templateUrl: './my.000863.component.html'
})
export class My000863Component {
  @Input() parentName: string;
  myName = 'My000863Component';
}
