// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000471Component } from './my.000471.component';

@NgModule({
  declarations: [
    My000471Component,
  ],
  imports: [CommonModule],
  exports: [
    My000471Component,
  ]
})
export class Module000271 { }
