// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000471',
  templateUrl: './my.000471.component.html'
})
export class My000471Component {
  @Input() parentName: string;
  myName = 'My000471Component';
}
