// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000371',
  templateUrl: './my.000371.component.html'
})
export class My000371Component {
  @Input() parentName: string;
  myName = 'My000371Component';
}
