// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000516',
  templateUrl: './my.000516.component.html'
})
export class My000516Component {
  @Input() parentName: string;
  myName = 'My000516Component';
}
