// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000730Component } from './my.000730.component';

@NgModule({
  declarations: [
    My000730Component,
  ],
  imports: [CommonModule],
  exports: [
    My000730Component,
  ]
})
export class Module000530 { }
