// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000630Component } from './my.000630.component';

@NgModule({
  declarations: [
    My000630Component,
  ],
  imports: [CommonModule],
  exports: [
    My000630Component,
  ]
})
export class Module000530 { }
