// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000730',
  templateUrl: './my.000730.component.html'
})
export class My000730Component {
  @Input() parentName: string;
  myName = 'My000730Component';
}
