// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000920',
  templateUrl: './my.000920.component.html'
})
export class My000920Component {
  @Input() parentName: string;
  myName = 'My000920Component';
}
