// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000110Component } from './my.000110.component';
import { My000111Component } from './my.000111.component';

@NgModule({
  declarations: [
    My000110Component,
    My000111Component,
  ],
  imports: [CommonModule],
  exports: [
    My000110Component,
  ]
})
export class Module000055 { }
