// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000127',
  templateUrl: './my.000127.component.html'
})
export class My000127Component {
  @Input() parentName: string;
  myName = 'My000127Component';
}
