// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000314Component } from './my.000314.component';
import { My000315Component } from './my.000315.component';

@NgModule({
  declarations: [
    My000314Component,
    My000315Component,
  ],
  imports: [CommonModule],
  exports: [
    My000314Component,
  ]
})
export class Module000157 { }
