// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000540Component } from './my.000540.component';

@NgModule({
  declarations: [
    My000540Component,
  ],
  imports: [CommonModule],
  exports: [
    My000540Component,
  ]
})
export class Module000440 { }
