// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000640Component } from './my.000640.component';

@NgModule({
  declarations: [
    My000640Component,
  ],
  imports: [CommonModule],
  exports: [
    My000640Component,
  ]
})
export class Module000440 { }
