// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000237Component } from './my.000237.component';

@NgModule({
  declarations: [
    My000237Component,
  ],
  imports: [CommonModule],
  exports: [
    My000237Component,
  ]
})
export class Module000137 { }
