// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000802',
  templateUrl: './my.000802.component.html'
})
export class My000802Component {
  @Input() parentName: string;
  myName = 'My000802Component';
}
