// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000332Component } from './my.000332.component';
import { My000333Component } from './my.000333.component';

@NgModule({
  declarations: [
    My000332Component,
    My000333Component,
  ],
  imports: [CommonModule],
  exports: [
    My000332Component,
  ]
})
export class Module000166 { }
