// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000266Component } from './my.000266.component';

@NgModule({
  declarations: [
    My000266Component,
  ],
  imports: [CommonModule],
  exports: [
    My000266Component,
  ]
})
export class Module000166 { }
