// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000246Component } from './my.000246.component';

@NgModule({
  declarations: [
    My000246Component,
  ],
  imports: [CommonModule],
  exports: [
    My000246Component,
  ]
})
export class Module000146 { }
