// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000292Component } from './my.000292.component';
import { My000293Component } from './my.000293.component';

@NgModule({
  declarations: [
    My000292Component,
    My000293Component,
  ],
  imports: [CommonModule],
  exports: [
    My000292Component,
  ]
})
export class Module000146 { }
