// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000194',
  templateUrl: './my.000194.component.html'
})
export class My000194Component {
  @Input() parentName: string;
  myName = 'My000194Component';
}
