// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000195',
  templateUrl: './my.000195.component.html'
})
export class My000195Component {
  @Input() parentName: string;
  myName = 'My000195Component';
}
