// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { Module000000 } from './Module000000/Module000000.module';
import { Module000001 } from './Module000001/Module000001.module';
import { DataTableModule } from './data-table/data-table.module';


@NgModule({
  declarations: [
    AppComponent,

  ],
  imports: [
    BrowserModule,
    Module000000,
    Module000001,
    DataTableModule,
    AppRoutingModule
],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
