// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000260',
  templateUrl: './my.000260.component.html'
})
export class My000260Component {
  @Input() parentName: string;
  myName = 'My000260Component';
}
