// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000321',
  templateUrl: './my.000321.component.html'
})
export class My000321Component {
  @Input() parentName: string;
  myName = 'My000321Component';
}
