// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001009',
  templateUrl: './my.001009.component.html'
})
export class My001009Component {
  @Input() parentName: string;
  myName = 'My001009Component';
}
