// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001109',
  templateUrl: './my.001109.component.html'
})
export class My001109Component {
  @Input() parentName: string;
  myName = 'My001109Component';
}
