// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000754Component } from './my.000754.component';

@NgModule({
  declarations: [
    My000754Component,
  ],
  imports: [CommonModule],
  exports: [
    My000754Component,
  ]
})
export class Module000654 { }
