// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000449Component } from './my.000449.component';

@NgModule({
  declarations: [
    My000449Component,
  ],
  imports: [CommonModule],
  exports: [
    My000449Component,
  ]
})
export class Module000349 { }
