// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000549Component } from './my.000549.component';

@NgModule({
  declarations: [
    My000549Component,
  ],
  imports: [CommonModule],
  exports: [
    My000549Component,
  ]
})
export class Module000349 { }
