// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000610',
  templateUrl: './my.000610.component.html'
})
export class My000610Component {
  @Input() parentName: string;
  myName = 'My000610Component';
}
