// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001017',
  templateUrl: './my.001017.component.html'
})
export class My001017Component {
  @Input() parentName: string;
  myName = 'My001017Component';
}
