// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001058Component } from './my.001058.component';

@NgModule({
  declarations: [
    My001058Component,
  ],
  imports: [CommonModule],
  exports: [
    My001058Component,
  ]
})
export class Module000958 { }
