// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001158',
  templateUrl: './my.001158.component.html'
})
export class My001158Component {
  @Input() parentName: string;
  myName = 'My001158Component';
}
