// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000569',
  templateUrl: './my.000569.component.html'
})
export class My000569Component {
  @Input() parentName: string;
  myName = 'My000569Component';
}
