// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000639',
  templateUrl: './my.000639.component.html'
})
export class My000639Component {
  @Input() parentName: string;
  myName = 'My000639Component';
}
