// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000940Component } from './my.000940.component';

@NgModule({
  declarations: [
    My000940Component,
  ],
  imports: [CommonModule],
  exports: [
    My000940Component,
  ]
})
export class Module000740 { }
