// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000940',
  templateUrl: './my.000940.component.html'
})
export class My000940Component {
  @Input() parentName: string;
  myName = 'My000940Component';
}
