// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000167',
  templateUrl: './my.000167.component.html'
})
export class My000167Component {
  @Input() parentName: string;
  myName = 'My000167Component';
}
