// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001024Component } from './my.001024.component';

@NgModule({
  declarations: [
    My001024Component,
  ],
  imports: [CommonModule],
  exports: [
    My001024Component,
  ]
})
export class Module000824 { }
