// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000578Component } from './my.000578.component';

@NgModule({
  declarations: [
    My000578Component,
  ],
  imports: [CommonModule],
  exports: [
    My000578Component,
  ]
})
export class Module000378 { }
