// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000578',
  templateUrl: './my.000578.component.html'
})
export class My000578Component {
  @Input() parentName: string;
  myName = 'My000578Component';
}
