// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000600Component } from './my.000600.component';

@NgModule({
  declarations: [
    My000600Component,
  ],
  imports: [CommonModule],
  exports: [
    My000600Component,
  ]
})
export class Module000400 { }
