// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000291Component } from './my.000291.component';

@NgModule({
  declarations: [
    My000291Component,
  ],
  imports: [CommonModule],
  exports: [
    My000291Component,
  ]
})
export class Module000191 { }
