// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000477Component } from './my.000477.component';

@NgModule({
  declarations: [
    My000477Component,
  ],
  imports: [CommonModule],
  exports: [
    My000477Component,
  ]
})
export class Module000277 { }
