// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000477',
  templateUrl: './my.000477.component.html'
})
export class My000477Component {
  @Input() parentName: string;
  myName = 'My000477Component';
}
