// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000377',
  templateUrl: './my.000377.component.html'
})
export class My000377Component {
  @Input() parentName: string;
  myName = 'My000377Component';
}
