// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001112Component } from './my.001112.component';

@NgModule({
  declarations: [
    My001112Component,
  ],
  imports: [CommonModule],
  exports: [
    My001112Component,
  ]
})
export class Module000912 { }
