// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000074Component } from './my.000074.component';
import { My000075Component } from './my.000075.component';

@NgModule({
  declarations: [
    My000074Component,
    My000075Component,
  ],
  imports: [CommonModule],
  exports: [
    My000074Component,
=======
import { My000057Component } from './my.000057.component';

@NgModule({
  declarations: [
    My000057Component,
  ],
  imports: [CommonModule],
  exports: [
    My000057Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000037 { }
