// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000606Component } from './my.000606.component';

@NgModule({
  declarations: [
    My000606Component,
  ],
  imports: [CommonModule],
  exports: [
    My000606Component,
  ]
})
export class Module000406 { }
