// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000084Component } from './my.000084.component';

@NgModule({
  declarations: [
    My000084Component,
  ],
  imports: [CommonModule],
  exports: [
    My000084Component,
  ]
})
export class Module000064 { }
