// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000128',
  templateUrl: './my.000128.component.html'
})
export class My000128Component {
  @Input() parentName: string;
  myName = 'My000128Component';
}
