// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000683',
  templateUrl: './my.000683.component.html'
})
export class My000683Component {
  @Input() parentName: string;
  myName = 'My000683Component';
}
