// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000690Component } from './my.000690.component';

@NgModule({
  declarations: [
    My000690Component,
  ],
  imports: [CommonModule],
  exports: [
    My000690Component,
  ]
})
export class Module000490 { }
