// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000938Component } from './my.000938.component';

@NgModule({
  declarations: [
    My000938Component,
  ],
  imports: [CommonModule],
  exports: [
    My000938Component,
  ]
})
export class Module000838 { }
