// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001026',
  templateUrl: './my.001026.component.html'
})
export class My001026Component {
  @Input() parentName: string;
  myName = 'My001026Component';
}
