// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001079Component } from './my.001079.component';

@NgModule({
  declarations: [
    My001079Component,
  ],
  imports: [CommonModule],
  exports: [
    My001079Component,
  ]
})
export class Module000979 { }
