// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001079',
  templateUrl: './my.001079.component.html'
})
export class My001079Component {
  @Input() parentName: string;
  myName = 'My001079Component';
}
