// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000975',
  templateUrl: './my.000975.component.html'
})
export class My000975Component {
  @Input() parentName: string;
  myName = 'My000975Component';
}
