// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000325Component } from './my.000325.component';

@NgModule({
  declarations: [
    My000325Component,
  ],
  imports: [CommonModule],
  exports: [
    My000325Component,
  ]
})
export class Module000225 { }
