// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000522Component } from './my.000522.component';

@NgModule({
  declarations: [
    My000522Component,
  ],
  imports: [CommonModule],
  exports: [
    My000522Component,
  ]
})
export class Module000322 { }
