// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000783Component } from './my.000783.component';

@NgModule({
  declarations: [
    My000783Component,
  ],
  imports: [CommonModule],
  exports: [
    My000783Component,
  ]
})
export class Module000583 { }
