// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000783',
  templateUrl: './my.000783.component.html'
})
export class My000783Component {
  @Input() parentName: string;
  myName = 'My000783Component';
}
