// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000054Component } from './my.000054.component';
import { My000055Component } from './my.000055.component';

@NgModule({
  declarations: [
    My000054Component,
    My000055Component,
  ],
  imports: [CommonModule],
  exports: [
    My000054Component,
=======
import { My000047Component } from './my.000047.component';

@NgModule({
  declarations: [
    My000047Component,
  ],
  imports: [CommonModule],
  exports: [
    My000047Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000027 { }
