// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000047',
  templateUrl: './my.000047.component.html'
})
export class My000047Component {
  @Input() parentName: string;
  myName = 'My000047Component';
}
