// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001121Component } from './my.001121.component';

@NgModule({
  declarations: [
    My001121Component,
  ],
  imports: [CommonModule],
  exports: [
    My001121Component,
  ]
})
export class Module000921 { }
