// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001121',
  templateUrl: './my.001121.component.html'
})
export class My001121Component {
  @Input() parentName: string;
  myName = 'My001121Component';
}
