// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000306Component } from './my.000306.component';
import { My000307Component } from './my.000307.component';

@NgModule({
  declarations: [
    My000306Component,
    My000307Component,
  ],
  imports: [CommonModule],
  exports: [
    My000306Component,
  ]
})
export class Module000153 { }
