// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000253',
  templateUrl: './my.000253.component.html'
})
export class My000253Component {
  @Input() parentName: string;
  myName = 'My000253Component';
}
