// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000306',
  templateUrl: './my.000306.component.html'
})
export class My000306Component {
  @Input() parentName: string;
  myName = 'My000306Component';
}
