// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000780Component } from './my.000780.component';

@NgModule({
  declarations: [
    My000780Component,
  ],
  imports: [CommonModule],
  exports: [
    My000780Component,
  ]
})
export class Module000580 { }
