// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001145',
  templateUrl: './my.001145.component.html'
})
export class My001145Component {
  @Input() parentName: string;
  myName = 'My001145Component';
}
