// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000251Component } from './my.000251.component';

@NgModule({
  declarations: [
    My000251Component,
  ],
  imports: [CommonModule],
  exports: [
    My000251Component,
  ]
})
export class Module000151 { }
