// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000078Component } from './my.000078.component';
import { My000079Component } from './my.000079.component';

@NgModule({
  declarations: [
    My000078Component,
    My000079Component,
  ],
  imports: [CommonModule],
  exports: [
    My000078Component,
=======
import { My000059Component } from './my.000059.component';

@NgModule({
  declarations: [
    My000059Component,
  ],
  imports: [CommonModule],
  exports: [
    My000059Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000039 { }
