// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000078',
  templateUrl: './my.000078.component.html'
})
export class My000078Component {
  @Input() parentName: string;
  myName = 'My000078Component';
}
