// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000059',
  templateUrl: './my.000059.component.html'
})
export class My000059Component {
  @Input() parentName: string;
  myName = 'My000059Component';
}
