// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000964Component } from './my.000964.component';

@NgModule({
  declarations: [
    My000964Component,
  ],
  imports: [CommonModule],
  exports: [
    My000964Component,
  ]
})
export class Module000864 { }
