// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001064',
  templateUrl: './my.001064.component.html'
})
export class My001064Component {
  @Input() parentName: string;
  myName = 'My001064Component';
}
