// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000460Component } from './my.000460.component';

@NgModule({
  declarations: [
    My000460Component,
  ],
  imports: [CommonModule],
  exports: [
    My000460Component,
  ]
})
export class Module000260 { }
