// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000360',
  templateUrl: './my.000360.component.html'
})
export class My000360Component {
  @Input() parentName: string;
  myName = 'My000360Component';
}
