// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000503Component } from './my.000503.component';

@NgModule({
  declarations: [
    My000503Component,
  ],
  imports: [CommonModule],
  exports: [
    My000503Component,
  ]
})
export class Module000303 { }
