// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000403',
  templateUrl: './my.000403.component.html'
})
export class My000403Component {
  @Input() parentName: string;
  myName = 'My000403Component';
}
