// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000773Component } from './my.000773.component';

@NgModule({
  declarations: [
    My000773Component,
  ],
  imports: [CommonModule],
  exports: [
    My000773Component,
  ]
})
export class Module000673 { }
