// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000873',
  templateUrl: './my.000873.component.html'
})
export class My000873Component {
  @Input() parentName: string;
  myName = 'My000873Component';
}
