// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000997Component } from './my.000997.component';

@NgModule({
  declarations: [
    My000997Component,
  ],
  imports: [CommonModule],
  exports: [
    My000997Component,
  ]
})
export class Module000897 { }
