// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000259Component } from './my.000259.component';

@NgModule({
  declarations: [
    My000259Component,
  ],
  imports: [CommonModule],
  exports: [
    My000259Component,
  ]
})
export class Module000159 { }
