// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000056',
  templateUrl: './my.000056.component.html'
})
export class My000056Component {
  @Input() parentName: string;
  myName = 'My000056Component';
}
