// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000608Component } from './my.000608.component';

@NgModule({
  declarations: [
    My000608Component,
  ],
  imports: [CommonModule],
  exports: [
    My000608Component,
  ]
})
export class Module000408 { }
