// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000508Component } from './my.000508.component';

@NgModule({
  declarations: [
    My000508Component,
  ],
  imports: [CommonModule],
  exports: [
    My000508Component,
  ]
})
export class Module000408 { }
