// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000508',
  templateUrl: './my.000508.component.html'
})
export class My000508Component {
  @Input() parentName: string;
  myName = 'My000508Component';
}
