// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000741',
  templateUrl: './my.000741.component.html'
})
export class My000741Component {
  @Input() parentName: string;
  myName = 'My000741Component';
}
