// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000867Component } from './my.000867.component';

@NgModule({
  declarations: [
    My000867Component,
  ],
  imports: [CommonModule],
  exports: [
    My000867Component,
  ]
})
export class Module000767 { }
