// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000867',
  templateUrl: './my.000867.component.html'
})
export class My000867Component {
  @Input() parentName: string;
  myName = 'My000867Component';
}
