// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000923Component } from './my.000923.component';

@NgModule({
  declarations: [
    My000923Component,
  ],
  imports: [CommonModule],
  exports: [
    My000923Component,
  ]
})
export class Module000723 { }
