// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000758Component } from './my.000758.component';

@NgModule({
  declarations: [
    My000758Component,
  ],
  imports: [CommonModule],
  exports: [
    My000758Component,
  ]
})
export class Module000558 { }
