// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000658',
  templateUrl: './my.000658.component.html'
})
export class My000658Component {
  @Input() parentName: string;
  myName = 'My000658Component';
}
