// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000369Component } from './my.000369.component';

@NgModule({
  declarations: [
    My000369Component,
  ],
  imports: [CommonModule],
  exports: [
    My000369Component,
  ]
})
export class Module000269 { }
