// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000060Component } from './my.000060.component';

@NgModule({
  declarations: [
    My000060Component,
  ],
  imports: [CommonModule],
  exports: [
    My000060Component,
  ]
})
export class Module000040 { }
