// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000080Component } from './my.000080.component';
import { My000081Component } from './my.000081.component';

@NgModule({
  declarations: [
    My000080Component,
    My000081Component,
  ],
  imports: [CommonModule],
  exports: [
    My000080Component,
=======
import { My000060Component } from './my.000060.component';

@NgModule({
  declarations: [
    My000060Component,
  ],
  imports: [CommonModule],
  exports: [
    My000060Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000040 { }
