// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000060',
  templateUrl: './my.000060.component.html'
})
export class My000060Component {
  @Input() parentName: string;
  myName = 'My000060Component';
}
