// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001045',
  templateUrl: './my.001045.component.html'
})
export class My001045Component {
  @Input() parentName: string;
  myName = 'My001045Component';
}
