// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000465',
  templateUrl: './my.000465.component.html'
})
export class My000465Component {
  @Input() parentName: string;
  myName = 'My000465Component';
}
