// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001088Component } from './my.001088.component';

@NgModule({
  declarations: [
    My001088Component,
  ],
  imports: [CommonModule],
  exports: [
    My001088Component,
  ]
})
export class Module000888 { }
