// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000988Component } from './my.000988.component';

@NgModule({
  declarations: [
    My000988Component,
  ],
  imports: [CommonModule],
  exports: [
    My000988Component,
  ]
})
export class Module000888 { }
