// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000633Component } from './my.000633.component';

@NgModule({
  declarations: [
    My000633Component,
  ],
  imports: [CommonModule],
  exports: [
    My000633Component,
  ]
})
export class Module000533 { }
