// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000633',
  templateUrl: './my.000633.component.html'
})
export class My000633Component {
  @Input() parentName: string;
  myName = 'My000633Component';
}
