// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000806',
  templateUrl: './my.000806.component.html'
})
export class My000806Component {
  @Input() parentName: string;
  myName = 'My000806Component';
}
