// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000837',
  templateUrl: './my.000837.component.html'
})
export class My000837Component {
  @Input() parentName: string;
  myName = 'My000837Component';
}
