// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000737',
  templateUrl: './my.000737.component.html'
})
export class My000737Component {
  @Input() parentName: string;
  myName = 'My000737Component';
}
