// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000738Component } from './my.000738.component';

@NgModule({
  declarations: [
    My000738Component,
  ],
  imports: [CommonModule],
  exports: [
    My000738Component,
  ]
})
export class Module000638 { }
