// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000738',
  templateUrl: './my.000738.component.html'
})
export class My000738Component {
  @Input() parentName: string;
  myName = 'My000738Component';
}
