// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000106',
  templateUrl: './my.000106.component.html'
})
export class My000106Component {
  @Input() parentName: string;
  myName = 'My000106Component';
}
