// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000691Component } from './my.000691.component';

@NgModule({
  declarations: [
    My000691Component,
  ],
  imports: [CommonModule],
  exports: [
    My000691Component,
  ]
})
export class Module000591 { }
