// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000691',
  templateUrl: './my.000691.component.html'
})
export class My000691Component {
  @Input() parentName: string;
  myName = 'My000691Component';
}
