// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000791',
  templateUrl: './my.000791.component.html'
})
export class My000791Component {
  @Input() parentName: string;
  myName = 'My000791Component';
}
