// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000821Component } from './my.000821.component';

@NgModule({
  declarations: [
    My000821Component,
  ],
  imports: [CommonModule],
  exports: [
    My000821Component,
  ]
})
export class Module000621 { }
