// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000821',
  templateUrl: './my.000821.component.html'
})
export class My000821Component {
  @Input() parentName: string;
  myName = 'My000821Component';
}
