// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000811',
  templateUrl: './my.000811.component.html'
})
export class My000811Component {
  @Input() parentName: string;
  myName = 'My000811Component';
}
