// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001139Component } from './my.001139.component';

@NgModule({
  declarations: [
    My001139Component,
  ],
  imports: [CommonModule],
  exports: [
    My001139Component,
  ]
})
export class Module000939 { }
