// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001039',
  templateUrl: './my.001039.component.html'
})
export class My001039Component {
  @Input() parentName: string;
  myName = 'My001039Component';
}
