// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001139',
  templateUrl: './my.001139.component.html'
})
export class My001139Component {
  @Input() parentName: string;
  myName = 'My001139Component';
}
