// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000699',
  templateUrl: './my.000699.component.html'
})
export class My000699Component {
  @Input() parentName: string;
  myName = 'My000699Component';
}
