// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000160Component } from './my.000160.component';
import { My000161Component } from './my.000161.component';

@NgModule({
  declarations: [
    My000160Component,
    My000161Component,
  ],
  imports: [CommonModule],
  exports: [
    My000160Component,
  ]
})
export class Module000080 { }
