// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000161',
  templateUrl: './my.000161.component.html'
})
export class My000161Component {
  @Input() parentName: string;
  myName = 'My000161Component';
}
