// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000006',
  templateUrl: './my.000006.component.html'
})
export class My000006Component {
  @Input() parentName: string;
  myName = 'My000006Component';
}
