// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000748Component } from './my.000748.component';

@NgModule({
  declarations: [
    My000748Component,
  ],
  imports: [CommonModule],
  exports: [
    My000748Component,
  ]
})
export class Module000548 { }
