// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000648',
  templateUrl: './my.000648.component.html'
})
export class My000648Component {
  @Input() parentName: string;
  myName = 'My000648Component';
}
