// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000453Component } from './my.000453.component';

@NgModule({
  declarations: [
    My000453Component,
  ],
  imports: [CommonModule],
  exports: [
    My000453Component,
  ]
})
export class Module000353 { }
