// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000453',
  templateUrl: './my.000453.component.html'
})
export class My000453Component {
  @Input() parentName: string;
  myName = 'My000453Component';
}
