// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001111Component } from './my.001111.component';

@NgModule({
  declarations: [
    My001111Component,
  ],
  imports: [CommonModule],
  exports: [
    My001111Component,
  ]
})
export class Module000911 { }
