// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001111',
  templateUrl: './my.001111.component.html'
})
export class My001111Component {
  @Input() parentName: string;
  myName = 'My001111Component';
}
