// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000827Component } from './my.000827.component';

@NgModule({
  declarations: [
    My000827Component,
  ],
  imports: [CommonModule],
  exports: [
    My000827Component,
  ]
})
export class Module000627 { }
