// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000727',
  templateUrl: './my.000727.component.html'
})
export class My000727Component {
  @Input() parentName: string;
  myName = 'My000727Component';
}
