// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000055',
  templateUrl: './my.000055.component.html'
})
export class My000055Component {
  @Input() parentName: string;
  myName = 'My000055Component';
}
