// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000071',
  templateUrl: './my.000071.component.html'
})
export class My000071Component {
  @Input() parentName: string;
  myName = 'My000071Component';
}
