// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000031',
  templateUrl: './my.000031.component.html'
})
export class My000031Component {
  @Input() parentName: string;
  myName = 'My000031Component';
}
