// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000230Component } from './my.000230.component';

@NgModule({
  declarations: [
    My000230Component,
  ],
  imports: [CommonModule],
  exports: [
    My000230Component,
  ]
})
export class Module000130 { }
