// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000260Component } from './my.000260.component';
import { My000261Component } from './my.000261.component';

@NgModule({
  declarations: [
    My000260Component,
    My000261Component,
  ],
  imports: [CommonModule],
  exports: [
    My000260Component,
  ]
})
export class Module000130 { }
