// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000112Component } from './my.000112.component';

@NgModule({
  declarations: [
    My000112Component,
  ],
  imports: [CommonModule],
  exports: [
    My000112Component,
  ]
})
export class Module000092 { }
