// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000184',
  templateUrl: './my.000184.component.html'
})
export class My000184Component {
  @Input() parentName: string;
  myName = 'My000184Component';
}
