// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001169',
  templateUrl: './my.001169.component.html'
})
export class My001169Component {
  @Input() parentName: string;
  myName = 'My001169Component';
}
