// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000572Component } from './my.000572.component';

@NgModule({
  declarations: [
    My000572Component,
  ],
  imports: [CommonModule],
  exports: [
    My000572Component,
  ]
})
export class Module000372 { }
