// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000472',
  templateUrl: './my.000472.component.html'
})
export class My000472Component {
  @Input() parentName: string;
  myName = 'My000472Component';
}
