// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000572',
  templateUrl: './my.000572.component.html'
})
export class My000572Component {
  @Input() parentName: string;
  myName = 'My000572Component';
}
