// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000525Component } from './my.000525.component';

@NgModule({
  declarations: [
    My000525Component,
  ],
  imports: [CommonModule],
  exports: [
    My000525Component,
  ]
})
export class Module000425 { }
