// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000886Component } from './my.000886.component';

@NgModule({
  declarations: [
    My000886Component,
  ],
  imports: [CommonModule],
  exports: [
    My000886Component,
  ]
})
export class Module000686 { }
