// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000886',
  templateUrl: './my.000886.component.html'
})
export class My000886Component {
  @Input() parentName: string;
  myName = 'My000886Component';
}
