// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000265',
  templateUrl: './my.000265.component.html'
})
export class My000265Component {
  @Input() parentName: string;
  myName = 'My000265Component';
}
