// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000330',
  templateUrl: './my.000330.component.html'
})
export class My000330Component {
  @Input() parentName: string;
  myName = 'My000330Component';
}
