// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000331',
  templateUrl: './my.000331.component.html'
})
export class My000331Component {
  @Input() parentName: string;
  myName = 'My000331Component';
}
