// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000650Component } from './my.000650.component';

@NgModule({
  declarations: [
    My000650Component,
  ],
  imports: [CommonModule],
  exports: [
    My000650Component,
  ]
})
export class Module000550 { }
