// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000596Component } from './my.000596.component';

@NgModule({
  declarations: [
    My000596Component,
  ],
  imports: [CommonModule],
  exports: [
    My000596Component,
  ]
})
export class Module000496 { }
