// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000820Component } from './my.000820.component';

@NgModule({
  declarations: [
    My000820Component,
  ],
  imports: [CommonModule],
  exports: [
    My000820Component,
  ]
})
export class Module000620 { }
