// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000404Component } from './my.000404.component';

@NgModule({
  declarations: [
    My000404Component,
  ],
  imports: [CommonModule],
  exports: [
    My000404Component,
  ]
})
export class Module000304 { }
