// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000504',
  templateUrl: './my.000504.component.html'
})
export class My000504Component {
  @Input() parentName: string;
  myName = 'My000504Component';
}
