// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000563',
  templateUrl: './my.000563.component.html'
})
export class My000563Component {
  @Input() parentName: string;
  myName = 'My000563Component';
}
