// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000463',
  templateUrl: './my.000463.component.html'
})
export class My000463Component {
  @Input() parentName: string;
  myName = 'My000463Component';
}
