// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000288Component } from './my.000288.component';
import { My000289Component } from './my.000289.component';

@NgModule({
  declarations: [
    My000288Component,
    My000289Component,
  ],
  imports: [CommonModule],
  exports: [
    My000288Component,
  ]
})
export class Module000144 { }
