// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000244',
  templateUrl: './my.000244.component.html'
})
export class My000244Component {
  @Input() parentName: string;
  myName = 'My000244Component';
}
