// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001073Component } from './my.001073.component';

@NgModule({
  declarations: [
    My001073Component,
  ],
  imports: [CommonModule],
  exports: [
    My001073Component,
  ]
})
export class Module000873 { }
