// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000973',
  templateUrl: './my.000973.component.html'
})
export class My000973Component {
  @Input() parentName: string;
  myName = 'My000973Component';
}
