// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000275Component } from './my.000275.component';

@NgModule({
  declarations: [
    My000275Component,
  ],
  imports: [CommonModule],
  exports: [
    My000275Component,
  ]
})
export class Module000175 { }
