// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000350',
  templateUrl: './my.000350.component.html'
})
export class My000350Component {
  @Input() parentName: string;
  myName = 'My000350Component';
}
