// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000378Component } from './my.000378.component';
import { My000379Component } from './my.000379.component';

@NgModule({
  declarations: [
    My000378Component,
    My000379Component,
  ],
  imports: [CommonModule],
  exports: [
    My000378Component,
  ]
})
export class Module000189 { }
