// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000289',
  templateUrl: './my.000289.component.html'
})
export class My000289Component {
  @Input() parentName: string;
  myName = 'My000289Component';
}
