// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000382Component } from './my.000382.component';

@NgModule({
  declarations: [
    My000382Component,
  ],
  imports: [CommonModule],
  exports: [
    My000382Component,
  ]
})
export class Module000282 { }
