// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000382',
  templateUrl: './my.000382.component.html'
})
export class My000382Component {
  @Input() parentName: string;
  myName = 'My000382Component';
}
