// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000835',
  templateUrl: './my.000835.component.html'
})
export class My000835Component {
  @Input() parentName: string;
  myName = 'My000835Component';
}
