// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000735',
  templateUrl: './my.000735.component.html'
})
export class My000735Component {
  @Input() parentName: string;
  myName = 'My000735Component';
}
