// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000329Component } from './my.000329.component';

@NgModule({
  declarations: [
    My000329Component,
  ],
  imports: [CommonModule],
  exports: [
    My000329Component,
  ]
})
export class Module000229 { }
