// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000329',
  templateUrl: './my.000329.component.html'
})
export class My000329Component {
  @Input() parentName: string;
  myName = 'My000329Component';
}
