// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000296Component } from './my.000296.component';
import { My000297Component } from './my.000297.component';

@NgModule({
  declarations: [
    My000296Component,
    My000297Component,
  ],
  imports: [CommonModule],
  exports: [
    My000296Component,
  ]
})
export class Module000148 { }
