// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000296',
  templateUrl: './my.000296.component.html'
})
export class My000296Component {
  @Input() parentName: string;
  myName = 'My000296Component';
}
