// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000248',
  templateUrl: './my.000248.component.html'
})
export class My000248Component {
  @Input() parentName: string;
  myName = 'My000248Component';
}
