// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000774',
  templateUrl: './my.000774.component.html'
})
export class My000774Component {
  @Input() parentName: string;
  myName = 'My000774Component';
}
