// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000879',
  templateUrl: './my.000879.component.html'
})
export class My000879Component {
  @Input() parentName: string;
  myName = 'My000879Component';
}
