// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000051Component } from './my.000051.component';

@NgModule({
  declarations: [
    My000051Component,
  ],
  imports: [CommonModule],
  exports: [
    My000051Component,
  ]
})
export class Module000031 { }
