// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000051',
  templateUrl: './my.000051.component.html'
})
export class My000051Component {
  @Input() parentName: string;
  myName = 'My000051Component';
}
