// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000854Component } from './my.000854.component';

@NgModule({
  declarations: [
    My000854Component,
  ],
  imports: [CommonModule],
  exports: [
    My000854Component,
  ]
})
export class Module000754 { }
