// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000954',
  templateUrl: './my.000954.component.html'
})
export class My000954Component {
  @Input() parentName: string;
  myName = 'My000954Component';
}
