// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001082Component } from './my.001082.component';

@NgModule({
  declarations: [
    My001082Component,
  ],
  imports: [CommonModule],
  exports: [
    My001082Component,
  ]
})
export class Module000882 { }
