// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000982',
  templateUrl: './my.000982.component.html'
})
export class My000982Component {
  @Input() parentName: string;
  myName = 'My000982Component';
}
