// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000761Component } from './my.000761.component';

@NgModule({
  declarations: [
    My000761Component,
  ],
  imports: [CommonModule],
  exports: [
    My000761Component,
  ]
})
export class Module000561 { }
