// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000502Component } from './my.000502.component';

@NgModule({
  declarations: [
    My000502Component,
  ],
  imports: [CommonModule],
  exports: [
    My000502Component,
  ]
})
export class Module000402 { }
