// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001130Component } from './my.001130.component';

@NgModule({
  declarations: [
    My001130Component,
  ],
  imports: [CommonModule],
  exports: [
    My001130Component,
  ]
})
export class Module000930 { }
