// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000596',
  templateUrl: './my.000596.component.html'
})
export class My000596Component {
  @Input() parentName: string;
  myName = 'My000596Component';
}
