// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000609Component } from './my.000609.component';

@NgModule({
  declarations: [
    My000609Component,
  ],
  imports: [CommonModule],
  exports: [
    My000609Component,
  ]
})
export class Module000409 { }
