// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000509',
  templateUrl: './my.000509.component.html'
})
export class My000509Component {
  @Input() parentName: string;
  myName = 'My000509Component';
}
