// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000348Component } from './my.000348.component';

@NgModule({
  declarations: [
    My000348Component,
  ],
  imports: [CommonModule],
  exports: [
    My000348Component,
  ]
})
export class Module000248 { }
