// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000448',
  templateUrl: './my.000448.component.html'
})
export class My000448Component {
  @Input() parentName: string;
  myName = 'My000448Component';
}
