// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000946Component } from './my.000946.component';

@NgModule({
  declarations: [
    My000946Component,
  ],
  imports: [CommonModule],
  exports: [
    My000946Component,
  ]
})
export class Module000746 { }
