// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000946',
  templateUrl: './my.000946.component.html'
})
export class My000946Component {
  @Input() parentName: string;
  myName = 'My000946Component';
}
