// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000605Component } from './my.000605.component';

@NgModule({
  declarations: [
    My000605Component,
  ],
  imports: [CommonModule],
  exports: [
    My000605Component,
  ]
})
export class Module000405 { }
