// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000505',
  templateUrl: './my.000505.component.html'
})
export class My000505Component {
  @Input() parentName: string;
  myName = 'My000505Component';
}
