// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000605',
  templateUrl: './my.000605.component.html'
})
export class My000605Component {
  @Input() parentName: string;
  myName = 'My000605Component';
}
