// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000810',
  templateUrl: './my.000810.component.html'
})
export class My000810Component {
  @Input() parentName: string;
  myName = 'My000810Component';
}
