// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000852Component } from './my.000852.component';

@NgModule({
  declarations: [
    My000852Component,
  ],
  imports: [CommonModule],
  exports: [
    My000852Component,
  ]
})
export class Module000652 { }
