// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001089Component } from './my.001089.component';

@NgModule({
  declarations: [
    My001089Component,
  ],
  imports: [CommonModule],
  exports: [
    My001089Component,
  ]
})
export class Module000889 { }
