// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001089',
  templateUrl: './my.001089.component.html'
})
export class My001089Component {
  @Input() parentName: string;
  myName = 'My001089Component';
}
