// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000705',
  templateUrl: './my.000705.component.html'
})
export class My000705Component {
  @Input() parentName: string;
  myName = 'My000705Component';
}
