// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000694Component } from './my.000694.component';

@NgModule({
  declarations: [
    My000694Component,
  ],
  imports: [CommonModule],
  exports: [
    My000694Component,
  ]
})
export class Module000494 { }
