// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001196Component } from './my.001196.component';

@NgModule({
  declarations: [
    My001196Component,
  ],
  imports: [CommonModule],
  exports: [
    My001196Component,
  ]
})
export class Module000996 { }
