// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001096',
  templateUrl: './my.001096.component.html'
})
export class My001096Component {
  @Input() parentName: string;
  myName = 'My001096Component';
}
