// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000144Component } from './my.000144.component';
import { My000145Component } from './my.000145.component';

@NgModule({
  declarations: [
    My000144Component,
    My000145Component,
  ],
  imports: [CommonModule],
  exports: [
    My000144Component,
  ]
})
export class Module000072 { }
