// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000390Component } from './my.000390.component';

@NgModule({
  declarations: [
    My000390Component,
  ],
  imports: [CommonModule],
  exports: [
    My000390Component,
  ]
})
export class Module000290 { }
