// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000556Component } from './my.000556.component';

@NgModule({
  declarations: [
    My000556Component,
  ],
  imports: [CommonModule],
  exports: [
    My000556Component,
  ]
})
export class Module000356 { }
