// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000456',
  templateUrl: './my.000456.component.html'
})
export class My000456Component {
  @Input() parentName: string;
  myName = 'My000456Component';
}
