// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000788',
  templateUrl: './my.000788.component.html'
})
export class My000788Component {
  @Input() parentName: string;
  myName = 'My000788Component';
}
