// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000318Component } from './my.000318.component';

@NgModule({
  declarations: [
    My000318Component,
  ],
  imports: [CommonModule],
  exports: [
    My000318Component,
  ]
})
export class Module000218 { }
