// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000372Component } from './my.000372.component';

@NgModule({
  declarations: [
    My000372Component,
  ],
  imports: [CommonModule],
  exports: [
    My000372Component,
  ]
})
export class Module000272 { }
