// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000567',
  templateUrl: './my.000567.component.html'
})
export class My000567Component {
  @Input() parentName: string;
  myName = 'My000567Component';
}
