// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001178Component } from './my.001178.component';

@NgModule({
  declarations: [
    My001178Component,
  ],
  imports: [CommonModule],
  exports: [
    My001178Component,
  ]
})
export class Module000978 { }
