// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001078',
  templateUrl: './my.001078.component.html'
})
export class My001078Component {
  @Input() parentName: string;
  myName = 'My001078Component';
}
