// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000301Component } from './my.000301.component';

@NgModule({
  declarations: [
    My000301Component,
  ],
  imports: [CommonModule],
  exports: [
    My000301Component,
  ]
})
export class Module000201 { }
