// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000125',
  templateUrl: './my.000125.component.html'
})
export class My000125Component {
  @Input() parentName: string;
  myName = 'My000125Component';
}
