// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000725Component } from './my.000725.component';

@NgModule({
  declarations: [
    My000725Component,
  ],
  imports: [CommonModule],
  exports: [
    My000725Component,
  ]
})
export class Module000625 { }
