// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001100',
  templateUrl: './my.001100.component.html'
})
export class My001100Component {
  @Input() parentName: string;
  myName = 'My001100Component';
}
