// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000046Component } from './my.000046.component';
import { My000047Component } from './my.000047.component';

@NgModule({
  declarations: [
    My000046Component,
    My000047Component,
  ],
  imports: [CommonModule],
  exports: [
    My000046Component,
  ]
})
export class Module000023 { }
