// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000576Component } from './my.000576.component';

@NgModule({
  declarations: [
    My000576Component,
  ],
  imports: [CommonModule],
  exports: [
    My000576Component,
  ]
})
export class Module000476 { }
