// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000238Component } from './my.000238.component';
import { My000239Component } from './my.000239.component';

@NgModule({
  declarations: [
    My000238Component,
    My000239Component,
  ],
  imports: [CommonModule],
  exports: [
    My000238Component,
  ]
})
export class Module000119 { }
