// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000219Component } from './my.000219.component';

@NgModule({
  declarations: [
    My000219Component,
  ],
  imports: [CommonModule],
  exports: [
    My000219Component,
  ]
})
export class Module000119 { }
