// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000830',
  templateUrl: './my.000830.component.html'
})
export class My000830Component {
  @Input() parentName: string;
  myName = 'My000830Component';
}
