// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001132Component } from './my.001132.component';

@NgModule({
  declarations: [
    My001132Component,
  ],
  imports: [CommonModule],
  exports: [
    My001132Component,
  ]
})
export class Module000932 { }
