// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000777Component } from './my.000777.component';

@NgModule({
  declarations: [
    My000777Component,
  ],
  imports: [CommonModule],
  exports: [
    My000777Component,
  ]
})
export class Module000577 { }
