// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000650',
  templateUrl: './my.000650.component.html'
})
export class My000650Component {
  @Input() parentName: string;
  myName = 'My000650Component';
}
