// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001167Component } from './my.001167.component';

@NgModule({
  declarations: [
    My001167Component,
  ],
  imports: [CommonModule],
  exports: [
    My001167Component,
  ]
})
export class Module000967 { }
