// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001167',
  templateUrl: './my.001167.component.html'
})
export class My001167Component {
  @Input() parentName: string;
  myName = 'My001167Component';
}
