// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000890Component } from './my.000890.component';

@NgModule({
  declarations: [
    My000890Component,
  ],
  imports: [CommonModule],
  exports: [
    My000890Component,
  ]
})
export class Module000690 { }
