// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000890',
  templateUrl: './my.000890.component.html'
})
export class My000890Component {
  @Input() parentName: string;
  myName = 'My000890Component';
}
