// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000747Component } from './my.000747.component';

@NgModule({
  declarations: [
    My000747Component,
  ],
  imports: [CommonModule],
  exports: [
    My000747Component,
  ]
})
export class Module000647 { }
