// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000847Component } from './my.000847.component';

@NgModule({
  declarations: [
    My000847Component,
  ],
  imports: [CommonModule],
  exports: [
    My000847Component,
  ]
})
export class Module000647 { }
