// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000747',
  templateUrl: './my.000747.component.html'
})
export class My000747Component {
  @Input() parentName: string;
  myName = 'My000747Component';
}
