// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000561Component } from './my.000561.component';

@NgModule({
  declarations: [
    My000561Component,
  ],
  imports: [CommonModule],
  exports: [
    My000561Component,
  ]
})
export class Module000461 { }
