// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000690',
  templateUrl: './my.000690.component.html'
})
export class My000690Component {
  @Input() parentName: string;
  myName = 'My000690Component';
}
