// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000790',
  templateUrl: './my.000790.component.html'
})
export class My000790Component {
  @Input() parentName: string;
  myName = 'My000790Component';
}
