// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000374Component } from './my.000374.component';
import { My000375Component } from './my.000375.component';

@NgModule({
  declarations: [
    My000374Component,
    My000375Component,
  ],
  imports: [CommonModule],
  exports: [
    My000374Component,
  ]
})
export class Module000187 { }
