// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000374',
  templateUrl: './my.000374.component.html'
})
export class My000374Component {
  @Input() parentName: string;
  myName = 'My000374Component';
}
