// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000877Component } from './my.000877.component';

@NgModule({
  declarations: [
    My000877Component,
  ],
  imports: [CommonModule],
  exports: [
    My000877Component,
  ]
})
export class Module000777 { }
