// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000812Component } from './my.000812.component';

@NgModule({
  declarations: [
    My000812Component,
  ],
  imports: [CommonModule],
  exports: [
    My000812Component,
  ]
})
export class Module000612 { }
