// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000971Component } from './my.000971.component';

@NgModule({
  declarations: [
    My000971Component,
  ],
  imports: [CommonModule],
  exports: [
    My000971Component,
  ]
})
export class Module000871 { }
