// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001071',
  templateUrl: './my.001071.component.html'
})
export class My001071Component {
  @Input() parentName: string;
  myName = 'My001071Component';
}
