// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000340Component } from './my.000340.component';
import { My000341Component } from './my.000341.component';

@NgModule({
  declarations: [
    My000340Component,
    My000341Component,
  ],
  imports: [CommonModule],
  exports: [
    My000340Component,
  ]
})
export class Module000170 { }
