// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000270',
  templateUrl: './my.000270.component.html'
})
export class My000270Component {
  @Input() parentName: string;
  myName = 'My000270Component';
}
