// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000340',
  templateUrl: './my.000340.component.html'
})
export class My000340Component {
  @Input() parentName: string;
  myName = 'My000340Component';
}
