// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000341',
  templateUrl: './my.000341.component.html'
})
export class My000341Component {
  @Input() parentName: string;
  myName = 'My000341Component';
}
