// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000903Component } from './my.000903.component';

@NgModule({
  declarations: [
    My000903Component,
  ],
  imports: [CommonModule],
  exports: [
    My000903Component,
  ]
})
export class Module000703 { }
