// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000967',
  templateUrl: './my.000967.component.html'
})
export class My000967Component {
  @Input() parentName: string;
  myName = 'My000967Component';
}
