// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000648Component } from './my.000648.component';

@NgModule({
  declarations: [
    My000648Component,
  ],
  imports: [CommonModule],
  exports: [
    My000648Component,
  ]
})
export class Module000448 { }
