// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000410',
  templateUrl: './my.000410.component.html'
})
export class My000410Component {
  @Input() parentName: string;
  myName = 'My000410Component';
}
