// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000116Component } from './my.000116.component';
import { My000117Component } from './my.000117.component';

@NgModule({
  declarations: [
    My000116Component,
    My000117Component,
  ],
  imports: [CommonModule],
  exports: [
    My000116Component,
  ]
})
export class Module000058 { }
