// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000078Component } from './my.000078.component';

@NgModule({
  declarations: [
    My000078Component,
  ],
  imports: [CommonModule],
  exports: [
    My000078Component,
  ]
})
export class Module000058 { }
