// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000117',
  templateUrl: './my.000117.component.html'
})
export class My000117Component {
  @Input() parentName: string;
  myName = 'My000117Component';
}
