// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000479',
  templateUrl: './my.000479.component.html'
})
export class My000479Component {
  @Input() parentName: string;
  myName = 'My000479Component';
}
