// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000933Component } from './my.000933.component';

@NgModule({
  declarations: [
    My000933Component,
  ],
  imports: [CommonModule],
  exports: [
    My000933Component,
  ]
})
export class Module000833 { }
