// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001033',
  templateUrl: './my.001033.component.html'
})
export class My001033Component {
  @Input() parentName: string;
  myName = 'My001033Component';
}
