// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000764',
  templateUrl: './my.000764.component.html'
})
export class My000764Component {
  @Input() parentName: string;
  myName = 'My000764Component';
}
