// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000864',
  templateUrl: './my.000864.component.html'
})
export class My000864Component {
  @Input() parentName: string;
  myName = 'My000864Component';
}
