// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001146Component } from './my.001146.component';

@NgModule({
  declarations: [
    My001146Component,
  ],
  imports: [CommonModule],
  exports: [
    My001146Component,
  ]
})
export class Module000946 { }
