// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001046',
  templateUrl: './my.001046.component.html'
})
export class My001046Component {
  @Input() parentName: string;
  myName = 'My001046Component';
}
