// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000645Component } from './my.000645.component';

@NgModule({
  declarations: [
    My000645Component,
  ],
  imports: [CommonModule],
  exports: [
    My000645Component,
  ]
})
export class Module000445 { }
