// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000545',
  templateUrl: './my.000545.component.html'
})
export class My000545Component {
  @Input() parentName: string;
  myName = 'My000545Component';
}
