// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000611Component } from './my.000611.component';

@NgModule({
  declarations: [
    My000611Component,
  ],
  imports: [CommonModule],
  exports: [
    My000611Component,
  ]
})
export class Module000411 { }
