// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000611',
  templateUrl: './my.000611.component.html'
})
export class My000611Component {
  @Input() parentName: string;
  myName = 'My000611Component';
}
