// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000511',
  templateUrl: './my.000511.component.html'
})
export class My000511Component {
  @Input() parentName: string;
  myName = 'My000511Component';
}
