// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000813',
  templateUrl: './my.000813.component.html'
})
export class My000813Component {
  @Input() parentName: string;
  myName = 'My000813Component';
}
