// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000353',
  templateUrl: './my.000353.component.html'
})
export class My000353Component {
  @Input() parentName: string;
  myName = 'My000353Component';
}
