// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000220',
  templateUrl: './my.000220.component.html'
})
export class My000220Component {
  @Input() parentName: string;
  myName = 'My000220Component';
}
