// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000523Component } from './my.000523.component';

@NgModule({
  declarations: [
    My000523Component,
  ],
  imports: [CommonModule],
  exports: [
    My000523Component,
  ]
})
export class Module000323 { }
