// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000763Component } from './my.000763.component';

@NgModule({
  declarations: [
    My000763Component,
  ],
  imports: [CommonModule],
  exports: [
    My000763Component,
  ]
})
export class Module000563 { }
