// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000916',
  templateUrl: './my.000916.component.html'
})
export class My000916Component {
  @Input() parentName: string;
  myName = 'My000916Component';
}
