// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000784Component } from './my.000784.component';

@NgModule({
  declarations: [
    My000784Component,
  ],
  imports: [CommonModule],
  exports: [
    My000784Component,
  ]
})
export class Module000584 { }
