// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000343',
  templateUrl: './my.000343.component.html'
})
export class My000343Component {
  @Input() parentName: string;
  myName = 'My000343Component';
}
