// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000271',
  templateUrl: './my.000271.component.html'
})
export class My000271Component {
  @Input() parentName: string;
  myName = 'My000271Component';
}
