// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000311Component } from './my.000311.component';

@NgModule({
  declarations: [
    My000311Component,
  ],
  imports: [CommonModule],
  exports: [
    My000311Component,
  ]
})
export class Module000211 { }
