// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000484Component } from './my.000484.component';

@NgModule({
  declarations: [
    My000484Component,
  ],
  imports: [CommonModule],
  exports: [
    My000484Component,
  ]
})
export class Module000384 { }
