// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000004',
  templateUrl: './my.000004.component.html'
})
export class My000004Component {
  @Input() parentName: string;
  myName = 'My000004Component';
}
