// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000649Component } from './my.000649.component';

@NgModule({
  declarations: [
    My000649Component,
  ],
  imports: [CommonModule],
  exports: [
    My000649Component,
  ]
})
export class Module000549 { }
