// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000749',
  templateUrl: './my.000749.component.html'
})
export class My000749Component {
  @Input() parentName: string;
  myName = 'My000749Component';
}
