// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000649',
  templateUrl: './my.000649.component.html'
})
export class My000649Component {
  @Input() parentName: string;
  myName = 'My000649Component';
}
