// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000591Component } from './my.000591.component';

@NgModule({
  declarations: [
    My000591Component,
  ],
  imports: [CommonModule],
  exports: [
    My000591Component,
  ]
})
export class Module000391 { }
