// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000625',
  templateUrl: './my.000625.component.html'
})
export class My000625Component {
  @Input() parentName: string;
  myName = 'My000625Component';
}
