// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000725',
  templateUrl: './my.000725.component.html'
})
export class My000725Component {
  @Input() parentName: string;
  myName = 'My000725Component';
}
