// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000358Component } from './my.000358.component';
import { My000359Component } from './my.000359.component';

@NgModule({
  declarations: [
    My000358Component,
    My000359Component,
  ],
  imports: [CommonModule],
  exports: [
    My000358Component,
  ]
})
export class Module000179 { }
