// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000279Component } from './my.000279.component';

@NgModule({
  declarations: [
    My000279Component,
  ],
  imports: [CommonModule],
  exports: [
    My000279Component,
  ]
})
export class Module000179 { }
