// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000970Component } from './my.000970.component';

@NgModule({
  declarations: [
    My000970Component,
  ],
  imports: [CommonModule],
  exports: [
    My000970Component,
  ]
})
export class Module000870 { }
