// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000979Component } from './my.000979.component';

@NgModule({
  declarations: [
    My000979Component,
  ],
  imports: [CommonModule],
  exports: [
    My000979Component,
  ]
})
export class Module000879 { }
