// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000979',
  templateUrl: './my.000979.component.html'
})
export class My000979Component {
  @Input() parentName: string;
  myName = 'My000979Component';
}
