// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000558',
  templateUrl: './my.000558.component.html'
})
export class My000558Component {
  @Input() parentName: string;
  myName = 'My000558Component';
}
