// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000388',
  templateUrl: './my.000388.component.html'
})
export class My000388Component {
  @Input() parentName: string;
  myName = 'My000388Component';
}
