// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000437',
  templateUrl: './my.000437.component.html'
})
export class My000437Component {
  @Input() parentName: string;
  myName = 'My000437Component';
}
