// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000654Component } from './my.000654.component';

@NgModule({
  declarations: [
    My000654Component,
  ],
  imports: [CommonModule],
  exports: [
    My000654Component,
  ]
})
export class Module000454 { }
