// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000693Component } from './my.000693.component';

@NgModule({
  declarations: [
    My000693Component,
  ],
  imports: [CommonModule],
  exports: [
    My000693Component,
  ]
})
export class Module000493 { }
