// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000239',
  templateUrl: './my.000239.component.html'
})
export class My000239Component {
  @Input() parentName: string;
  myName = 'My000239Component';
}
