// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000986Component } from './my.000986.component';

@NgModule({
  declarations: [
    My000986Component,
  ],
  imports: [CommonModule],
  exports: [
    My000986Component,
  ]
})
export class Module000786 { }
