// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000181',
  templateUrl: './my.000181.component.html'
})
export class My000181Component {
  @Input() parentName: string;
  myName = 'My000181Component';
}
