// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000180',
  templateUrl: './my.000180.component.html'
})
export class My000180Component {
  @Input() parentName: string;
  myName = 'My000180Component';
}
