// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001072Component } from './my.001072.component';

@NgModule({
  declarations: [
    My001072Component,
  ],
  imports: [CommonModule],
  exports: [
    My001072Component,
  ]
})
export class Module000872 { }
