// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001072',
  templateUrl: './my.001072.component.html'
})
export class My001072Component {
  @Input() parentName: string;
  myName = 'My001072Component';
}
