// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000209Component } from './my.000209.component';

@NgModule({
  declarations: [
    My000209Component,
  ],
  imports: [CommonModule],
  exports: [
    My000209Component,
  ]
})
export class Module000109 { }
