// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000660Component } from './my.000660.component';

@NgModule({
  declarations: [
    My000660Component,
  ],
  imports: [CommonModule],
  exports: [
    My000660Component,
  ]
})
export class Module000560 { }
