// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000846',
  templateUrl: './my.000846.component.html'
})
export class My000846Component {
  @Input() parentName: string;
  myName = 'My000846Component';
}
