// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000282',
  templateUrl: './my.000282.component.html'
})
export class My000282Component {
  @Input() parentName: string;
  myName = 'My000282Component';
}
