// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000762Component } from './my.000762.component';

@NgModule({
  declarations: [
    My000762Component,
  ],
  imports: [CommonModule],
  exports: [
    My000762Component,
  ]
})
export class Module000562 { }
