// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000590Component } from './my.000590.component';

@NgModule({
  declarations: [
    My000590Component,
  ],
  imports: [CommonModule],
  exports: [
    My000590Component,
  ]
})
export class Module000390 { }
