// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000590',
  templateUrl: './my.000590.component.html'
})
export class My000590Component {
  @Input() parentName: string;
  myName = 'My000590Component';
}
