// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000536',
  templateUrl: './my.000536.component.html'
})
export class My000536Component {
  @Input() parentName: string;
  myName = 'My000536Component';
}
