// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000008',
  templateUrl: './my.000008.component.html'
})
export class My000008Component {
  @Input() parentName: string;
  myName = 'My000008Component';
}
