// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001156Component } from './my.001156.component';

@NgModule({
  declarations: [
    My001156Component,
  ],
  imports: [CommonModule],
  exports: [
    My001156Component,
  ]
})
export class Module000956 { }
