// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001025Component } from './my.001025.component';

@NgModule({
  declarations: [
    My001025Component,
  ],
  imports: [CommonModule],
  exports: [
    My001025Component,
  ]
})
export class Module000925 { }
