// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001025',
  templateUrl: './my.001025.component.html'
})
export class My001025Component {
  @Input() parentName: string;
  myName = 'My001025Component';
}
