// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000208Component } from './my.000208.component';

@NgModule({
  declarations: [
    My000208Component,
  ],
  imports: [CommonModule],
  exports: [
    My000208Component,
  ]
})
export class Module000108 { }
