// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000216Component } from './my.000216.component';
import { My000217Component } from './my.000217.component';

@NgModule({
  declarations: [
    My000216Component,
    My000217Component,
  ],
  imports: [CommonModule],
  exports: [
    My000216Component,
  ]
})
export class Module000108 { }
