// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000217',
  templateUrl: './my.000217.component.html'
})
export class My000217Component {
  @Input() parentName: string;
  myName = 'My000217Component';
}
