// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000208',
  templateUrl: './my.000208.component.html'
})
export class My000208Component {
  @Input() parentName: string;
  myName = 'My000208Component';
}
