// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001047Component } from './my.001047.component';

@NgModule({
  declarations: [
    My001047Component,
  ],
  imports: [CommonModule],
  exports: [
    My001047Component,
  ]
})
export class Module000947 { }
