// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001147Component } from './my.001147.component';

@NgModule({
  declarations: [
    My001147Component,
  ],
  imports: [CommonModule],
  exports: [
    My001147Component,
  ]
})
export class Module000947 { }
