// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001147',
  templateUrl: './my.001147.component.html'
})
export class My001147Component {
  @Input() parentName: string;
  myName = 'My001147Component';
}
