// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000118Component } from './my.000118.component';

@NgModule({
  declarations: [
    My000118Component,
  ],
  imports: [CommonModule],
  exports: [
    My000118Component,
  ]
})
export class Module000098 { }
