// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000197',
  templateUrl: './my.000197.component.html'
})
export class My000197Component {
  @Input() parentName: string;
  myName = 'My000197Component';
}
