// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000196',
  templateUrl: './my.000196.component.html'
})
export class My000196Component {
  @Input() parentName: string;
  myName = 'My000196Component';
}
