// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000794Component } from './my.000794.component';

@NgModule({
  declarations: [
    My000794Component,
  ],
  imports: [CommonModule],
  exports: [
    My000794Component,
  ]
})
export class Module000694 { }
