// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000589Component } from './my.000589.component';

@NgModule({
  declarations: [
    My000589Component,
  ],
  imports: [CommonModule],
  exports: [
    My000589Component,
  ]
})
export class Module000489 { }
