// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000817Component } from './my.000817.component';

@NgModule({
  declarations: [
    My000817Component,
  ],
  imports: [CommonModule],
  exports: [
    My000817Component,
  ]
})
export class Module000617 { }
