// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000817',
  templateUrl: './my.000817.component.html'
})
export class My000817Component {
  @Input() parentName: string;
  myName = 'My000817Component';
}
