// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000869Component } from './my.000869.component';

@NgModule({
  declarations: [
    My000869Component,
  ],
  imports: [CommonModule],
  exports: [
    My000869Component,
  ]
})
export class Module000769 { }
