// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000727Component } from './my.000727.component';

@NgModule({
  declarations: [
    My000727Component,
  ],
  imports: [CommonModule],
  exports: [
    My000727Component,
  ]
})
export class Module000527 { }
