// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000000Component } from './my.000000.component';
import { My000001Component } from './my.000001.component';
import { My000002Component } from './my.000002.component';

@NgModule({
  declarations: [
    My000000Component,
    My000001Component,
    My000002Component,
  ],
  imports: [CommonModule],
  exports: [
    My000000Component,
  ]
})
export class Module000000 { }
