// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000002',
  templateUrl: './my.000002.component.html'
})
export class My000002Component {
  @Input() parentName: string;
  myName = 'My000002Component';
}
