// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000140Component } from './my.000140.component';
import { My000141Component } from './my.000141.component';

@NgModule({
  declarations: [
    My000140Component,
    My000141Component,
  ],
  imports: [CommonModule],
  exports: [
    My000140Component,
  ]
})
export class Module000070 { }
