// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000141',
  templateUrl: './my.000141.component.html'
})
export class My000141Component {
  @Input() parentName: string;
  myName = 'My000141Component';
}
