// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000090',
  templateUrl: './my.000090.component.html'
})
export class My000090Component {
  @Input() parentName: string;
  myName = 'My000090Component';
}
