// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000158',
  templateUrl: './my.000158.component.html'
})
export class My000158Component {
  @Input() parentName: string;
  myName = 'My000158Component';
}
