// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000995Component } from './my.000995.component';

@NgModule({
  declarations: [
    My000995Component,
  ],
  imports: [CommonModule],
  exports: [
    My000995Component,
  ]
})
export class Module000795 { }
