// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000766Component } from './my.000766.component';

@NgModule({
  declarations: [
    My000766Component,
  ],
  imports: [CommonModule],
  exports: [
    My000766Component,
  ]
})
export class Module000666 { }
