// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000372Component } from './my.000372.component';
import { My000373Component } from './my.000373.component';

@NgModule({
  declarations: [
    My000372Component,
    My000373Component,
  ],
  imports: [CommonModule],
  exports: [
    My000372Component,
  ]
})
export class Module000186 { }
