// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000965',
  templateUrl: './my.000965.component.html'
})
export class My000965Component {
  @Input() parentName: string;
  myName = 'My000965Component';
}
