// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000276Component } from './my.000276.component';

@NgModule({
  declarations: [
    My000276Component,
  ],
  imports: [CommonModule],
  exports: [
    My000276Component,
  ]
})
export class Module000176 { }
