// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000276',
  templateUrl: './my.000276.component.html'
})
export class My000276Component {
  @Input() parentName: string;
  myName = 'My000276Component';
}
