// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000746Component } from './my.000746.component';

@NgModule({
  declarations: [
    My000746Component,
  ],
  imports: [CommonModule],
  exports: [
    My000746Component,
  ]
})
export class Module000546 { }
