// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000646',
  templateUrl: './my.000646.component.html'
})
export class My000646Component {
  @Input() parentName: string;
  myName = 'My000646Component';
}
