// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000987Component } from './my.000987.component';

@NgModule({
  declarations: [
    My000987Component,
  ],
  imports: [CommonModule],
  exports: [
    My000987Component,
  ]
})
export class Module000887 { }
