// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001083',
  templateUrl: './my.001083.component.html'
})
export class My001083Component {
  @Input() parentName: string;
  myName = 'My001083Component';
}
