// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001183',
  templateUrl: './my.001183.component.html'
})
export class My001183Component {
  @Input() parentName: string;
  myName = 'My001183Component';
}
