// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000346Component } from './my.000346.component';

@NgModule({
  declarations: [
    My000346Component,
  ],
  imports: [CommonModule],
  exports: [
    My000346Component,
  ]
})
export class Module000246 { }
