// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000563Component } from './my.000563.component';

@NgModule({
  declarations: [
    My000563Component,
  ],
  imports: [CommonModule],
  exports: [
    My000563Component,
  ]
})
export class Module000463 { }
