// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000663Component } from './my.000663.component';

@NgModule({
  declarations: [
    My000663Component,
  ],
  imports: [CommonModule],
  exports: [
    My000663Component,
  ]
})
export class Module000463 { }
