// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000183',
  templateUrl: './my.000183.component.html'
})
export class My000183Component {
  @Input() parentName: string;
  myName = 'My000183Component';
}
