// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001115Component } from './my.001115.component';

@NgModule({
  declarations: [
    My001115Component,
  ],
  imports: [CommonModule],
  exports: [
    My001115Component,
  ]
})
export class Module000915 { }
