// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001015',
  templateUrl: './my.001015.component.html'
})
export class My001015Component {
  @Input() parentName: string;
  myName = 'My001015Component';
}
