// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000559Component } from './my.000559.component';

@NgModule({
  declarations: [
    My000559Component,
  ],
  imports: [CommonModule],
  exports: [
    My000559Component,
  ]
})
export class Module000459 { }
