// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000659Component } from './my.000659.component';

@NgModule({
  declarations: [
    My000659Component,
  ],
  imports: [CommonModule],
  exports: [
    My000659Component,
  ]
})
export class Module000459 { }
