// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000732',
  templateUrl: './my.000732.component.html'
})
export class My000732Component {
  @Input() parentName: string;
  myName = 'My000732Component';
}
