// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001092',
  templateUrl: './my.001092.component.html'
})
export class My001092Component {
  @Input() parentName: string;
  myName = 'My001092Component';
}
