// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000034',
  templateUrl: './my.000034.component.html'
})
export class My000034Component {
  @Input() parentName: string;
  myName = 'My000034Component';
}
