// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000835Component } from './my.000835.component';

@NgModule({
  declarations: [
    My000835Component,
  ],
  imports: [CommonModule],
  exports: [
    My000835Component,
  ]
})
export class Module000735 { }
