// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000833Component } from './my.000833.component';

@NgModule({
  declarations: [
    My000833Component,
  ],
  imports: [CommonModule],
  exports: [
    My000833Component,
  ]
})
export class Module000633 { }
