// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000733Component } from './my.000733.component';

@NgModule({
  declarations: [
    My000733Component,
  ],
  imports: [CommonModule],
  exports: [
    My000733Component,
  ]
})
export class Module000633 { }
