// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000461Component } from './my.000461.component';

@NgModule({
  declarations: [
    My000461Component,
  ],
  imports: [CommonModule],
  exports: [
    My000461Component,
  ]
})
export class Module000361 { }
