// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001143',
  templateUrl: './my.001143.component.html'
})
export class My001143Component {
  @Input() parentName: string;
  myName = 'My001143Component';
}
