// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000101Component } from './my.000101.component';

@NgModule({
  declarations: [
    My000101Component,
  ],
  imports: [CommonModule],
  exports: [
    My000101Component,
  ]
})
export class Module000081 { }
