// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000163',
  templateUrl: './my.000163.component.html'
})
export class My000163Component {
  @Input() parentName: string;
  myName = 'My000163Component';
}
