// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001107Component } from './my.001107.component';

@NgModule({
  declarations: [
    My001107Component,
  ],
  imports: [CommonModule],
  exports: [
    My001107Component,
  ]
})
export class Module000907 { }
