// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001007',
  templateUrl: './my.001007.component.html'
})
export class My001007Component {
  @Input() parentName: string;
  myName = 'My001007Component';
}
