// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000837Component } from './my.000837.component';

@NgModule({
  declarations: [
    My000837Component,
  ],
  imports: [CommonModule],
  exports: [
    My000837Component,
  ]
})
export class Module000737 { }
