// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000231',
  templateUrl: './my.000231.component.html'
})
export class My000231Component {
  @Input() parentName: string;
  myName = 'My000231Component';
}
