// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000222',
  templateUrl: './my.000222.component.html'
})
export class My000222Component {
  @Input() parentName: string;
  myName = 'My000222Component';
}
