// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000745',
  templateUrl: './my.000745.component.html'
})
export class My000745Component {
  @Input() parentName: string;
  myName = 'My000745Component';
}
