// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000921Component } from './my.000921.component';

@NgModule({
  declarations: [
    My000921Component,
  ],
  imports: [CommonModule],
  exports: [
    My000921Component,
  ]
})
export class Module000721 { }
