// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000921',
  templateUrl: './my.000921.component.html'
})
export class My000921Component {
  @Input() parentName: string;
  myName = 'My000921Component';
}
