// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000601',
  templateUrl: './my.000601.component.html'
})
export class My000601Component {
  @Input() parentName: string;
  myName = 'My000601Component';
}
