// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001187Component } from './my.001187.component';

@NgModule({
  declarations: [
    My001187Component,
  ],
  imports: [CommonModule],
  exports: [
    My001187Component,
  ]
})
export class Module000987 { }
