// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001087',
  templateUrl: './my.001087.component.html'
})
export class My001087Component {
  @Input() parentName: string;
  myName = 'My001087Component';
}
