// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000022',
  templateUrl: './my.000022.component.html'
})
export class My000022Component {
  @Input() parentName: string;
  myName = 'My000022Component';
}
