// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000865',
  templateUrl: './my.000865.component.html'
})
export class My000865Component {
  @Input() parentName: string;
  myName = 'My000865Component';
}
