// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000911Component } from './my.000911.component';

@NgModule({
  declarations: [
    My000911Component,
  ],
  imports: [CommonModule],
  exports: [
    My000911Component,
  ]
})
export class Module000711 { }
