// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000811Component } from './my.000811.component';

@NgModule({
  declarations: [
    My000811Component,
  ],
  imports: [CommonModule],
  exports: [
    My000811Component,
  ]
})
export class Module000711 { }
