// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000468Component } from './my.000468.component';

@NgModule({
  declarations: [
    My000468Component,
  ],
  imports: [CommonModule],
  exports: [
    My000468Component,
  ]
})
export class Module000268 { }
