// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000368',
  templateUrl: './my.000368.component.html'
})
export class My000368Component {
  @Input() parentName: string;
  myName = 'My000368Component';
}
