// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001061Component } from './my.001061.component';

@NgModule({
  declarations: [
    My001061Component,
  ],
  imports: [CommonModule],
  exports: [
    My001061Component,
  ]
})
export class Module000961 { }
