// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000036Component } from './my.000036.component';
import { My000037Component } from './my.000037.component';

@NgModule({
  declarations: [
    My000036Component,
    My000037Component,
  ],
  imports: [CommonModule],
  exports: [
    My000036Component,
  ]
})
export class Module000018 { }
