// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000294Component } from './my.000294.component';
import { My000295Component } from './my.000295.component';

@NgModule({
  declarations: [
    My000294Component,
    My000295Component,
  ],
  imports: [CommonModule],
  exports: [
    My000294Component,
  ]
})
export class Module000147 { }
