// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000042Component } from './my.000042.component';

@NgModule({
  declarations: [
    My000042Component,
  ],
  imports: [CommonModule],
  exports: [
    My000042Component,
  ]
})
export class Module000022 { }
