// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000044',
  templateUrl: './my.000044.component.html'
})
export class My000044Component {
  @Input() parentName: string;
  myName = 'My000044Component';
}
