// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001194Component } from './my.001194.component';

@NgModule({
  declarations: [
    My001194Component,
  ],
  imports: [CommonModule],
  exports: [
    My001194Component,
  ]
})
export class Module000994 { }
