// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001194',
  templateUrl: './my.001194.component.html'
})
export class My001194Component {
  @Input() parentName: string;
  myName = 'My001194Component';
}
