// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001085Component } from './my.001085.component';

@NgModule({
  declarations: [
    My001085Component,
  ],
  imports: [CommonModule],
  exports: [
    My001085Component,
  ]
})
export class Module000885 { }
