// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000100Component } from './my.000100.component';
import { My000101Component } from './my.000101.component';

@NgModule({
  declarations: [
    My000100Component,
    My000101Component,
  ],
  imports: [CommonModule],
  exports: [
    My000100Component,
=======
import { My000070Component } from './my.000070.component';

@NgModule({
  declarations: [
    My000070Component,
  ],
  imports: [CommonModule],
  exports: [
    My000070Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000050 { }
