// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000261Component } from './my.000261.component';

@NgModule({
  declarations: [
    My000261Component,
  ],
  imports: [CommonModule],
  exports: [
    My000261Component,
  ]
})
export class Module000161 { }
