// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000322',
  templateUrl: './my.000322.component.html'
})
export class My000322Component {
  @Input() parentName: string;
  myName = 'My000322Component';
}
