// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000094Component } from './my.000094.component';

@NgModule({
  declarations: [
    My000094Component,
  ],
  imports: [CommonModule],
  exports: [
    My000094Component,
  ]
})
export class Module000074 { }
