// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001022Component } from './my.001022.component';

@NgModule({
  declarations: [
    My001022Component,
  ],
  imports: [CommonModule],
  exports: [
    My001022Component,
  ]
})
export class Module000922 { }
