// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001122Component } from './my.001122.component';

@NgModule({
  declarations: [
    My001122Component,
  ],
  imports: [CommonModule],
  exports: [
    My001122Component,
  ]
})
export class Module000922 { }
