// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001022',
  templateUrl: './my.001022.component.html'
})
export class My001022Component {
  @Input() parentName: string;
  myName = 'My001022Component';
}
