// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000795Component } from './my.000795.component';

@NgModule({
  declarations: [
    My000795Component,
  ],
  imports: [CommonModule],
  exports: [
    My000795Component,
  ]
})
export class Module000695 { }
