// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000895',
  templateUrl: './my.000895.component.html'
})
export class My000895Component {
  @Input() parentName: string;
  myName = 'My000895Component';
}
