// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000707Component } from './my.000707.component';

@NgModule({
  declarations: [
    My000707Component,
  ],
  imports: [CommonModule],
  exports: [
    My000707Component,
  ]
})
export class Module000607 { }
