// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000888',
  templateUrl: './my.000888.component.html'
})
export class My000888Component {
  @Input() parentName: string;
  myName = 'My000888Component';
}
