// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001185',
  templateUrl: './my.001185.component.html'
})
export class My001185Component {
  @Input() parentName: string;
  myName = 'My001185Component';
}
