// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001035Component } from './my.001035.component';

@NgModule({
  declarations: [
    My001035Component,
  ],
  imports: [CommonModule],
  exports: [
    My001035Component,
  ]
})
export class Module000935 { }
