// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001135',
  templateUrl: './my.001135.component.html'
})
export class My001135Component {
  @Input() parentName: string;
  myName = 'My001135Component';
}
