// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000076',
  templateUrl: './my.000076.component.html'
})
export class My000076Component {
  @Input() parentName: string;
  myName = 'My000076Component';
}
