// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000512Component } from './my.000512.component';

@NgModule({
  declarations: [
    My000512Component,
  ],
  imports: [CommonModule],
  exports: [
    My000512Component,
  ]
})
export class Module000312 { }
