// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000412',
  templateUrl: './my.000412.component.html'
})
export class My000412Component {
  @Input() parentName: string;
  myName = 'My000412Component';
}
