// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001175Component } from './my.001175.component';

@NgModule({
  declarations: [
    My001175Component,
  ],
  imports: [CommonModule],
  exports: [
    My001175Component,
  ]
})
export class Module000975 { }
