// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001175',
  templateUrl: './my.001175.component.html'
})
export class My001175Component {
  @Input() parentName: string;
  myName = 'My001175Component';
}
