// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001098',
  templateUrl: './my.001098.component.html'
})
export class My001098Component {
  @Input() parentName: string;
  myName = 'My001098Component';
}
