// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000962Component } from './my.000962.component';

@NgModule({
  declarations: [
    My000962Component,
  ],
  imports: [CommonModule],
  exports: [
    My000962Component,
  ]
})
export class Module000862 { }
