// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001062Component } from './my.001062.component';

@NgModule({
  declarations: [
    My001062Component,
  ],
  imports: [CommonModule],
  exports: [
    My001062Component,
  ]
})
export class Module000862 { }
