// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000962',
  templateUrl: './my.000962.component.html'
})
export class My000962Component {
  @Input() parentName: string;
  myName = 'My000962Component';
}
