// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000631',
  templateUrl: './my.000631.component.html'
})
export class My000631Component {
  @Input() parentName: string;
  myName = 'My000631Component';
}
