// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001186Component } from './my.001186.component';

@NgModule({
  declarations: [
    My001186Component,
  ],
  imports: [CommonModule],
  exports: [
    My001186Component,
  ]
})
export class Module000986 { }
