// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000871Component } from './my.000871.component';

@NgModule({
  declarations: [
    My000871Component,
  ],
  imports: [CommonModule],
  exports: [
    My000871Component,
  ]
})
export class Module000671 { }
