// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000871',
  templateUrl: './my.000871.component.html'
})
export class My000871Component {
  @Input() parentName: string;
  myName = 'My000871Component';
}
