// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000362Component } from './my.000362.component';
import { My000363Component } from './my.000363.component';

@NgModule({
  declarations: [
    My000362Component,
    My000363Component,
  ],
  imports: [CommonModule],
  exports: [
    My000362Component,
  ]
})
export class Module000181 { }
