// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000363',
  templateUrl: './my.000363.component.html'
})
export class My000363Component {
  @Input() parentName: string;
  myName = 'My000363Component';
}
