// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000216',
  templateUrl: './my.000216.component.html'
})
export class My000216Component {
  @Input() parentName: string;
  myName = 'My000216Component';
}
