// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000233',
  templateUrl: './my.000233.component.html'
})
export class My000233Component {
  @Input() parentName: string;
  myName = 'My000233Component';
}
