// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000954Component } from './my.000954.component';

@NgModule({
  declarations: [
    My000954Component,
  ],
  imports: [CommonModule],
  exports: [
    My000954Component,
  ]
})
export class Module000854 { }
