// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001054',
  templateUrl: './my.001054.component.html'
})
export class My001054Component {
  @Input() parentName: string;
  myName = 'My001054Component';
}
