// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000223',
  templateUrl: './my.000223.component.html'
})
export class My000223Component {
  @Input() parentName: string;
  myName = 'My000223Component';
}
