// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000662Component } from './my.000662.component';

@NgModule({
  declarations: [
    My000662Component,
  ],
  imports: [CommonModule],
  exports: [
    My000662Component,
  ]
})
export class Module000462 { }
