// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000562',
  templateUrl: './my.000562.component.html'
})
export class My000562Component {
  @Input() parentName: string;
  myName = 'My000562Component';
}
