// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001166Component } from './my.001166.component';

@NgModule({
  declarations: [
    My001166Component,
  ],
  imports: [CommonModule],
  exports: [
    My001166Component,
  ]
})
export class Module000966 { }
