// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001066Component } from './my.001066.component';

@NgModule({
  declarations: [
    My001066Component,
  ],
  imports: [CommonModule],
  exports: [
    My001066Component,
  ]
})
export class Module000966 { }
