// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000692',
  templateUrl: './my.000692.component.html'
})
export class My000692Component {
  @Input() parentName: string;
  myName = 'My000692Component';
}
