// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000718',
  templateUrl: './my.000718.component.html'
})
export class My000718Component {
  @Input() parentName: string;
  myName = 'My000718Component';
}
