// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000575',
  templateUrl: './my.000575.component.html'
})
export class My000575Component {
  @Input() parentName: string;
  myName = 'My000575Component';
}
