// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000475',
  templateUrl: './my.000475.component.html'
})
export class My000475Component {
  @Input() parentName: string;
  myName = 'My000475Component';
}
