// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000256Component } from './my.000256.component';

@NgModule({
  declarations: [
    My000256Component,
  ],
  imports: [CommonModule],
  exports: [
    My000256Component,
  ]
})
export class Module000156 { }
