// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000312Component } from './my.000312.component';
import { My000313Component } from './my.000313.component';

@NgModule({
  declarations: [
    My000312Component,
    My000313Component,
  ],
  imports: [CommonModule],
  exports: [
    My000312Component,
  ]
})
export class Module000156 { }
