// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000568',
  templateUrl: './my.000568.component.html'
})
export class My000568Component {
  @Input() parentName: string;
  myName = 'My000568Component';
}
