// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000152Component } from './my.000152.component';
import { My000153Component } from './my.000153.component';

@NgModule({
  declarations: [
    My000152Component,
    My000153Component,
  ],
  imports: [CommonModule],
  exports: [
    My000152Component,
=======
import { My000096Component } from './my.000096.component';

@NgModule({
  declarations: [
    My000096Component,
  ],
  imports: [CommonModule],
  exports: [
    My000096Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000076 { }
