// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000153',
  templateUrl: './my.000153.component.html'
})
export class My000153Component {
  @Input() parentName: string;
  myName = 'My000153Component';
}
