// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000152',
  templateUrl: './my.000152.component.html'
})
export class My000152Component {
  @Input() parentName: string;
  myName = 'My000152Component';
}
