// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000306Component } from './my.000306.component';

@NgModule({
  declarations: [
    My000306Component,
  ],
  imports: [CommonModule],
  exports: [
    My000306Component,
  ]
})
export class Module000206 { }
