// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000643Component } from './my.000643.component';

@NgModule({
  declarations: [
    My000643Component,
  ],
  imports: [CommonModule],
  exports: [
    My000643Component,
  ]
})
export class Module000443 { }
