// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000643',
  templateUrl: './my.000643.component.html'
})
export class My000643Component {
  @Input() parentName: string;
  myName = 'My000643Component';
}
