// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000324Component } from './my.000324.component';

@NgModule({
  declarations: [
    My000324Component,
  ],
  imports: [CommonModule],
  exports: [
    My000324Component,
  ]
})
export class Module000224 { }
