// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000973Component } from './my.000973.component';

@NgModule({
  declarations: [
    My000973Component,
  ],
  imports: [CommonModule],
  exports: [
    My000973Component,
  ]
})
export class Module000773 { }
