// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000066',
  templateUrl: './my.000066.component.html'
})
export class My000066Component {
  @Input() parentName: string;
  myName = 'My000066Component';
}
