// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000945Component } from './my.000945.component';

@NgModule({
  declarations: [
    My000945Component,
  ],
  imports: [CommonModule],
  exports: [
    My000945Component,
  ]
})
export class Module000745 { }
