// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000845Component } from './my.000845.component';

@NgModule({
  declarations: [
    My000845Component,
  ],
  imports: [CommonModule],
  exports: [
    My000845Component,
  ]
})
export class Module000745 { }
