// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001192Component } from './my.001192.component';

@NgModule({
  declarations: [
    My001192Component,
  ],
  imports: [CommonModule],
  exports: [
    My001192Component,
  ]
})
export class Module000992 { }
