// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001192',
  templateUrl: './my.001192.component.html'
})
export class My001192Component {
  @Input() parentName: string;
  myName = 'My001192Component';
}
