// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000106Component } from './my.000106.component';

@NgModule({
  declarations: [
    My000106Component,
  ],
  imports: [CommonModule],
  exports: [
    My000106Component,
  ]
})
export class Module000086 { }
