// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000172',
  templateUrl: './my.000172.component.html'
})
export class My000172Component {
  @Input() parentName: string;
  myName = 'My000172Component';
}
