// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000929',
  templateUrl: './my.000929.component.html'
})
export class My000929Component {
  @Input() parentName: string;
  myName = 'My000929Component';
}
