// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000999Component } from './my.000999.component';

@NgModule({
  declarations: [
    My000999Component,
  ],
  imports: [CommonModule],
  exports: [
    My000999Component,
  ]
})
export class Module000799 { }
