// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000999',
  templateUrl: './my.000999.component.html'
})
export class My000999Component {
  @Input() parentName: string;
  myName = 'My000999Component';
}
