// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000428Component } from './my.000428.component';

@NgModule({
  declarations: [
    My000428Component,
  ],
  imports: [CommonModule],
  exports: [
    My000428Component,
  ]
})
export class Module000328 { }
