// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000926',
  templateUrl: './my.000926.component.html'
})
export class My000926Component {
  @Input() parentName: string;
  myName = 'My000926Component';
}
