// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001009Component } from './my.001009.component';

@NgModule({
  declarations: [
    My001009Component,
  ],
  imports: [CommonModule],
  exports: [
    My001009Component,
  ]
})
export class Module000809 { }
