// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001124Component } from './my.001124.component';

@NgModule({
  declarations: [
    My001124Component,
  ],
  imports: [CommonModule],
  exports: [
    My001124Component,
  ]
})
export class Module000924 { }
