// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000949Component } from './my.000949.component';

@NgModule({
  declarations: [
    My000949Component,
  ],
  imports: [CommonModule],
  exports: [
    My000949Component,
  ]
})
export class Module000749 { }
