// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000849',
  templateUrl: './my.000849.component.html'
})
export class My000849Component {
  @Input() parentName: string;
  myName = 'My000849Component';
}
