// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000174',
  templateUrl: './my.000174.component.html'
})
export class My000174Component {
  @Input() parentName: string;
  myName = 'My000174Component';
}
