// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000387',
  templateUrl: './my.000387.component.html'
})
export class My000387Component {
  @Input() parentName: string;
  myName = 'My000387Component';
}
