// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

<<<<<<< HEAD
import { My000188Component } from './my.000188.component';
import { My000189Component } from './my.000189.component';

@NgModule({
  declarations: [
    My000188Component,
    My000189Component,
  ],
  imports: [CommonModule],
  exports: [
    My000188Component,
=======
import { My000114Component } from './my.000114.component';

@NgModule({
  declarations: [
    My000114Component,
  ],
  imports: [CommonModule],
  exports: [
    My000114Component,
>>>>>>> 4946175... bazel with angular stress test
  ]
})
export class Module000094 { }
