// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000188',
  templateUrl: './my.000188.component.html'
})
export class My000188Component {
  @Input() parentName: string;
  myName = 'My000188Component';
}
