// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000189',
  templateUrl: './my.000189.component.html'
})
export class My000189Component {
  @Input() parentName: string;
  myName = 'My000189Component';
}
