// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000114',
  templateUrl: './my.000114.component.html'
})
export class My000114Component {
  @Input() parentName: string;
  myName = 'My000114Component';
}
