// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000757Component } from './my.000757.component';

@NgModule({
  declarations: [
    My000757Component,
  ],
  imports: [CommonModule],
  exports: [
    My000757Component,
  ]
})
export class Module000557 { }
