// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000615Component } from './my.000615.component';

@NgModule({
  declarations: [
    My000615Component,
  ],
  imports: [CommonModule],
  exports: [
    My000615Component,
  ]
})
export class Module000415 { }
