// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000615',
  templateUrl: './my.000615.component.html'
})
export class My000615Component {
  @Input() parentName: string;
  myName = 'My000615Component';
}
