// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000656',
  templateUrl: './my.000656.component.html'
})
export class My000656Component {
  @Input() parentName: string;
  myName = 'My000656Component';
}
