// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001118',
  templateUrl: './my.001118.component.html'
})
export class My001118Component {
  @Input() parentName: string;
  myName = 'My001118Component';
}
