// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001050',
  templateUrl: './my.001050.component.html'
})
export class My001050Component {
  @Input() parentName: string;
  myName = 'My001050Component';
}
