// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000950',
  templateUrl: './my.000950.component.html'
})
export class My000950Component {
  @Input() parentName: string;
  myName = 'My000950Component';
}
