// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000459Component } from './my.000459.component';

@NgModule({
  declarations: [
    My000459Component,
  ],
  imports: [CommonModule],
  exports: [
    My000459Component,
  ]
})
export class Module000359 { }
