// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000459',
  templateUrl: './my.000459.component.html'
})
export class My000459Component {
  @Input() parentName: string;
  myName = 'My000459Component';
}
