// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000529Component } from './my.000529.component';

@NgModule({
  declarations: [
    My000529Component,
  ],
  imports: [CommonModule],
  exports: [
    My000529Component,
  ]
})
export class Module000329 { }
