// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000429',
  templateUrl: './my.000429.component.html'
})
export class My000429Component {
  @Input() parentName: string;
  myName = 'My000429Component';
}
