// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000881Component } from './my.000881.component';

@NgModule({
  declarations: [
    My000881Component,
  ],
  imports: [CommonModule],
  exports: [
    My000881Component,
  ]
})
export class Module000681 { }
