// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001031Component } from './my.001031.component';

@NgModule({
  declarations: [
    My001031Component,
  ],
  imports: [CommonModule],
  exports: [
    My001031Component,
  ]
})
export class Module000931 { }
