// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001131Component } from './my.001131.component';

@NgModule({
  declarations: [
    My001131Component,
  ],
  imports: [CommonModule],
  exports: [
    My001131Component,
  ]
})
export class Module000931 { }
