// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000717',
  templateUrl: './my.000717.component.html'
})
export class My000717Component {
  @Input() parentName: string;
  myName = 'My000717Component';
}
