// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000716Component } from './my.000716.component';

@NgModule({
  declarations: [
    My000716Component,
  ],
  imports: [CommonModule],
  exports: [
    My000716Component,
  ]
})
export class Module000516 { }
