// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000885Component } from './my.000885.component';

@NgModule({
  declarations: [
    My000885Component,
  ],
  imports: [CommonModule],
  exports: [
    My000885Component,
  ]
})
export class Module000685 { }
