// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000785Component } from './my.000785.component';

@NgModule({
  declarations: [
    My000785Component,
  ],
  imports: [CommonModule],
  exports: [
    My000785Component,
  ]
})
export class Module000685 { }
