// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000885',
  templateUrl: './my.000885.component.html'
})
export class My000885Component {
  @Input() parentName: string;
  myName = 'My000885Component';
}
