// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000785',
  templateUrl: './my.000785.component.html'
})
export class My000785Component {
  @Input() parentName: string;
  myName = 'My000785Component';
}
